### ISSUE TITLE
Some project names do not appear in project list

### ISSUE THREAD

**Issue by medikoo** [alefragnani/vscode-project-manager#105]
I found that if I name my project with name that starts with `_` (e.g. `_test`), it's not available in project list, and I'm not able to switch to it using one of Project commands.

I can understand that there can be some restrictions on project name format, but in such case there should be some validation at _save_ step, currently you can create such project without issues, it just remains not accessible thereafter.

**Comment by alefragnani** [comment]
Hi @medikoo ,

I couln't reproduce this error. I could save the project name using **'_'** in any place (start, middle or end) with no problem. I can even _filter_ the projects using **'_'**.

Just a tip: If you _Save a Project_ and then _List them_ it will not be visible, because _you are at that project_ and the list removes the current project from the list.

Could you check if the project was saved in `projects.json` file? You could use the `Edit Projects` command to see.

**Comment by medikoo** [comment]
Hi @alefragnani Indeed issue is not related to project name, as I thought. It appears that this project remains not accessible in windows (projects) which were opened before new project was saved (in other window).

Fact that it's not accessible in own project window is totally fine.

Other improvement would be sort projects by most recently used and not in alphabetical order.
Usually you want to switch back to most recent (but let me open other request for that :)

**Comment by alefragnani** [comment]
I think it is a duplicate of https://github.com/alefragnani/vscode-project-manager/issues/85, am I right?

**Comment by medikoo** [comment]
@alefragnani true, I'm going to close that one
