### ISSUE TITLE
Duplicated projects in project list after 0.15.0 update

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#113]
At the same time I noticed #111, I also started noticing projects being duplicated in the project list sometimes:

![](http://i.imgur.com/VK8rKN5.png)

The issue only goes away when the cache is refreshed, a VSCode restart doesn't help. The projects are actually duplicated in the `projects_cache_git` / `projects_cache_vscode.json` files.

I haven't it reported it until now because I couldn't figure out a way to reproduce it reliably. After a bit of experimentation, I think it's related to pressing the "list projects" shortcut multiple times after the cache was invalidated - this ends up happening quite often, as there's little visual feedback that project-manager is doing work in the background  (so it seems like the shortcut simply didn't do anything at first). Does project-manager launch multiple scans in this case?

**Comment by alefragnani** [comment]
Hi @Gama11 ,

Since it uses an asynchronous approach to generate the list of projects, and you call `List Projects` multiple times, then yes, you may end up _overloading_ the process. The only _visual feedback_ that it uses today is updating the `Status Bar`, and I use the `Status Bar` instead of a `Message` because the `Status Bar` has a _hide timeout_, so the user doesn't need to click any button.

Maybe fixing #111 you won't see this anymore, right?

**Comment by Gama11** [comment]
>Maybe fixing #111 you won't see this anymore, right?

Yeah, if project-manager responds close to instantly again, it may become impossible to reproduce this. However, it seems like there should still be a check to prevent this from happening, just to be safe?

**Comment by alefragnani** [comment]
It should be fixed with release 0.15.1, which fixes #111.

**Comment by Gama11** [comment]
Awesome, thanks! 👍
