### ISSUE TITLE
Workspace vscode/settings.json

### ISSUE THREAD

**Issue by 1st** [alefragnani/vscode-project-manager#114]
Each workspace creates `.vscode/settings.json` file in the top folder.

I need to change this behavior, because some extensions put some files in this directory. I need to save all settings about all projects in the `~/.vscode` global folder. It will allow me to save all project files in one place `~/.vscode/workspaces/project_name/settings.json` (project is a workspace).  In this case we can set project name in the `settings.json` for each workspace file.

When any extension will write any additional files (like cache files) they will put them to the `~/.vscode/workspaces/project_name/` folder, instead of `project_name/.vscode/` folder.

What do you think about such implementation? Can you implement it, or it requires changes in the VS Code?

**Comment by alefragnani** [comment]
Hi @1st ,

I think you are mixing two different things here. Some from the VSCode itself and other from extensions (this and others).

VSCode only save `$your_project/.vscode/settings.json` if you do something in `Workspace Settings`. If you configure `User Settings`, if I remember right, it will save in `~/.config/Code/User/settings.json`. The same goes to `keybindings`. I think you are using Linux, right? I'm on Windows, which uses `$HOMEDIR\\AppData\\Roaming\\Code`

This extension saves the project list in `~/.config/Code/User/projects.json. The _caches_ are saved in the same location. On the other hand, it does not save anything in `$your_project/.vscode`. 

Other extensions, depends on each developer's decision. If is something related to the _workspace_, it _should_ be saved in `$your_project/.vscode`, otherwise, in that `~...` location.

You could try to use `--user-data-dir` command line switch. More info in https://github.com/Microsoft/vscode/issues/329
