### ISSUE TITLE
suport macOS native Tabs

### ISSUE THREAD

**Issue by kitian616** [alefragnani/vscode-project-manager#117]
vscode version 1.12 now suport macOS native Tabs. it would be great if it can open a new project in a new tab.

**Comment by alefragnani** [comment]
Hi @kitian616 ,

Unfortunately I don't have a Mac anymore :cry:. Would you be able to make a PR?

**Comment by kitian616** [comment]
thx for your reply. seems that VSCode didn't provide any api for the macOS native tab.

**Comment by alefragnani** [comment]
Hi @kitian616 ,

I had the opportunity to use a MacOS and test the `window.nativeTabs` setting. What I could see is that the extension _already supports_ NativeTabs 😄 .

If you set `window.nativeTabs` to `true`, and use the `List Projects to Open in New Window` command, the new window is effectively created in a new _NativeTab_, instead of a new window.

Being so, I'm closing the issue.

Hope this helps

**Comment by ctf0** [comment]
> If you set window.nativeTabs to true, and use the List Projects to Open in New Window command, the new window is effectively created in a new NativeTab, instead of a new window.

> Being so, I'm closing the issue.

@alefragnani sadly this is not working

**Comment by ctf0** [comment]
> Hi @ctf0 ,
> 
> I just tested the setting and it is working as before. (I don't use NativeTabs btw).
> 
> In fact, the extension does nothing about the setting. It only asks VS Code to open the project in a new window. Is up to VS Code itself to manage the Native Tab behavior.
> 
> Is Native Tabs working if you use other native commands, like `Open Recent`? I guess it must be an issue in VS Code, because nothing changed in the extension, and no warn was made on recent release notes/APIs.
> 
> Hope this helps

i also tried to test doing what am after using macros but it didnt work because of 2 things
- the macro is being executed in the old tab which is a vscode is treating it as a different instance so project selection cmnd wont work as expected
- the open project in new window has to be executed in the new tab otherwise vscode will open an actual new window

**Comment by alefragnani** [comment]
I’m not sure what you mean about `macros`. 

Is it a VS Code extension or MacOS tool/feature?

**Comment by ctf0** [comment]
extension

**Comment by alefragnani** [comment]
Well, I don't know how this extension works, but if the Project Manager extension works by itself (via regular commands), I guess something in this macros extension must be updated/fixed to deal with some change in recent releases of VS Code.

By the way, are testing using an _empty_ workspace? If yes, take a look at the `projectManager.openInCurrentWindowIfEmpty` setting, as it can make the `Open in New Window` opens the project in the same window, if it is empty.

Hope this helps
