### ISSUE TITLE
Add a 'projectManager.openInNewWindowWhenClickingTheStatusBar' setting

### ISSUE THREAD

**Issue by sparrc** [alefragnani/vscode-project-manager#123]
I've just updated to 0.17 and found that my projects no longer open in a new window, could you please consider re-adding this setting?

That, or have some setting for when clicking on the status bar it should use `List Projects to Open in New Window` instead of just the regular `List Projects`

That being said, I would prefer if it just always opened in a new window. Personally I don't ever want to open a new project in the same window and I liked having that configuration option.

**Comment by alefragnani** [comment]
Hi @sparrc ,

Sorry to hear that 😢 . The intention was to _avoid more conflict_ with the new command created some releases ago `List Projects to Open in New Window', since its default value was `true`. Doing so, the users could just use the new command, maybe with a new keybinding. Personally, I defined `Ctrl + Shift + Alt + P` to the  `List Projects to Open in New Window' command. 

The use could become simpler with #76.

I thought about the Status Bar, but decided to remove from that as well. I didn't know how useful it was. I think I could add a config specifically for that, as you suggested 👍 

Hope that helps.

**Comment by egabrum** [comment]
@sparrc Came here exactly to say the same thing.

**Comment by davegillem** [comment]
This became even more useful with the latest ` "window.nativeTabs": true` setting in the most recent VSCode release since the new window setting by clicking the name in the status bar would now cause it to open in a new tab (which is awesome). Hope to see this back soon.

**Comment by alefragnani** [comment]
Sadly, I can't test this `nativeTabs` feature, since I don't have a Mac available to test anymore :cry:

Maybe someone could make a PR with this.

**Comment by carrbrpoa** [comment]
Sorry, but where do you put that setting? Is it through `File > Preferences > Settings`?

**Comment by alefragnani** [comment]
@carrbrpoa exactly. just add `"projectManager.openInNewWindowWhenClickingInStatusBar": true` and _reload VSCode_.

**Comment by carrbrpoa** [comment]
Was missing the reload, thanks!

**Comment by egabrum** [comment]
Wonderful. Thanks.
For some reason, I was clicking on `"projectManager.openInNewWindowWhenClickingInStatusBar": true,` and it wasn't inserting it in my settings.json . Had to do it manually.

Anyhow, works like a charm (after reload). thanks
