### ISSUE TITLE
Projects with same rootPath behave strange

### ISSUE THREAD

**Issue by hensz** [alefragnani/vscode-project-manager#124]
Hi!
I set up some projects with the same rootPath but different names, just for the purpose of saving the currently open files (as it's possible with MyLyn tasks in Eclipse). But switching between (or rather to one of) those projects only works if I'm in a project with a different rootPath.

Here's a sketch of my projects.json:
	{
		"name": "src",
		"rootPath": "/my/src/",
		"paths": [],
		"group": ""
	},
	{
		"name": "src2",
		"rootPath": "/my/src/",
		"paths": [],
		"group": ""
	},
	{
		"name": "src3",
		"rootPath": "/my/src/",
		"paths": [],
		"group": ""
	},
	{
		"name": "subsrc",
		"rootPath": "/my/src/sub",
		"paths": [],
		"group": ""
	}

If I'm in project subsrc List Projects shows all three projects src, src2 and src3. When I select e.g. src, then List Projects only shows subsrc, but not src2 and src3. Also the open files in src are also open in src2 and src3.

Can you comment on this? Is this intended or a bug?

**Comment by alefragnani** [comment]
Hi @hensz ,

It doesn't show `src2` or `src3` because their `rootPath` is the same as _the current opened project_.  Unfortunately, when you open a project, it won't know if you selected `src`, `src2` or `src3`, since VS Code open _the folder_, with no relation to the project name.

But, I didn't understand why you duplicated the projects. If I remember right, VS Code will save the _opened files_ based on the _opened folder_, not the _project_, because in this case, the _project name_ is not a VS Code concept, but extension...

Hope this helps

**Comment by hensz** [comment]
Hi @alefragnani!

So it works as intended, thanks for clarifying!
As I said, my intention was to simulate the behavior of MyLyn for Eclipse: With this extension you can create tasks for a project (which is in fact the source folder, you cannot create multiple projects for the same folder in Eclipse), and MyLyn stores the open files for each task. This help focusing on a task even when switching between different tasks.

My hope was that your extension works in a similar way, but obviously this is not the case... Is it possible to extend Project Manager in this way? Or do you (or anyone else reading this ;-) know a different solution for my need?

Best regards,
Torsten

**Comment by alefragnani** [comment]
Hi @hensz ,

No problem, I was just trying to understand your scenario, because I never heard about MyLyn.

Unfortunately, I don't see this extension simulating MyLyn. It's main purpose is just _easily switch between projects/folders_, with no extra information about the project (which is an abstract concept). 

I think your better option is to have a new extension, _porting_ MyLyn to VSCode. 

- If you intend to have the whole ALM and Task Focused interface, you may be out of luck (for now) because the VS Code API restricts what you can do in UX terms, unless you access some external URL with its contents. 
- If you just need to detect the opened project, based on some file _inside the folder_ and have some interaction with your tasks, it would be more reliable, since _(if I understood correctly)_ the task repository/info is in BugZilla/Track/others.

What was your idea about a _MyLyn like_ extension in VS Code?
