### ISSUE TITLE
auto run task or command when switching project

### ISSUE THREAD

**Issue by Xuefeng-Zhu** [alefragnani/vscode-project-manager#130]
It will be very helpful to have the support to automatically run specific task when switching projects

**Comment by alefragnani** [comment]
Hi @Xuefeng-Zhu ,

Do you need that tasks to be run when you _will switch to a project_ or when you _have switched to a project_?

**Comment by Xuefeng-Zhu** [comment]
@alefragnani Thank you for asking. It will be great if it is available for both.

**Comment by alefragnani** [comment]
Did you try [Auto Run Command extension](https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command)? It may help you when you _have switched to a Project_.

**Comment by Xuefeng-Zhu** [comment]
@alefragnani Thank you for suggestion. Yeah. I checked that plugin, but I feel that it may not work perfectly for the workflow. Ideally, when we switch into a new project, there can be a task to setup dev environment, and when we switch out the project, there can be a task to tear down dev environment.

**Comment by alefragnani** [comment]
I'll think about it 👍 . 

I wondering that maybe it would be better to have a _new extension_ to handle this, instead of _increasing_ this one. Specially because the extension don't know if the project that is being opened, was opened using the command, or if you just opened the folder using built in `File / Open Folder` or `File / Open Recent` commands.

Why that extension didn't work for you?

**Comment by alefragnani** [comment]
Hi @Xuefeng-Zhu ,

Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

Have you found (since you reported this issue) any additional extension that does what you were expecting? Do you still think this issue is necessary?

Thank you

**Comment by Xuefeng-Zhu** [comment]
@alefragnani Thank you for checking. Yes, I think this automation can be helpful

**Comment by alefragnani** [comment]
Hi @Xuefeng-Zhu . 

The idea itself is interesting, but I'm still thinking its _out of scope_ for Project Manager extension. To me, it should be a separate extension, sorry. In fact, I've found a few extensions that do _something like_ what you asked for. In any case, If I find an extension that do what you need, I let you know.

I invite you to participate on my [Patreon page](https://www.patreon.com/alefragnani). Maybe we could chat there about a new extension.

Thank you
