### ISSUE TITLE
Cross-platform baseFolders options

### ISSUE THREAD

**Issue by vkbansal** [alefragnani/vscode-project-manager#131]
First of all thanks for the amazing plugin.

I have a feature request.

As I work on on both MacOS and Windows and use [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) plugin to keep my settings in sync, it would be nice to have an option in project manager for platform specific `baseFolders`.

Something like `projectManager.git.baseFolders.windows` for Windows
and `projectManager.git.baseFolders.macos` for MacOS. This can be extended for linux too.

Integrated terminal settings are already present in similar manner.

**Comment by alefragnani** [comment]
Thanks @vkbansal 👍 .

Integrated Terminal settings aren't exactly _cross-platform_. It's just a setting to you to choose the proper `Shell` for specific platform. I think you are asking something like https://github.com/Microsoft/vscode/issues/17619..

Do you need _different settings_ for each platform because you have your projects in _different folders_? I mean, something like `C:\MyGitProjects\` in Windows and `~/projects/` in MacOS? If _yes_, the problem is not related to the _platform_ itself, but the _machine_ that you use.  

Please, fill more info so I could understand better your needs.

Hope this helps.

**Comment by vkbansal** [comment]
Yes I have `E:/Projects` on Windows and `~/Projects` on MacOS.
How do I specify this in settings?

if I do
```
[
  'E:/Projects',
  '~/Projects'
]
```
will this work?

**Comment by vkbansal** [comment]
My bad this works correctly. I changed the settings to
```
[
 "'E:\\Projects",
  "~/Projects"
]
```
and it works.

Thanks.

**Comment by alefragnani** [comment]
That's great! 🎉 

You can have as many folders as you want, even if they don't exist in all computers. Doing so, the _invalid folders_ will be ignored for that specific computer, but will work for the valid computers.
