### ISSUE TITLE
Open in new window for keyboard shortcut

### ISSUE THREAD

**Issue by aramk** [alefragnani/vscode-project-manager#132]
I can see ` "projectManager.openInNewWindowWhenClickingInStatusBar": true` as an option, but it would be good to have this behaviour for the keyboard shortcut as well.

**Comment by alefragnani** [comment]
Hi @aramk ,

There extension has two commands to list/open projects. The first one is `List Projects to Open`, which comes with a default keyboard shortcut (`Shift + Alt + P`). The second `List Projects to Open in New Window`, has no default keyboard shortcut, so all you have to do is to define your own.

The User Setting that you are referring to only defines how the click in the status bar should work, because there is no way to define _alternate_ behavior for the click.

Hope this helps.

**Comment by aramk** [comment]
Hi @alefragnani, so there's no way to open a new project in a new window if it isn't already opened or switch to it if has? My issue is that the keyboard shortcut switches the project in the current window by default.

**Comment by aramk** [comment]
Ah, never mind I see what you mean, I just added that to replace the existing shortcut. Thanks!

```
  {
    "key": "alt+cmd+p",
    "command": "projectManager.listProjectsNewWindow"
  }
````

**Comment by alefragnani** [comment]
Yes, that's it 👍 
Hope you like it..
