### ISSUE TITLE
Support `Any Folder` as Project

### ISSUE THREAD

**Issue by simonRiep** [alefragnani/vscode-project-manager#137]
Hi there,

it seems I´m making some terrible mistakes and need some help/ guidance/ clarification!

First of all it might seem stupid but I needed nearly 2 hours until I found out how I was able to modify my settings e.g.  "projectManager.sortList": "Name" 
because it´s cleary not a valid JSON String to paste into my "projects.json" 
so I searched.. and finally after I nearly giving up I found (in Git Project Manager) the hint to: "File -> Preferences -> User Settings"
 (even after that I needed another 15 Minutes until I found out it's not "User Settings" but "Settings") maybe you can add this somehow!

But more important for me, i added:
{
    "projectManager.git.baseFolders": [
        "C:\\dev\\svn-git\\haxe\\customer",
        "C:\\dev\\svn-git\\haxe\\customer\\apps"
    ]
}

the git folder is: "C:\dev\svn-git\haxe\customer"

customers contains ~60 folders 
apps another ~50

I thougt I get now all 110 folders as Project but it keeps telling me "There are no entries to pick from"

When I add "C:\\dev\\svn-git\\haxe" I get 3 Git-Folders and it seems ok, but it´s not exactly what I´m looking for.
So I´m looking more for an option to get my folders as Projects is this possible?

**Comment by alefragnani** [comment]
Hi @simonRiep ,

You don't have to add both folders in your settings, because `C:\dev\svn-git\haxe\customer\apps` is a `C:\dev\svn-git\haxe\customer` subfolder, and since the extension looks for Git repositories recursively, it will be used as well. With your settings, it would just have _duplicates_, which will be ignored.

To determine if the folder is a Git project it uses two rules:

* it has a `.git` folder with a `config` file inside _(normal git repo)_
* it has a `.git` file _(git worktree)_

Do you have this scenarios?

About the `README` issue, I'm avoiding to add _how to setup_ because I don't want to be forced to update my instructions if VS Code changes how it works. I used the same model from other extensions, simplifying the instructions displaying the specific settings and available values. I think that VS Code itself should have better instructions on _how to setup_.

Hope this helps.

**Comment by simonRiep** [comment]
Hi @alefragnani,

- C:\dev\svn-git\haxe\customer
has a .git-Folder + 60 Project-folders (without any further .git-folders) so they are not a real git-Project?

So maybe I´m more in need for a solution that picks all my folders as projects, and leave the .git-part out of it?

So for me a nice feature would be if I can add something like this to my project.json:
[
	{
		"name": "main-pj-folder",
		"rootPath": "c:\\dev\\svn-git\\haxe\\customer\\*",
		"paths": [],
		"group": ""
	}
]

and I get every folder in c:\\dev\\svn-git\\haxe\\customer\\ as a project selectable.

**Comment by alefragnani** [comment]
Hi @simonRiep ,

That's right. Each folder/project needs to be a _Git repository_, to be recognized as a project. The same happens for VSCode projects (which checks for a `.vscode` subfolder) and SVN repositories (which checks for a `.svn\pristine` subfolder).

I'll add your idea as an enhancement for future releases 👍 . The only _limitation_ that I see in this approach is that the `maxDepthRecursion` setting should be limited to `1`, because otherwise, it should create too much _invalid_ projects (subfolders which are not real projects).

In the meantime, I guess your only solution is to add this projects in you `projects.json` file individually 😢 . It's not too painful, if you use _VSCode multi edit_ feature, but still, a _manual_ process.

Hope this helps

**Comment by simonRiep** [comment]
That´s ok for a future release, I can wait for it! Thanks for your fast help so far :)!

**Comment by alefragnani** [comment]
Just released on version 9.0. 

Simply use `projectManager.any.baseFolders`, `projectManager.any.ignoredFolders` and `projectManager.any.maxDepthRecursion` like you do for Git repositories.

I didn't update the `README.md` because it works just like the other auto-detected projects, and I still want to add some other features on this, like _Regex_ for naming/ignore.
