### ISSUE TITLE
Path does not exist

### ISSUE THREAD

**Issue by sldobri** [alefragnani/vscode-project-manager#141]
The path '/$home/Code/pousada_do_tucunare' does not seem to exist anymore on disk.
when select Favorites in sidebar

**Comment by richarddavenport** [comment]
Yeah, I'm getting this also. 
![project-manager](https://user-images.githubusercontent.com/3596012/30219570-0b6ca5a6-9482-11e7-8ef4-cb9f9715d195.gif)

**Comment by alefragnani** [comment]
Thanks for reporting. 

I will fix it ASAP 👍

**Comment by richarddavenport** [comment]
@alefragnani I think I have a fix. Do you mind if I submit a PR? And you can let me know if I did it right or not?

**Comment by alefragnani** [comment]
@richarddavenport , Thanks for help, but it won't be needed 👍 
I just have already fixed, but just can't publish the update right now because I'm not in my personal computer. I should release the update until the end of the day.

This was the fix: https://github.com/alefragnani/vscode-project-manager/commit/4a4997960d9f2e6511d2ecafe62e245441a4089c. Have you found this too?

**Comment by richarddavenport** [comment]
Nope, but I like that way better! Closing my PR. Thanks!
