### ISSUE TITLE
Make Treeview optional?

### ISSUE THREAD

**Issue by ls-guillaume-lambert** [alefragnani/vscode-project-manager#143]
Would that be an easy feature to add? Keep up the good work by the way!

**Comment by alefragnani** [comment]
Hi @ls-guillaume-lambert ,

First of all, thanks 👍 

I didn't know it was possible when I added the feature. That's why I didn't add a `setting` for that. But looking deeper now, I found a way to do that, so yes, it would be easy to add 😄.  

Unfortunately, I can't focus on this right now (other priorities), so in the meantime, you could _Hide it_ using the contexto menu in the explorer panel.

Hope this helps.

**Comment by ls-guillaume-lambert** [comment]
Will hide it with the context menu, no rush, thanks for quick reply!

**Comment by alexchantastic** [comment]
Just for those who are looking, you can collapse or hide the Projects Tree view.

To hide it, right click the "Projects" heading a select "Hide from Side Bar".

If you need to bring it back, you can right click the "Explorer" heading at the very top and select "Projects".

I believe that these settings are per root folder.
