### ISSUE TITLE
Options to show opened projects

### ISSUE THREAD

**Issue by stfoo** [alefragnani/vscode-project-manager#145]
Hello!

It seems that already opened projects are hidden from projects list. Is there a way to show all project there.

I am migrating from sublime where I was using ProjectManager. I've got used to using it as a project switcher even between opened projects. It is not rare when I opened project sometime in the past and forgot about it. Exclusion of opened projects forces me to always keep in mind what is opened and what is not which is impossible.

If there is no such option and you don't mind, I can implement it with some directions from you.

**Comment by alefragnani** [comment]
Hi @stfoo ,

That's right, it's the expected behavior. But I understand your point and sure, it could be added a `setting` to change the behavior.

The current project is removed using a single function `removeRootPath`. Updating this function to _check_ for a setting (`removeCurrentProjectFromList`) before effectively removing the `rootPath` should be enough. 

Feel free to send a PR 👍 .
