### ISSUE TITLE
Support “Localization” for both Commands and Messages

### ISSUE THREAD

**Issue by advokatb** [alefragnani/vscode-project-manager#147]
Hi. Is it possible to translate your extension? 
If no can you add this feature? I'd like to use it in my native langeuage.
Thanks.

**Comment by alefragnani** [comment]
Hi @advokatb ,

I don't know if is already available for extensions, but I will take a look. 

Thanks for your suggestion 👍

**Comment by ilyadanilov** [comment]
Hello, is there a way to disable localization? I really don't like it and don't need either.

**Comment by alefragnani** [comment]
Hi @ilyadanilov ,

What do you mean? The extension's localization depends on VS Code's localization. It's not something that the extension _forces/overrides_ in your installation. 

The extension will not be presented in other language, unless you changed VS Code to be presented in that language. The extension will _follow_ VS Code language.

**Comment by ilyadanilov** [comment]
For some reason it doesn't. I'm using english version of VS Code, but your extension use russian.

**Comment by alefragnani** [comment]
I'm not sure either, but I found [this VS Code issue](https://github.com/Microsoft/vscode/issues/62623) which I think to be the same. 

At [this comment](https://github.com/Microsoft/vscode/issues/62623#issuecomment-467347288), a VS Code team member appears to found the reason, which should be fixed for March release. But I'm wondering if this issue is happening because the extension has no `nls.en` file (not needed, once the _default_ language is already localized in `package.nls.json` - creating a copy named `nls.en` should be unnecessary). 

Could you make a simple test?

1. Restore the `.ru` file
1. Duplicates the `package.nls.json` file
1. renaming it to `package.nls.en.json` file.

If it works, then VS Code _needs_ the duplicate `.en` file to be used and the user _forces the UI to be English. And that VS Code issue will probably fix it in March.

Thank you

**Comment by ilyadanilov** [comment]
Okay i tried a few things and i couldn't replicate this problem twice on two different pc's. On first i restored ru.json and added new file, nothing changed, everything worked, but when i deleted new file, disabled/re-enabled even deleted and re-installed ext again, this problem didn't appear, everything worked as supposed to. On second pc i encountered the same problem after installing ext, tried same steps, also installed russian language, but in the end only deleting rus file helped. Both pc have same version of VS Code, i'm using settings sync, so there are no difference between apps and settings. Very strange problem

**Comment by alefragnani** [comment]
I’m closing the issue because I don’t see the translation of the **messages** happening, at least not while it uses the i18n sample provided. Simply because it requires access to all source files, and the core submodule remains private.

So, the translation will be limited to **Commands** only, for now, which only requires access to `package.json`
