### ISSUE TITLE
Support multi-root projects

### ISSUE THREAD

**Issue by andig** [alefragnani/vscode-project-manager#159]
The readme already mentions it and VS finally supports it: https://code.visualstudio.com/docs/editor/multi-root-workspaces. Would be great to have this in the project manager.

Refs https://github.com/alefragnani/vscode-project-manager/issues/46

**Comment by alefragnani** [comment]
Hi @andig ,

As mentioned, it already _supports_ 😄 . It will take _the first folder_ from a multi-root project as the _opened project_ and use it while using the extension, just that.

**Comment by andig** [comment]
I may be doing this all wrong, but. I'm coming from Sublime Text. I'd used to the notion of a project= a collection of root folders which are open/ visible in the explorer at the same time.

RIght now this extension doesn't seem to do that (while workspaces actually do now)? Taking the first folder is nice but what I would really need is all of them.

Does that mean I shouldn't be using this extension but rather switch to work spaces?

**Comment by alefragnani** [comment]
The concepts are the same now, as you may notice in my [other comment](https://github.com/alefragnani/vscode-project-manager/issues/151#issuecomment-350739294).

This extension is not to _make workspaces_, but to _switch between projects/folders_, and in the future, _workspaces_. Why it does not work with Workspaces yet? Because there is no API in VS Code for that. 

I updated the extension to support workspaces (multi-root) right at the first Insiders release, and one day prior to release it in Insiders channel, the VS Code team changed how it worked (from User Settings to an external file. So, I decided to wait the oficial release and made the smallest change possible, which is to work with the _first folder_. I didn't want to wast my time again with an API that would change in the near future.

The multi-root support is finally in Stable release, and now I'm just waiting the proper API. Unfortunately, there is no ETA from VS Code team. Until there, I don't see why I would update the extension for multi-root related operations.

I'm sorry to hear that the extension don't fit your needs. I work with it my entire day and it seems to work just well.
