### ISSUE TITLE
saving projects doesn't work, also edit projects does nothing.

### ISSUE THREAD

**Issue by OneOfOne** [alefragnani/vscode-project-manager#16]
Like the title says, using the latest version as of 5 minutes ago on the store and vscode 0.10.10 on Linux 64bit.

**Comment by alefragnani** [comment]
Does it ask you for the project name, when you try to save the project?

If yes, you could try to find the `projects.json` file in your `/Users/yourlogin` folder, that is where I supposed it should be saved, in Linux.

I will try to get a Linux VM to test it. I remember having a Ubuntu available somewhere.

**Comment by OneOfOne** [comment]
It asks for the project name, doesn't show anything after I hit enter to save it.

I just ran `find -iname projects.json` on my $HOME and there was nothing.

**Comment by OneOfOne** [comment]
Taking a quick look at the code, 

```
            let appdata = process.env.APPDATA || (process.platform == 'darwin' ? process.env.HOME + '/Library/Application Support' : '/var/local');
            var projectFile = path.join(appdata, "Code/User/projects.json");
```

`projectFile` is wrong, it should be `vscodeConfigPath + "/projects.json"`, but i'm not sure if there's an actual api to return `vscodeConfigPath`.

**Comment by gil-levy** [comment]
hi,

on linux i changed it to: 
   var appdata = process.env.HOME;
   var projectFile = path.join(appdata, ".config/Code/User/projects.json");

and it works now.

**Comment by alefragnani** [comment]
Hi @OneOfOne ,

I tested in a Ubuntu VM and could reproduce your problem. Instead of `/Users/YourLogin` folder, as I supposed it should use, it tries to save in `/usr/local` (I didn't check the source prior my previous post). I don't use Linux, so I'm sorry for missing the right configs. I just used a _home folder template_ that I found in StackOverflow :disappointed: .

I tested @gil-levy approach and found more references that says it should be `/home/YourUser/.config` the right place. In fact, at least in my Ubuntu installation, it was here that **Code** itself put its temp files, so I suppose it is really the right place.

I pretend to update the extension until the weekend with this fix.

Thanks @gil-levy for pointing the right direction :+1:

**Comment by alioygur** [comment]
+1

**Comment by alefragnani** [comment]
The fix is already working, but I'm having problems while opening the projects. It seems to be a problem with `child_process.exec`, and as soon as I have a solution, I'll publish the update.
Stay tuned :smile:

**Comment by alioygur** [comment]
@alefragnani yes I have too :)

I think this about vscode it self

**Comment by alefragnani** [comment]
Good news... I just tested the latest **Insider** release, using the new **Debian** package and it worked perfectly. Even the `openInNewWindow`. :tada: 

So, I will release this fix right after the new **Code** version is released. 

Thanks for your patience

**Comment by alioygur** [comment]
Alefragnani can you explain the problem.

Thank you.

**Comment by alefragnani** [comment]
Hi @alioygur , 

Would you like to know the _original problem_ reported in this issue, or the _opening projects_ problem, which is fixed in the **Code Insider** release? :smile:

**Comment by alioygur** [comment]
@alefragnani all of them :)

**Comment by alefragnani** [comment]
Hi @gil-levy , 

Which Linux distro are you using? Did you do anything else other than the soft link as described in https://code.visualstudio.com/Docs/editor/setup to work, because on an Ubuntu VM that I have, it has no effect. I can open Code from the shell, but not withing Code (the extension).

Thanks

**Comment by alefragnani** [comment]
Ok @alioygur :smile: 

1. **Original Problem**: I used a _Stack Overflow_ answer to know where is the _home folder_ using Node.js. But the _supposed_ place where wrong, so I search a little bit and @gil-levy pointed me to the right direction. This is already fixed, but then, when testing the _switching_ between projects, I get problem 2 

2.**Opening Projects**: The same problem that I had with Mac OS X, happened with Linux (_whata surprise_). I use

**Comment by alefragnani** [comment]
`
