### ISSUE TITLE
Does not create the projects.json file

### ISSUE THREAD

**Issue by ngryman** [alefragnani/vscode-project-manager#162]
Hey, I've just installed your extension and it seems that the `projects.json` file is not created. When I browse to the default path `/Users/xxx/Library/Application Support/Code/User` I only can see a `projects_cache_git.json` file. Also, executing a `Save Project` command displays me an error message.

The only settings I've customized are as follows:
```json
{
  "projectManager.git.baseFolders": [
    "/Users/xxx/Projects"
  ],
  "projectManager.git.maxDepthRecursion": 1
}
```

I'm running VSCode `1.19.2` and High Sierra `10.13.2`.

**Comment by alefragnani** [comment]
Hi @ngryman ,

If you use `projectManager.git.baseFolders` (or `svn` / `vscode`), the projects are _automatically detected_ an so, no `projects.json` file is created, only the _caches_. There is no need to **Save a Project** (listed from your `git` config).

You should use the `Save Project` command to store non-git/svn/vscode projects, which are not _automatically detected_. 

But even in this scenario, the command _must work_. Could you please paste the error message, and also the `Console` output from `Help / Toggle Developer Tools`?

Hope this helps

**Comment by ngryman** [comment]
Hey @alefragnani,

Thanks for the explanaton, gotcha. I'm trying to use your extension with this [Alfred workflow](https://github.com/konstantinbueschel/alfred-vs-code). And it seems that he relies on the `projects.json` file to display all the available projects.

Do you think it would be possible to always create this `projects.json` so 3rd party tools leveraging your extension could always rely on that file? If not, what should I propose to the developer of this workflow to make it work with versioned projects?

`Save Project` actually works now 😮 I guess it happened to me just after installing the extension 🤷‍♂️ 

Thanks!

**Comment by alefragnani** [comment]
Hi @ngryman ,

That's cool! I didn't know about this extension. That's really fun to see the projects available in Alfred 😄 

The `projects.json` is really not necessary, because you may choose to use only _auto-detected_ projects (git, svn, vscode). And even if I add an empty file, the autodetected projects will not appear.

I think the correct approach is to suggest the **Alfred Workflow** extension to support auto-detected projects, merging the results with the projects available in `projects.json` (if any). 

Hope this helps.

**Comment by ngryman** [comment]
Hey @alefragnani, thanks for the suggestion! I've contacted the author and proposed your change.
