### ISSUE TITLE
_conflict files are being created

### ISSUE THREAD

**Issue by userlip** [alefragnani/vscode-project-manager#173]
Hey!

I opened an issue over at the VSCode repo because there was something unusual stuff happening read here:
https://github.com/Microsoft/vscode/issues/45354

And I think that this extension is the issue, as the problem stopped as soon as I disabled this extension

As said in the other issue thread: I thought it was due to git (git conflict) but I disabled git in VSCode so could this extension re-enable git and cause this problem?

Thanks for your help!

**Comment by alefragnani** [comment]
Hi @userlip ,

That's weird, because the extension doesn't touch any of your files. The only files that it saves/loads are stored in your _user data_, with VSCode data files itself.

Did you uninstalled/disabled _only this extension_ and the problem disappeared, or did you disabled _all extensions_ (`code --disable-extensions`), as advised by VSCode team?

Are your projects stored in some kind of _cloud/synced location_? I mean, its name `yourfile_conflict-yyyymmdd-hhmmss.ext` seems like a cloud/sync solution for conflict files. For instance, Dropbox has a `yourfile (Poeple's conflicted copy yyyy-mm-dd).ext`. It this is your case (using a _cloud/synced location_) I think the problem may be in another extension that _manipulates_ your files.

Hope this helps

**Comment by userlip** [comment]
Hey @alefragnani 
You are right it's Owncloud (NextCloud).
Although I didnt have the issue when disabling this extension I am still sorry to have consumed your time!

Thanks for the hint though, never would have guessed, that it could be nextcloud as I am working with it since a long time now.

Keep it up!
