### ISSUE TITLE
Delete Project does not show in list.

### ISSUE THREAD

**Issue by frackham** [alefragnani/vscode-project-manager#182]
Not sure if this is just me or related to issue fixed in PR #100 ?

![image](https://user-images.githubusercontent.com/2105204/39427231-eb6ea856-4c7a-11e8-948b-01fb9d405f54.png)

**Comment by alefragnani** [comment]
Hi @frackham ,

There is no `Delete Project` command available in Command Palette. 

What #100 accomplishes is a delete _Button_, which is presented when you try to select a Project in the list, but it does not exist anymore in you filesystem (you saved a Project but then renamed/deleted its folder). 

To delete a Project, you must open your call `Project Manager: Edit Projects` and remove its entry from the `projects.json` file.

Otherwise, if you are using the project autodetection (for `Git` or `SVN` for instance), you just have to call `Project Manager: Refresh Projects`. Doing so, your the deleted/renamed projects from your filesystem will reflect in the list.

Hope this helps.

**Comment by frackham** [comment]
Thanks, `Project Manager: Edit Projects` was what I needed. 

Refresh wasn't clearing projects where the path was no longer valid (WAI?).

**Comment by alefragnani** [comment]
That's great to hear 🎉 

About the `Refresh` command not working, it is because it does not reflect on your _saved project_, but only on those _auto-detected_. 

The idea behind this command is to update your auto-detected projects when you delete/rename/add projects, because I create a _cache_ to speed-up the listing. But, for your _saved projects_, it will show an icon/text saying _Path does not exist_. 

Hope this helps
