### ISSUE TITLE
Open multiple projects not working

### ISSUE THREAD

**Issue by asotog** [alefragnani/vscode-project-manager#20]
is there any way to open multiple projects at the same time ? i mean multiple windows for different projects ? i tried but opening nothing

**Comment by alefragnani** [comment]
Hi @asotog ,

Using the default setting for `"projectManager.openInNewWindow"` (`true`), it will open a new **Code** instance every time you select a project, otherwise, it will change the current instance root folder.

What OS are you using? By today, there is an issue with Linux (#16). And for Mac, you have to install the `Code Shell Command` (_see readme.md_).

Hope this helps.

**Comment by asotog** [comment]
hi yeah using mac here will try that thanks

**Comment by alefragnani** [comment]
Good to see it worked :+1: 

I pretend to update the `README.MD` to let this info easier to find, and also to update the extension itself, to detected empty setting that _could_ be vital to the extension.

Thanks
