### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by edgaraljuri83** [alefragnani/vscode-project-manager#206]
when I install the Project Manager extension, download the artifacts, but do not install it, the process is frozen, I have vscode 1.25 Portable Mode 

Steps to Reproduce:

    Go the the Extensions side bar CTRL + SHFT + X
    Search for an extension, for example Bimbo Theme
    Click the button Install

Nothing happens, the text Install changes to Installing and then gets back to Install without anything installed or any notification of what happened.

![2018-08-02 07_52_53-extension_ project manager - automation-scripts - visual studio code administra](https://user-images.githubusercontent.com/36165949/43584842-269b9086-9629-11e8-9676-3a1548d3e496.png)
![2018-08-02 07_55_40-out](https://user-images.githubusercontent.com/36165949/43584970-827aedac-9629-11e8-9e69-3327c3bf7251.png)
![2018-08-02 08_10_39-extension_ project manager - automation-scripts - visual studio code administra](https://user-images.githubusercontent.com/36165949/43585934-f06aa422-962b-11e8-8e5b-1c60321daab1.png)
![2018-08-02 08_12_08-](https://user-images.githubusercontent.com/36165949/43585938-f30cff54-962b-11e8-93b5-5a178777b1cc.png)

**Comment by alefragnani** [comment]
Hi @edgaraljuri83 ,

The installation process is entirely controlled by VS Code, and not by the extension. Sometimes you just have to _try again_ and the installation finally worked. I don't know if this is your case.

Also, you reported that you are using the **Portable Version**, which I didn't use yet. I don't know if this would be the reason, but I guess not, since #201 was filled, which means that it was able to install the extension.

I would suggest you to try again. Maybe there was just a temporary connection issue.

Hope this helps
