### ISSUE TITLE
"undo" functionality impaired

### ISSUE THREAD

**Issue by jeffreysbrother** [alefragnani/vscode-project-manager#209]
Steps to reproduce:

1. modify a file in some repository x, and save.
2. use Project Manager to navigate to some different repository y.
3. use Project Manager to navigate to original repository x. Attempts to undo previous change will not work. (cmd+z AND Edit>Undo will not work)

Undo functionality works as expected only if I refrain from using Project Manager. For example, if I toggle between multiple VS Code windows (corresponding to different repos), Undo works as expected.

VS Code version 1.26.1

Plugins used:
- Bookmarks 9.0.3
- DotENV 1.0.1
- Easy icon theme 0.3.1
- EditorConfig for VS Code 0.12.4
- Project Manager 8.0.0
- Subtle Match Brackets 2.1.1

**Comment by alefragnani** [comment]
Hi @jeffreysbrother ,

I made some tests, and it appears that you have two different scenarios, and that's why you have two different results.

In the end, toggling between multiple windows, or switching between different projects, works the same way, using Project Manager or VS Code alone. 

Do these tests:

1. Toggle between windows using Project Manager. For that, you could open the second window using `List Project to Open in New Window` command. At this point, you have two windows opened by Project manager. Now, you can keep using `List Project to Open` to _toggle_ between windows. Try to use `Undo`, and you will see that it works just like you described for VS Code alone.

2. Use `Open Recent` to replace the current window the previous project that was open. Try to use `Undo` command, and you will see that nothing happens.

The point is, VS Code does not store the `Undo` stack when you _reopen_ a project/folder, but only if it remains opened, which is the case when you _toggle windows_ .

Hope this helps.

**Comment by jeffreysbrother** [comment]
Thanks so much for the explanation. I've tested and confirmed that your solution (using "list projects to open in new window") ensures that the undo stack is retained.
