### ISSUE TITLE
Add Searchbar to filter projects in Activity Bar

### ISSUE THREAD

**Issue by Ritorna** [alefragnani/vscode-project-manager#213]
In my opinion a few great additions to this extension would be:

### provide a searchbar to filter projects

When having many projects saved it would be great to can search for them.

> Currently VS Code does not support this yet, so need to be patient for this feature request: [Vs Code Issue 20224](https://github.com/Microsoft/vscode/issues/20224)

### make use of the groups

For easier visual structuring it'd be great to build up a whole tree based on the groups. For example:

A projects configuration like this:

```json
[
  {
    "name": "project1",
    "group": "group1"
  },
  {
    "name": "project2",
    "group": "group1"
  }
    {
    "name": "project5",
    "group": "group2"
  }
]
```
could end up being rendered like this:

![image](https://user-images.githubusercontent.com/10747768/44858375-231aac80-ac72-11e8-973a-c0a24cebbf58.png)

**Comment by alefragnani** [comment]
Hi @Ritorna ,

For the first suggestion (search bar to filter projects) it was already on my radar (https://github.com/Microsoft/vscode/issues/50062), but not yet _reported_ on any of my extensions. 

About the second suggestion, It's the simiar to #50 which still waits for another VS Code API. Once the API is released, I could update the extension both in Command Palette and Activity Bar.

I'll update the description to reflect only the first suggestion, since the second one is already reported.

Thanks for reporting

**Comment by alefragnani** [comment]
I'm closing this issue because the referenced issue from VS Code has been closed. The VS Code team will not supported the requested API.

**Comment by alefragnani** [comment]
Reopening because another API Request issue has been opened https://github.com/microsoft/vscode/issues/70646

**Comment by alefragnani** [comment]
It's been around 3 years a new API has been requested to the VS Code team, and up until now, no updates or ETA.

I'm changing the idea of this issue, and instead of a filter box on each Panel, I'll add a filter button, which will open the same `List Project to Open` command, but already filtered by the _kind of project_ from the clicked panel. So the user will filter the projects by that kind. The negative point of this approach, you will not have the option to open the project _`on New Window`_. But it's better than no filter option at all.

Stay tuned

**Comment by Ritorna** [comment]
Sounds like an acceptable compromise to me 👍🏻

**Comment by el1f** [comment]
+1 for this approach! Looking forward to trying it out for myself!

**Comment by leonardopn** [comment]
+1
