### ISSUE TITLE
After switching project git gutter decorator stops working

### ISSUE THREAD

**Issue by steverandy** [alefragnani/vscode-project-manager#215]
Steps to reproduce:

1. Open a project normally.
2. Switch to a different project with project manager.
3. Make changes in the new project.

Expected:
Gutter should show git decorators (add/delete/modified).

Actually:
Git decorators in gutter stops working and does not show anything.

Code version: 1.27.1
Project Manager version: 8.0.0

**Comment by alefragnani** [comment]
Hi @steverandy ,

That's weird, because the Project Manager extension does not affect the installed extensions while switching to different projects. It only _open/switch_ a folder, as would happen if you use `File / Open Folder` or `Open Recent` commands.

In the recent VS Code releases, I have noted that the Git extension itself is a bit _lazy_, taking longer than previous versions to load/show up. At first, I was thinking it would be something with my home computer, but it is happening on my work computer too. Maybe this is your case.

Can you confirm that this _only happens_ when using the Project Manager extension, and not with `File / Open Folder` or `Open Recent` commands?

Hope this helps

**Comment by steverandy** [comment]
I could not reproduce the issue on Code v1.27.2.
Thanks.

**Comment by darrinholst** [comment]
this ended up being a casing issue for me as described [here](https://github.com/Microsoft/vscode/issues/60010#issuecomment-510441083)
