### ISSUE TITLE
Support for window.nativeTabs

### ISSUE THREAD

**Issue by meandmax** [alefragnani/vscode-project-manager#216]
For some reason `window.nativeTabs` stopped working and now I need to open projects from command line again instead of leveraging this awesome plugin. Could u make it work again, or point me to the place where I need to adjust the plugin.

**Comment by alefragnani** [comment]
Hi @meandmax ,

I didn't do anything to make the extension support `window.nativeTabs`, because I just use the VSCode API to open folders/projects/workspaces. 

What happens if you try to use the native `Open Recent` command, using `Command + Return` option to open the folder _in new Window_. Does it work, or does it also fails?

Hope this helps

**Comment by alefragnani** [comment]
Hi @meandmax , any news about it?

**Comment by alefragnani** [comment]
I'm closing this issue because received no answer from my latest _ping_ almost two months ago.
Feel free to reopen if you have any new news.
