### ISSUE TITLE
Displaying the project within its organization

### ISSUE THREAD

**Issue by oshliaer** [alefragnani/vscode-project-manager#217]
FR

Is it possible to save projects with its organization (if it exists) ? For an example

`my project` to `oshliaer/my project`
`my project` to `my organization/my project`

At now it's not a clean to see what project is there.

**Comment by alefragnani** [comment]
Hi @oshliaer ,

This has already been reported in #50 , but it hasn't been released yet because of missing APIs in VS Code, to accomplish the design that I was thinking. But, some new APIs has been released recently, and I'm planning to take a look and see if it _could_ be used to make what I have in mind. 

Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. But this "re-focus" will be based on community feedback/support, and I still don't know where this idea will be. I suggest you to follow #50 for news.

Hope this helps
