### ISSUE TITLE
Error: No view is registered with id: <VCS-ALIAS>

### ISSUE THREAD

**Issue by alxpsr** [alefragnani/vscode-project-manager#219]
I got errors after installing extension: 
`No view is registered with id: projectsExplorerGit`
`No view is registered with id: projectsExplorerMercurial`
`No view is registered with id: projectsExplorerSVN`

Screenshot: http://joxi.ru/Grq1eQMFQ1Zp1r

Also, project-manager icon does not show in vscode-panel
What i'm doing wrong?

**Comment by alefragnani** [comment]
Hi @alxpsr ,

You are not doing anything wrong, don't worry 👍 . 

You just may be  experiencing the same issue as #198, which unfortunately I didn't find the reason nor a solution. That's really weird, because there is nothing _special_ about the views 😢 .

In the recent weeks has been very difficult to find free time to work on the extensions, so I couldn't look deeper in this issue. Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. But this "re-focus" will be based on community feedback/support, and I still don't know where the issue will be. I suggest you to follow #198 for news.

Hope this helps.
