### ISSUE TITLE
projects.json is not created in a code-insiders only environment

### ISSUE THREAD

**Issue by satokaz** [alefragnani/vscode-project-manager#22]
`projects.json` is dependent on the PATH of the vscode stable.

vscode stable: 
`$HOME/Library/Application Support/Code/User/`

vscode-insiders
`$HOME/Library/Application Support/Code - Insiders/`

`projectFile` is hardcoded to "**Code**/User/projects.json".
`"$HOME/Library/Application Support/Code/"` directory is not create to be to launch the vscode-stable.
need to support to insiders build.

https://github.com/alefragnani/vscode-project-manager/blob/master/extension.ts#L18-L19

It does not come to mind a little good idea...

Mac OS X 10.11.3

**Comment by satokaz** [comment]
Just idea.
It is a way to switch to add a projectManager.useInsiders setting item.

`	"projectManager.useInsiders": true`

Windows and Linux is also not possible to confirm whether the same behavior. But I believe that's the same.


```diff
diff --git a/extension.ts b/extension.ts
index 38faa42..04d06d1 100644
--- a/extension.ts
+++ b/extension.ts
@@ -12,17 +12,23 @@ export function activate() {
     // Use the console to output diagnostic information (console.log) and errors (console.error)
     // This line of code will only be executed once when your extension is activated
     console.log('Congratulations, your extension "project-manager" is now active!');
-
-    //
-    let projectFile: string;
-    let appdata = process.env.APPDATA || (process.platform == 'darwin' ? process.env.HOME + '/Library/Application Support' : '/var/local');
-    projectFile = path.join(appdata, "Code/User/projects.json");
-
-    // in linux, it may not work with /var/local, then try to use /home/myuser/.config
-    if ((process.platform == 'linux') && (!fs.existsSync(projectFile))) {
-        let os = require('os');
-        projectFile = path.join(os.homedir(), '.config/Code/User/projects.json');
-    }
+
+    //
+    let projectFile: string;
+    let appdata = process.env.APPDATA || (process.platform == 'darwin' ? process.env.HOME + '/Library/Application Support' : '/var/local');
+    // ProjectFil path
+    let useInsiders = vscode.workspace.getConfiguration('projectManager').get('useInsiders', false);
+    if (useInsiders == false) {
+        projectFile = path.join(appdata, "Code/User/projects.json");
+    } else {
+        projectFile = path.join(appdata, "Code - Insiders/User/projects.json");
+    }
+
+    // in linux, it may not work with /var/local, then try to use /home/myuser/.config
+    if ((process.platform == 'linux') && (!fs.existsSync(projectFile))) {
+        let os = require('os');
+        projectFile = path.join(os.homedir(), '.config/Code/User/projects.json');
+    }

     // Save the Projects
     vscode.commands.registerCommand('projectManager.saveProject', () => {
diff --git a/package.json b/package.json
index 4ec044a..e65caa0 100644
--- a/package.json
+++ b/package.json
@@ -69,6 +69,11 @@
                                        "type": "boolean",
                                        "default": false,
                                        "description": "Should use the alternative approach in Mac OS X?"
+                               },
+                               "projectManager.useInsiders": {
+                                       "type": "boolean",
+                                       "default": false,
+                                       "description": "Should use the alternative approach in Code - Insiders?"
                                }
                        }
                },
```

**Comment by alefragnani** [comment]
Hi @satokaz 

I noted that last week when running on a machine that only had the Insider version installed. I will try to find a way to detect the release kind, otherwise I could use your idea :+1: 

Thanks

**Comment by bbak** [comment]
Same here on Win 10 (of course). Changing `extension.js:16` to `projectFile = path.join(appdata, "Code - Insiders/User/projects.json");` resolves the issue.

**Comment by alefragnani** [comment]
Yep, it has the same issue no matter the platform.

I created this issue https://github.com/Microsoft/vscode/issues/5297 and will be using the proposed solution, until a native API is available.

I hope an update to be available in a couple of days

**Comment by texastoland** [comment]
Tracked in Microsoft/vscode#2741.

**Comment by kumarharsh** [comment]
@alefragnani until the proposed fix in vscode lands, can the solution proposed here be implemented? It's really irritating that I can't use PM until vscode team implements that API (which I think is still some way off in the future).

Right now, I'm manually changing the extension.js file to fix it, but after every update it breaks. I'd also be happy to re-submit a PR if it's ok with you.

**Comment by texastoland** [comment]
All I had to do was create the non Insiders directory to work around.

**Comment by alefragnani** [comment]
@kumarharsh @texastoland 

I was expecting the new API to be released back in April, but since then, they evolved the idea and postponed the final release. I agree with you that's irritating to be forced to patch the extension, or create the _non Insiders_ folder 👍 . 

But don't worry. I will release a workaround until the weekend and fix this.

The idea is to create a **new user setting** called `projectManager.projectsLocation` to define the _subfolder_ where the `projects.json` file is located. So for those that patched the extension to use `Code - Insiders`, or those that want to keep _different projects_ for Stable and Insiders version, just define `Code - Insiders/User/` in the Insiders install and it will work. And for those that want to _share the projects_ between Stable and Insiders version, just use `Code/User/` and it will also work.

Maybe, just maybe 😄 , also use the `$HOME` variable idea and let you to decide _the entire path_ where the `projects.json` file is located, so you could easily _sync_. I will see how it goes.

Hope this finally solves this issue 👍

**Comment by alefragnani** [comment]
Better yet,

The **new user setting** will be the **full folder path** (not _subfolder) where `projects.json` will be stored. So, you may define _any folder_.

If you don't config anything, it will _detect which channel you are_ and use the appropriate folder.

So, for those of you that patched the extension, you don't have to do anything. And those of you that created the `\Code\User\` folder, just define the user setting.

Stay tunned

**Comment by texastoland** [comment]
Why not just create the missing folder until the API arrives? Sharing configuration between instances would only work for your extension whereas symlinking gets them all. I'd really prefer a hardcoded `- Insiders` path since that's the only use case wanted until API lands.

**Comment by kumarharsh** [comment]
@texastoland not everyone is going to create the missing folders - especially when it serves no other purpose apart from being a hack to get this plugin to work. Hacks are prone to breaking, and only people who have actually taken time to read into the source-code of this plugin would even know that. Most people might thing that "eh, it doesn't work, its broken" and never use the plugin again.

**Comment by texastoland** [comment]
I meant why doesn't the extension. The proposed setting just complicates configuration for the only conceivable use case. Or it could alternatively hard code the path given a boolean flag.

**Comment by texastoland** [comment]
I misread his proposal.

**Comment by alefragnani** [comment]
That's right.

There will be no need to _manually_ create folders. Each VSCode channel (Stable and Insider) has its own `$APPDATA` folder, and right from the beginning, the extension _should know that_ and store the `projects.json` in the appropriate folder. But since I had both installed right from the beginning, I didn't note this. My bad.

So, with the new release, each VSCode channel will have it's own `projects.json` file, so, if you only have the Insider version, your `projects.json` file will be in `$APPDATA\Code - Insiders\Code`.

And with the new setting, if you want to share the projects between Stable and Insider versions, just choose the path.

Is that ok?

**Comment by texastoland** [comment]
Sounds good. The misunderstanding wasn't about creating a folder but it <q>just working</q> without configuration. Sounds intuitive!

**Comment by alefragnani** [comment]
Great :+1:

**Comment by texastoland** [comment]
WFM 👏

**Comment by satokaz** [comment]
@alefragnani 

Thanks! 🎉

**Comment by kumarharsh** [comment]
Sweet!

**Comment by alefragnani** [comment]
Great! Glad to see it worked for all of you :+1: 

Thanks for your patience
