### ISSUE TITLE
Drag folder in to project?

### ISSUE THREAD

**Issue by thetwopct** [alefragnani/vscode-project-manager#244]
Is it possible to drag a folder from Finder in to Project Manager and have it add that as a project?

**Comment by alefragnani** [comment]
Hi @thetwopct ,

Unfortunately there is no API available for that yet, so no, it's not possible to use _drag and drop_ there.

I'll let your issue open, and create a new issue in VS Code repository, asking for that.

Hope this helps

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/65303#event-2033593249 / https://github.com/Microsoft/vscode/issues/32592

**Comment by thetwopct** [comment]
FYI to anyone else, I ended up solving my need the opposite way - there is a Finder extension to open in Code 👍 

https://github.com/sozercan/OpenInCode

**Comment by alefragnani** [comment]
I'm closing this issue because the VS Code issue that it depends on has no update from VS Code team members for more than an year, and based on [this comment](https://github.com/Microsoft/vscode/issues/32592#issuecomment-458747834), it's not even planed.

I've subscribed to the issue, so if/when it is released, I'll be notified, and could reopen/reactive this one
