### ISSUE TITLE
Project Groupings

### ISSUE THREAD

**Issue by mt-webdev** [alefragnani/vscode-project-manager#247]
As a user i would like to be able to group projects in "folder like" groupings for better usability.
This feature will enable maintaining a larger amout of projects.

Thanks in advance.

**Comment by alefragnani** [comment]
Hi @mt-webdev ,

This is indeed a good addition, and has already been reported in #50. But, it is still open because there is no VS Code API available for a _proper grouping of items in the pick list_. I have created an [issue in VS Code repository](https://github.com/Microsoft/vscode/issues/11468), but unfortunately, no ETA 😢 .

It's open for more than 2 years, with no _movement_, so maybe it's time to move on and use another idea. 

Hope this helps

**Comment by OzzyTheGiant** [comment]
The best I could come up with grouping/categorizing projects is by "tagging" them. For example, website projects I name as "WEB: example.com", web/mobile apps I label as "APP: Sample App", and sandboxes or testing environments as "TST: localhost". Hope this helps in any way
