### ISSUE TITLE
feature-request: add save button

### ISSUE THREAD

**Issue by nn-hh** [alefragnani/vscode-project-manager#249]
I think it is difficult for vscode beginners to save from the command palette.
I think that it will be useful if you have either a status bar or a sidebar?

**Comment by alefragnani** [comment]
Hi @nn-hh ,

I understand you point, but I would call the `Command Palette` as the _core / heart_ of VS Code. Everything that you need to do, should be available there. So, I would suggest you to use it. You will se how powerful it is. 

In the latest release (10.3.0) I released #227 , which makes the Side Bar visible by default (even if you didn't save a project yet) and also a `Save your First Project` command, to help you to _get started_. After that, you should use the `Command Palette`, using the commands [described here](
https://github.com/alefragnani/vscode-project-manager#available-commands). Just a tip, when looking for commands _from extensions_, start typing the extension's name, prior the command itself. There is an _unofficial convention_ for extension developers to prepend the command name, with the extension's name.

Hope this helps

**Comment by nn-hh** [comment]
thank you for listening. 
I can not speak English.I think it is hard to understand my story. I'm sorry.

I am using it comfortably. <code>projectManager.git.baseFolders</code> very convenient. Thank you.
But housewives who do coding (css, html only) can not understand at all.
Of course, git etc can not be used.
I teach more than three times for one person...

**Comment by alefragnani** [comment]
No need to be sorry. English is not my _native_ language too, and I understand how difficult can be to use a tool in a foreign language. My point is _this is how VSCode is designed_ so if you want to use it, you may adapt your workflow.

 You could also to [change VSCode language](
https://code.visualstudio.com/docs/getstarted/locales), so instead of English, it would be presented in your native language. There are a lot languages available, and some extensions are already translated. It’s on the roadmap for me #222 (Russian at first).

I’ll keep this issue open for now. Let’s see how many votes it receives, so I could prioritize on future releases.

Hope this helps

**Comment by nn-hh** [comment]
Thank you for your kindness.

I recommend this project manager to many people.
But where is the save button? It is always asked...

It is only programmers like us who understand quickly.
It seems to be difficult for light users...

Thank you for responding.

**Comment by eKoopmans** [comment]
Yeah... I'm a coder and just exploring VS Code, considering making the switch. Project Manager was one of the first extensions I added to try to get the environment feeling comfortable. The Command Palette **is not** obvious - I'm open to adopting it but I didn't even know what to look for.

I recommend at least adding a line to your readme, e.g. under "Save Project":

> You can save the current project in the manager at any time. **Just open the Command Palette (Ctrl-Shift-P), enter `> Project Manager: Save Project`,** then type a name.

The feedback within VS Code isn't helpful either - within the Project Manager sidebar, the only clickable thing at the start is the Edit button, and it says "You should open a folder and use Save Project instead". This was very frustrating because there was no indication of *how* to do this.

I've only now found the "Save your First Project", which was hidden on the "No projects" text - it would be more useful if "Save a project" came up when right-clicking anywhere in the manager window.

**Comment by alefragnani** [comment]
Hi @eKoopmans ,

First of all, thank you for your comments.

I suggest you to replicate this feedback to VS Code team (www.github.com/microsoft/vscode), because as I commented above, the Command Palette is the _core_ and intended to be easy to adopt. If they know how difficult it has been to adopt the concept, they could improve and/or add new solutions.

It's been a while that VS Code team is exploring new UI elements (like the custom Side Bar), but a lot of _usability_ depends on APIs provided by VS Code to extension's developers. For instance, your request to _right-clicking anywhere in the manager window_, is not possible today, because I can't add a context menu item to the panel (manager window), only to elements (nodes). 

About your readme update, I'm open to a PR 😁 . Just don't add the keyboard shortcut, because I don't add those on my readme files anymore.

Hope this helps

**Comment by nn-hh** [comment]
package.json#219
add
```
{
    "command": "projectManager.saveProject",
    "when": "view == projectsExplorerFavorites",
    "group": "navigation"
},
```
I think it's very good.(There is no icon)
@alefragnani  Is this useless?

**Comment by alefragnani** [comment]
Hi @nn-hh ,

No, it's not useless. That's exactly how it works :-). The icon is added in the command itself.

Sorry for taking so long to revisit the issue. I was focused in other projects. This will be in the next update, this weekend.

Hope this helps
