### ISSUE TITLE
No sidebar

### ISSUE THREAD

**Issue by jimpriest** [alefragnani/vscode-project-manager#255]
Windows 10, VSCode 1.31.1, Project Manager 10.3.2

I have no sidebar.  I have sidebars for other extensions ie: Bookmarks, SVN, etc.

I've uninstalled/reinstalled extension to no avail?

**Comment by alefragnani** [comment]
Hi @jimpriest ,

Since release 10.3.0, the Activity Bar icon should be visible by default, even if you don't have any saved, auto-detected projects. 

Unless you already had the extension installed prior this version, and configured in user settings to hide the Treeview (`"projectManager.treeview.visible": false`), it should be visible.

Please, take a look if you have this setting defined, otherwise, take a look at `Toggle Developer Tools / Console`, looking for some error message.

Hope this helps

**Comment by jimpriest** [comment]
Treeview was it!  I removed that and it works!
