### ISSUE TITLE
project list to open selected foreground color uses different theme property

### ISSUE THREAD

**Issue by cyrus86** [alefragnani/vscode-project-manager#259]
the "list projects to open" list's `focusForeground` seems to be using `sideBar.foreground` instead of the supposed `list.focusForeground`. You can test this by customizing the workbench color values in your settings.json:

```json
  "workbench.colorCustomizations": {
    "list.focusBackground": "#FFFFFF",
    "list.focusForeground": "#000000",
    "sideBar.foreground": "#FF0000"
  },
```
this will show red color for the currently focused item in the project list, but should show black color like the currently focused item in the regular command palette.
Not sure this needs to specified on the extensions side or not, but the list's focusForeground should use `list.focusForeground` if I understand this correctly.

**Comment by alefragnani** [comment]
Hi @cyrus86 ,

That's really weird, I agree, but that's something that you should report directly to VS Code, because this is not caused by the extension, but VS Code itself. 

Try opening **Command Palette**, **Go to Symbol**, **Go to File**, or any other list, and you will see the same colors. 

Hope this helps.

**Comment by cyrus86** [comment]
Thanks for the quick response @alefragnani !  

> Try opening **Command Palette**, **Go to Symbol**, **Go to File**, or any other list, and you will see the same colors.

I posted here because for me the view for project-manager is **the only one** showing a different behavior. Please see below screenshots of the open projects list, Command Palette, Go to Symbol, Go to File with settings exactly as they are in my first post. project list is the only one, where the foreground color of the currently selected tile is red. Is It different if you set it like that in your vscode settings?
Maybe it's connected to the theme I'm using (seti monokai). i'll try again with default theme today.  

<img width="517" alt="projman" src="https://user-images.githubusercontent.com/2669027/54242031-7a290480-4566-11e9-8d5f-eb7d11881d70.png">
<img width="513" alt="cmdpalett" src="https://user-images.githubusercontent.com/2669027/54242043-857c3000-4566-11e9-9e53-380d29e52f2d.png">
<img width="525" alt="gotosymbol" src="https://user-images.githubusercontent.com/2669027/54242052-8d3bd480-4566-11e9-8bb6-67dd89e0ac94.png">
<img width="522" alt="settings_json" src="https://user-images.githubusercontent.com/2669027/54242058-9462e280-4566-11e9-919b-a6aa409ac438.png">

**Comment by alefragnani** [comment]
Hi @cyrus86 ,

Wow, I didn't noted the difference while using other machine (probably theme related) sorry. Now at home, I see better.

But I think it's still a VS Code issue. Try opening `Preferences: Color Themes`. You will see that the list of themes is presented just like the list of projects (red foreground, instead of black). So, I suppose the PickList component provided by VS Code API is not using the same color definition as the native commands.

Hope this helps

**Comment by cyrus86** [comment]
> Try opening Preferences: Color Themes. You will see that the list of themes is presented just like the list of projects

Wow, you're right! I didn't check that one. Thanks, I'll see if I need to raise and issue with vscode or I'm just missing the right colorCustomization setting.

**Comment by alefragnani** [comment]
Probably related items:

- https://github.com/Microsoft/vscode/issues/54509
- https://github.com/Microsoft/vscode/issues/46129
