### ISSUE TITLE
Using `*.code-workspace` as the current project still makes it show up in the list

### ISSUE THREAD

**Issue by AndreasBackx** [alefragnani/vscode-project-manager#260]
Perhaps related to #151, though I read on a few issues here that you could get multiroot projects to work by using the `.code-workspace` file as the `rootPath`, which indeed worked. However there seems to be a small bug. When one of these projects is activated, it still shows up in the list of projects when switching projects. Would this require #151 to be resolved first?

**Comment by alefragnani** [comment]
Hi @AndreasBackx ,

Yes, this scenario is not supported (adding a `.code-workspace` in `projects.json`.  So, you will have to wait for #151 to be officially released.

I'm thinking about to give up from https://github.com/Microsoft/vscode/issues/37421, because unfortunately, I don't see it being released soon 😞 .

Hope this helps

**Comment by alefragnani** [comment]
@AndreasBackx , that doesn't mean I would give up from supporting Workspaces. Just the way it _should_ work 😁 

Stay tuned.
