### ISSUE TITLE
Startup too slow

### ISSUE THREAD

**Issue by innerlee** [alefragnani/vscode-project-manager#264]
Win10

I have to wait more than 10s to see the project sidebar appears. Then I have to wait because I rely on it to switch projects.

**Comment by alefragnani** [comment]
Hi @innerlee ,

What kind of projects to you have? Do you use only Saved/Favorite projects, or also uses the auto-detection feature for Git, SVN, etc..?

If you only have Saved/Favorite projects, this behaviour is not expected, because it only have to load the project list from a json file (unless, of course, you project list is huge). 
If you have auto-detected projects (no matter the kind), this behaviour _would_ happen if for some reason you changed `projectManager.cacheProjectsBetweenSessions` to `false` (The default value is `true` so the list of auto-detected projects is _cached_. Otherwise, it would happen only if the number of auto-detected projects (them sum of each kind) is also huge.

* How many projects do you have _listed_? 
* If you have any auto-detected project configured, how much time it takes to _refresh_ the project list (run `Project Manager: Refresh Projects` command)
* What kind of HDD (SSD or not) do you have?

Hope this helps

**Comment by innerlee** [comment]
hi, 5 favorite and 87 git projects.

`cacheProjectsBetweenSessions` is true

`Project Manager: Refresh Projects`: 5s

SSD

**Comment by alefragnani** [comment]
That's really weird.

In this scenario, it would be _instantaneous_ to see the projects in the Side Bar, when you click its button in the Activity Bar, because the extension is activated _when you open a VS Code instance_, an so, the cached projects are also loaded. I'm using a 5400 RPM HDD to load 140 git projects and 20 favorites, and it takes 6s to `Refresh` and 0.05s to show the Side Bar.

But, if you are talking about the time it takes _to show the Project Manager icon_ in Activity Bar, it may be another reason. Run the `Developer: Show Running Extensions` command, and see the time it takes to startup the extension. In my case, it takes 22ms.

Hope this helps.

**Comment by innerlee** [comment]
Yes its weird. I'm talking about the time it takes to show the icon in the activity bar. The `Developer: Show Running Extensions` shows 10ms. But it still appears very late. BTW, the bookmark icon shows up very early, almost instantaneous after the vscode window shows up.

**Comment by alefragnani** [comment]
Well, I don’t know how VS Code decides the “startup order” for the registered/enabled extensions. If I remember correctly, there is no way to force/register any kind of _order_. Otherwise, all extensions would like to be the first 😁 .

I’ve already noted the difference between my both extensions, but it never bothered me, tbh, because of this “non declarative order”, and extensions like Live Share, Typescript Language Server and C# takes around 10 seconds each to start.

I‘ll take a look if there is something that can be changed to make VS Code _priorize_ the extension. Let’s see what I can find.

Stay tuned

**Comment by alefragnani** [comment]
I just found https://github.com/Microsoft/vscode/issues/57481. 😬

**Comment by innerlee** [comment]
cool, thanks!

**Comment by alefragnani** [comment]
Hi @mrx23dot ,

The extension took `651ms` to activate, but as commented above, VS Code decides the order each extension is loaded, and not everything can be made in parallel.

If caching is enabled, the list of repos is stored in a set of `.json` files (one file per kind of project/repo), and the extension will load them next time it is required. No re-search should be made in the file system ever again.

BTW, are your projects stored in symlinks or external drives?

**Comment by aagerblad** [comment]
Having the same issue. Not sure if there's anything I can do to optimize. 
Running in Cursor Version: 1.7.53
VSCode Version: 1.99.3
Extension version 12.8.0
30 local projects, 23 git projects

Steps to recreate:
Open a new Cursor window
Press Project Manager Icon
Wait at least 2+ seconds to see the list of Favorites
