### ISSUE TITLE
Let user choose when to automatically load a Workspace definition file

### ISSUE THREAD

**Issue by cig0** [alefragnani/vscode-project-manager#266]
Hi @alefragnani,

I searched the documentation and this tracker for related issues but couldn't find any.

It'd be really handy for me, and possibly others too, to add the following capabilities to Project Manager:

- Ability to automatically load a Workspace file when loading a project (a.k.a. avoid having to expressly ask to open the Workspace)
- Ability to define per-project when to load an associated Workspace file

I do use workspaces extensively to tailor my editors to the stuff I happen to be working with. Generally speaking, I'd like to _automatically_ load the associated Workspace file (usually at the root directory of each project) whenever I open a project.

Maybe for others they might instead prefer not go that way but rather be able to tell PM when to automatically load a Workspace file, hence the per-project request. 

While I just started using Project Manager - literally, like four hours ago -, it feels it packs all the  missing features in Workspaces, while working perfectly in tandem with it.

With PM I can define, organize and quickly load my projects effortlessly, while the Workspace definition file will take care of loading _just_ the needed stuff for that project: i.e. I don't need to load Ansible related plugins when working with a Jenkinsfile (unless it is part of a playbook, of course) or enable Go syntax highlighting when editing some Terraform module or an OpenShift ConfigMap -- you got the idea.

I hope my request rings a bell on you, if so let me know how can I help.

Grazie!

**Comment by alefragnani** [comment]
Hi @cig0 ,

The "question dialog" you see when you open a folder that contains a `.code-workspace` file inside is something VS Code does, not the extension, so unfortunately, there is nothing I can do about it. I don't know any setting you could change to _choose_ the behaviour, so I suggest you to open an issue in VS Code repo, asking for that.

The extension itself _still_ does not support Workspaces, because of a missing API in VS Code, as you can see tracked in #151. I think that when it does, it will fulfil the scenarios you describe, because workspaces itself does support this customisations in your projects. I would ask you to upvote the [VS Code issue it depends on](https://github.com/Microsoft/vscode/issues/37421) so the VS Code team could give it more attention and release it sooner.

BTW, I'm thinking about to give up from https://github.com/Microsoft/vscode/issues/37421, because unfortunately, I don't see it being released soon 😞 . But that doesn't mean I would give up from supporting Workspaces. Just the way it _should_ work 😁 .

Hope this helps.
