### ISSUE TITLE
Please support multiple folders in the same project

### ISSUE THREAD

**Issue by IRIS-Core** [alefragnani/vscode-project-manager#268]
Some of my favorite projects have multiple folders, please add support for this!
Atm I still have to save the project as a workspace and open it manually since the extension doesn't support multiple folders =(

**Comment by alefragnani** [comment]
Hi @IRIS-Core ,

This is already being tracked in #151, but as you can see [in the comments](https://github.com/alefragnani/vscode-project-manager/issues/151#issuecomment-425164273), it depends on VS Code releasing a proper API. 

I suggest you to upvote the [VS Code issue it depends on](https://github.com/Microsoft/vscode/issues/37421) so the VS Code team could give it more attention and release it sooner.

BTW, I'm thinking about to give up from https://github.com/Microsoft/vscode/issues/37421, because unfortunately, I don't see it being released soon 😞 . But that doesn't mean I would give up from supporting Workspaces. Just the way it _should_ work 😁 .

Hope this helps
