### ISSUE TITLE
Project Name doesn't appear in Status Bar

### ISSUE THREAD

**Issue by iSolutionJA** [alefragnani/vscode-project-manager#273]
#### Description
The project name does not show in the status bar for auto-detected projects unless projects.json is not empty.

#### Screenshots
![Downhill Windmills](https://media.giphy.com/media/WpyWsJOV6Usv9RBa35/giphy.gif)

#### To Reproduce
1. Ensure that projects.json has an empty array
2. Open a project using Project Manager
3. Project name is not in the status bar
4. Add an empty object to the empty array in projects.json.
5. Reload window using "Developer: Reload Window" in the Command Pallete
6. Project name is now in the status bar

#### VSCode
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
Extension Version: 10.5.1

**Comment by alefragnani** [comment]
Hi @iSolutionJA ,

This is the _expected behavior_ today, because the extension itself was originally created to manage for _favorite projects_. It's fun to think that until now, no user (neither me) has requested this 😄 .

Technically speaking, there is no _limitation_ to add this to the extension. Thanks for reporting.

Stay tuned

**Comment by iSolutionJA** [comment]
Yeah, it is a weird issue that most people wouldn't notice😄. I just added one project to favorite projects to get around it since that is such a simple fix. And I'll definitely stay tuned for an update.
