### ISSUE TITLE
Exclude folders via a "glob" string?

### ISSUE THREAD

**Issue by rowild** [alefragnani/vscode-project-manager#278]
Is it possible to exclude folders that, e.g., start with an underline?
```
 "projectManager.any.ignoredFolders": [
    "_*"
  ],
```

**Comment by alefragnani** [comment]
Hi @rowild ,

Sorry, but this is not supported. 

There is an open PR (#199) to handle that, but the main request was accomplished with another PR, and I ended up forgetting to close that PR. No other request has been made since then.

Is there any particular scenario you would like to use, or is it just a _regular_ case?

Hope this helps

**Comment by rowild** [comment]
@alefragnani Thank you for your feedback! 
The scenario in my case would only be as described above: exclude all folders that start with an underline or two.
Do you have plans to add some kind of (I think it is called) "globbing"?

**Comment by alefragnani** [comment]
Well, that’s what I would call a _regular_ case 😄 .

Added to the backlog. Maybe I could use that PR as basis for the feature.

Stay tuned
