### ISSUE TITLE
Plugin Now prefixes `/` to All My Project Roots

### ISSUE THREAD

**Issue by matsieftw** [alefragnani/vscode-project-manager#282]
```[
  {
    "name": "All Projects",
    "rootPath": "~/Projects/",
    "paths": [],
    "group": "",
    "enabled": true
  },
```

Now if I try to access this project, I get an error saying, `The path '/~/Projects/' does not seem to exist anymore on disk.`

This behavior exists on all of my projects now.

**Comment by matsieftw** [comment]
Okay. I think I'll just have to uninstall and find an alternative. Thanks for your time!

**Comment by alefragnani** [comment]
Hi @matsieftw ,

Sorry to hear that, but I have no idea what could happen to _change_ the `projects.json` file, adding this extra `/` (if that is the case). The file is only changed when you _add_ or _update_ a project, otherwise, it only _loads_ it. But,  if the file is _ok_, but when you try to change (load) a project, it displays this message, it could be caused by other reasons.

I hope you have found an alternative extension that fits your needs. I know at least two (one is from a close friend). 

I was in vacation for the last couple of weeks, and totally turned off from my OSS projects.

Wish you the best

**Comment by matsieftw** [comment]
Nothing is changing `projects.json`. It remains exactly as I have typed it, which I copied above. The problem is when I try to select a project, it tries to load the path I have in the `projects.json` but appends `/` to it.

**Comment by alefragnani** [comment]
Hi @matsieftw ,

I'm sorry, but I totally missed an important point here. The extension doesn't support `~` special character. Instead, you should use a _special variable_  called `$home`. Its use is described in readme (but yes, not the unsupported `~`) 

> Use a special variable called $home while defining any path. It will be replaced by the HOME folder.

Hope this helps
