### ISSUE TITLE
"List Projects to add to workspace" command

### ISSUE THREAD

**Issue by grozan** [alefragnani/vscode-project-manager#283]
this extension is really cool, thanks.
One thing which is missing though, I think, is a command to pick a project, and have it added to the current workspace.

"List projects to open" and "List projects to open in new window" are already here. Could a third one be added?

I see it's possible to add a project to the current workspace when right-clicking on it, in the side bar, but you have to get to the mouse for that. I'd like to keep my hands on the keyboard. It's also more efficient to type a few letters to find the one you want, versus having to scroll through a potentially long list)

**Comment by gregmuellegger** [comment]
I just came here to open the exact same proposal. I find that idea really compelling to support "open project", "open in new window" and "add to workspace" from all available entrypoints (sidebar and command palette).

**Comment by alefragnani** [comment]
Hi @grozan ,

Yes, you already have it available in the Side Bar, _today_ 😁 

Thanks for your suggestion

**Comment by alefragnani** [comment]
Instead of `List Projects to Add to Workspace`, I'll add a single `Add to Workspace` command, which will add _the current_ project/folder to the current workspace.

I would even _ignore_ the fact the current opened project/folder is not a Favorite/Auto-detected project, and could be used for _any opened project_. A missing command from VS Code itself 😬 .

**Comment by grozan** [comment]
Hi,

any chance this will make it to the 10.9.0 release?
Thanks

**Comment by grozan** [comment]
Hi, any update on that one by any chance?
Thanks

**Comment by grozan** [comment]
Hi, do you take contributions?
I really can't stand anymore having to reach the mouse every time I want to add a project to the current workspace :-)
How could I work on a PR for that? The vscode-project-manager-core repo is not public apparently. How can someone go and write/test such a change before making a PR?

Thanks

**Comment by alefragnani** [comment]
Hi @grozan ,

Yes, I do take contributions, of any kind 😄 , but right now some pieces of the sources are private, and you will not able to build. I still have some work to do before reopening the sources.

But, about this feature, don't worry, it would be released in the next week 🎉 . I have started a month ago, to release in the latest update, but ended up pausing its development and simply forgot to resume. In the end, it was good, because you remembered me to resume it today, and the solution is better/cleaner than before.

Stay tuned
