### ISSUE TITLE
Adding projects directly into command palette?

### ISSUE THREAD

**Issue by gee-forr** [alefragnani/vscode-project-manager#286]
Hi there,

I used to use a similar project manager plugin in Atom, and it had a great usability feature whereby it would add projects into its command palette and made it really quick and simple to load a project without having to select "List projects to open" first.

Would it be possible to make this fantastic addon add projects as commands directly into the command palette?

Atom then allowed you to hit "enter" to open the project in the current window, and "shift+enter" to open it in a new window. Not sure if that's possible with VSCode.

Anyway - thank you for this extremely useful plugin. VSCode would be significantly more difficult to use without it.

**Comment by alefragnani** [comment]
Hi @gee-forr ,

> I used to use a similar project manager plugin in Atom, and it had a great usability feature whereby it would add projects into its command palette and made it really quick and simple to load a project without having to select "List projects to open" first.

I also used a lot that Atom plugin, before moving to VSCode 😄. It was kind of an inspiration to me, because VS Code didn't have anything like that, natively. It was an opportunity to contribute back to the community.

You don't need to select the `List projects to open` command in the Command Palette, if you use its default _shortcut_ (`Shift` + `Alt` + `P`). The projects itself don't have _shortcuts_ available, and I'm not sure VS Code supports _defining shortcuts on the fly_. I'll take a look 👍 .

> Would it be possible to make this fantastic addon add projects as commands directly into the command palette?

You can do that, using `Project Manager: Save Project` command.

> Atom then allowed you to hit "enter" to open the project in the current window, and "shift+enter" to open it in a new window. Not sure if that's possible with VSCode.

This _should be available_ right from the start, but VS Code didn't provide an API, and two years later (#76) I closed the issue. If an API appears in the future, I'll certainly add it to the extension.

Hope this helps

**Comment by alefragnani** [comment]
Unfortunately, there is no API available to define shortcuts _on the fly_.  Closing the issue
