### ISSUE TITLE
Add "args" to open project command

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#287]
I can't understand how does this feature would binding to the current project?

I think it would be great to add parameters for exec the `code` to the project manager settings file. For an example:

```json
[
  {
    "name": "google_spreadsheets_chat_bot",
    "rootPath": "/raid/user/gitlab.com/blah-blah ",
    "paths": [],
    "group": "",
    "enabled": true,
    "args": "--extensions-dir /home/user/yada-yada"
  }
]
```

It would let us to use more flexible options. Using exported variables would be great too. "before runs triggers" are appreciated too.

_Originally posted by @oshliaer in https://github.com/alefragnani/vscode-project-manager/issues/281#issuecomment-510471885_

**Comment by alefragnani** [comment]
comments in the original issue: 

> Hi @oshliaer , 

> Thank you for your suggestion, but to switch between projects, the extension does not use `code` command line but the `openFolder` command (VS Code API) and it does not provide _args_ to add. 

> I'm not sure such extensibility is possible, because some of the command args may define _how VS Code will open_, so I guess to accomplish such feature, it would indeed need to use `code` command line args. It's not something that I would like to _bring back_ (at the early days of the extension, it worked this way), but I wouldn't say _it won't happen_ 😄 . I'll move it to its own issue.

> Hope this helps

**Comment by oshliaer** [comment]
I was afraid of it.

I'm not sure that we can very easily reload the environment of the vscode application (basing on `openFolder` of API). Most likely there are a lot of cache, optimizers and accelerators. I even think that it is still necessary to restart the aplication from time to time or when installing an extension.

My initial offer is more about the ability to manage the entire environment (of whole current execution), rather than switching between projects in the current process.

As far as I understand the structure of your application, we need to create a startup manager that will control how to exec the code. Even delegating to a bash script would already be very handy.

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue! 

Thanks for your understanding
