### ISSUE TITLE
Create 'group' for project

### ISSUE THREAD

**Issue by api-spinner** [alefragnani/vscode-project-manager#293]
Is it possible to create 'groups' for projects? For example, I have some lambda functions. I would like to separate then like this: http://prntscr.com/otffae

Why I need this? Because if I have all as folder, if I need to activate gitflow, an error ocurred. If I am with just direct folder I need, gitflow is initialised. For example: http://prntscr.com/otfhju

Even if I enter the directory through the terminal, initialize gitflow not works: http://prntscr.com/otfju8

Separating them, each project it will have only one lambda function, but I will group them like: 'Lambda Functions Admin', 'Lambda Functions Clients' ,'Front-end' (Admin and Clients), 'Back-end' (Admin and Clients), 'Another Projects', etc.

**Comment by alefragnani** [comment]
Hi @api-spinner ,

This is already being tracked in #50, but it still depends on proper VS Code API for the pick list. 

You can’t however, have your _visual_ proposal, because there is no API for that. These “sections” needs to be pre-registered by the extension itself, as “part of the extension”, which is not the case. The idea is to have folders and projects, listed as an Explorer view.

Hope this helps.
