### ISSUE TITLE
add project list in status bar

### ISSUE THREAD

**Issue by parsibox** [alefragnani/vscode-project-manager#295]
hi
please always show project list in  status bar 
i have 3 project but when i close the vscode project list not show in status bar

**Comment by alefragnani** [comment]
Hi @parsibox ,

The Status Bar was added to show _the current loaded project_. It's an easy way to detect you have loaded a saved/detected project.

You already have the project list available in the `Command Palette` and a dedicated `Side Bar`, so I think using the `Status Bar` as another way to find projects may be _too much_, but let us know what other users think about it. Upvotes are welcome.

Maybe a `setting` to have this behavior `on/off`.

Hope this helps

**Comment by parsibox** [comment]
i need when i open a file directly , the vscode detect this file is on which project and open that project.
but vscode do not detect this.
then i need to change the project manually.
Status Bar  is the fastest way to change some thing

**Comment by alefragnani** [comment]
Looking closer to your request, I think it should be added to VS Code itself, maybe as a new [Core CLI option](https://code.visualstudio.com/docs/editor/command-line#_core-cli-options). Not only because it _appears to fit_ as a core operation, but also because extensions can't change how VS Code starts (detect a file/folder and replaces the active root folder in the same instance).

I see one simple decision (this new CLI option would do), to _detect the previously opened folder/workspace_ when you open some random file: _How deep it would look?_

So, in this case, I suggest you to open an issue to [VS Code repo](https://github.com/microsoft/vscode/). 

Hope this helps

**Comment by alefragnani** [comment]
I think [this issue](https://github.com/microsoft/vscode/issues/87290) is _kind of similar_ to your request. 

Maybe starting from/referring to, would help the VS Code team.

Hope this helps

**Comment by parsibox** [comment]
yes this is same as my issue
thanks
