### ISSUE TITLE
Highlight the current project in SideBar

### ISSUE THREAD

**Issue by JiahuanZhang** [alefragnani/vscode-project-manager#299]
First  thanks to all developers countributing to this plugin, I like this plugin very much. 
But when I add too many projects in project manager list, I find it`s hard to find out which project this is. So I wander could you add this function : highlight current project in list, 
Finally thanks for your reading.

**Comment by alefragnani** [comment]
Hi @JiahuanZhang ,

First of all, thank you for your kind words. It's great to see you enjoy the extension.

I'm not sure you did noticed, but the name of the _currently opened project_ is displayed in the status bar, so you already have this available _somewhere_ :-) But I agree that, _selecting/focusing_ the current project in the sidebar would help to identify it.

Thanks for your suggestion

**Comment by gerhardcit** [comment]
I live with the project manager. Adding to that, I would prefer to know if a project is already open. Switching to another project is great, but it should not replace the current project.
A super setting like, each project in own window will be super great. So you never have to worry about closing the current one.
I find the Ctrl-w command to list projects very messy. That list needs rework, so I prefer using the project manager.

**Comment by alefragnani** [comment]
Hi @gerhardcit , 

I’m glad you like the extension that much 😄 !

About the “not replace the window” behavior, you already have that available. Just use the `List Projects to Open in New Window` command. It will always open the project in New Window, unless already open.

Hope this helps

**Comment by alefragnani** [comment]
I’ve posted [this question](https://vscode-dev-community.slack.com/archives/C74CB59NE/p1587087282161500) on VS Code Slack and Gitter channels, asking for help on an issue/limitation that I faced while trying to _highlight/focus/select_ the current project. 

Let’s see if someone knows how to deal with that, otherwise I’ll have to close the issue.

Stay tuned.

**Comment by alefragnani** [comment]
No one answered, so I guess it's not possible. 
I opened https://github.com/microsoft/vscode/issues/96146 to ask for a new API.

**Comment by viridia** [comment]
I don't think we actually need to select or focus the current project row. All we need is a way to visually distinguish it from the other rows - this could be done by making it bold, adding a checkmark, or changing the color.

For me this is particularly important because I often have multiple git workspaces for the same project, as I am working on several branches simultaneously; it's easy for me to forget which workspace I am currently in, and a visual aid would help.
