### ISSUE TITLE
Open in new window does not work if it is the currently open project.

### ISSUE THREAD

**Issue by leetmachine** [alefragnani/vscode-project-manager#305]
Issue:
if _project A_ is the currently open project in VSCode, right click _project A_  > "Open in new window" does nothing. 

request:
Allow any project to be opened in a new window, regardless of if its already open. 

purpose:
Many projects have multiple other projects that are colocated under a root folder. I'd like to be able to save the root folder in project manager and then quickly open multiple windows of VSCode to access and run these sub project folders.

**Comment by alefragnani** [comment]
Hi @leetmachine ,

Unfortunately, this is not possible, because VS Code itself does not support to open the same project in another window. There is an open issue in VS Code repo (https://github.com/microsoft/vscode/issues/2686). Please, upvote there...

Once this issue is released, the extension will work as you expect

About your _purpose_, have you take a look at how **Workspaces** works? It will be only one Window open, but with many different _root folders_ available_ for you in the explorer tab

Hope this helps
