### ISSUE TITLE
How to set a specific file as main file ?

### ISSUE THREAD

**Issue by vinodvinu** [alefragnani/vscode-project-manager#314]
Hi,
I am using Nim programming language. I have 10 files in my project and i want only one file to run all the time. Rest of the 9 files are include files. So now, visual studio is running the active file. So each time, when i want to run, i need to activate the main file. Is there anyway to setup a specific file as main file and i can easily press run button and run the code no matter what file is active.

**Comment by alefragnani** [comment]
Hi @vinodvinu ,

The extension has no control about _which file should run_ in a project, because in fact, it does not know about any programming language. Its idea is to manage your projects/repositories, giving you an easy way to switch between them. 

I think, in your case, you are running the [Nim extension](https://marketplace.visualstudio.com/items?itemName=kosz78.nim), right? If that's the case, you should look at it's readme page, because I see two options to you.

* define a `Task` to build a specific file
* use the `Nim: Run selected file` command

If that's not the case, I think you should ask this question in [Nim's extension repo](https://github.com/pragmagic/vscode-nim/issues), so someone with better experience in that extension could help you.

Hope this helps

**Comment by vinodvinu** [comment]
@alefragnani , 
Thanks for the answer, I think your suggestions are right. I need to try it.
