### ISSUE TITLE
"No projects saved yet" error on a fresh install of VS Code

### ISSUE THREAD

**Issue by thimalw** [alefragnani/vscode-project-manager#315]
This happened after I did a fresh install of macOS Catalina and installed VS Code on it.

I figured that the `projects.json` file wasn't getting created and the reason was that the `alefragnani.project-manager` directory in `/Users/username/Library/Application Support/Code/User/globalStorage` was owned by the `root` user and didn't have any write permissions for the `staff` group. I changed the ownership of it to my user account and the extension started working as expected.

I'm not sure whether this is a common issue in macOS or specific to Catalina, or if it's just a one time occurrence. I've been using this extension for about 3 or 4 years now on multiple computers (Windows, Mac and Linux) and this is the first time it happened. But this is also the first time I installed the extension after May 2019 when the directory of `projects.json` was changed to `globalStorage/alefragnani.project-manager`.

Edit: I was getting the "No projects saved yet" error after I saved some projects.

**Comment by alefragnani** [comment]
Hi @thimalw ,

I see no reason for the folder to be owned by the `root` user instead of the _currently logged user_, unless it has been started with `sudo`. Maybe you were in terminal with `sudo` while opened VS Code for the first time. Even tho, it should create the folder in `/Users/root/...` instead of `/Users/username/...`. I _don't_ have macOS Catalina, BTW 😞 

The API the extension uses to create the folder is no different from other scenarios, and _do not care_ about user permissions/privileges. 

Maybe it's related to the issues the VS Code team is having with macOS Catalina itself (like Notarisation). I'll take a look in VS Code repo for similar issues, to have some idea.

Thanks for reporting.

**Comment by thimalw** [comment]
Hi @alefragnani ,

I just uninstalled and installed the extension a couple of times to check whether I might have been using `sudo` and I think you maybe right. Although, I can't think of a reason why I would have installed the extension during one of those times.

I uninstalled the extension, deleted the `alefragnani.project-manager` folder and installed it again by running VS Code **without** `sudo` and the folder got created with my user and everything worked fine. Then I tried again while running VS Code **with** `sudo` and the folder got created with the `root` user, but in `/Users/username/...` just like the first time.

So, yeah, I might have been running VS Code with `sudo` when I installed the extension the first time without realizing it. Sorry for my mistake. I think you can close the issue.

**Comment by alefragnani** [comment]
Hi @thimalw ,

No need to be sorry. In fact, thank you for double checking the installation scenarios.  your confirmation, we wouldn’t be sure how the error occurred 👍
