### ISSUE TITLE
Clarify the term "project" in the documentation

### ISSUE THREAD

**Issue by jrial** [alefragnani/vscode-project-manager#316]
The documentation of this extension keeps mentioning the term "project", but never clarifies what is meant by that. VS Code already has a built-in way of managing what most of us think of as "projects", but decided to name them "workspaces" instead.

This leaves me a bit confused:
* How does a project differ from a workspace?
* What does the notion of projects add that isn't already achieved with workspaces?
* What relationship, if any, is there between projects and workspaces?
* When using projects, do we still need to set up workspaces as well? Yes/no/optional? And if optional, what features would we miss?

It would be nice if these things were clarified in the README to avoid confusion.

**Comment by alefragnani** [comment]
Hi @jrial,

VS Code has no **Project** concept, like VS, IntelliJ, Eclipse, Delphi, Xcode, when you open a file and it _expands_ the project. Instead, it only open **Folders**. Just recently, it added the **Workspaces** concept, which it nothing more than _a group of folders_. Ok, you can also open single files 😄 .

The extension used the term **Project** (instead of _Folders_) because I new that, at some point, the VS Code team would support multi-folder in the same window. Why I was so sure? Because since VS Code targets Sublime and Atom.

You can save **Folders** or **Workspaces** as **Projects** (the Workspaces support was released in September/2019). Any auto-detected folder (using Git/SVN/Mercurial repositories) will be called **Project** too.

I'm not sure this clarifies to you. I hope so :-) I don't think this needs to be added to the README, but I'll review it, to avoid confusion in the future. Thanks for the tip 👍 

TBH, the VS Code documentation itself confused me at the beginning. The most used term was **Folder**, but remember finding a few occurrences of **Project** or **Folder/Project**. Even **Directory** was available.

Hope this helps.

**Comment by jrial** [comment]
Hmm, I'm not sure I understand you correctly, so I'll just tell you how I understand it and you can correct me if I'm wrong:

* Conceptually, a project and a workspace are the same thing. At first, VSC did not have support for multi-root workspaces, which is why you wrote your own implementation, which you called "project".
* At this moment, workspaces also have multi-root support, so in that regard there is feature parity with your projects implementation.
* However, this extension offers extra features that are not in VS Code. E.g. automatic discovery of projects so you don't have to explicitly create and save them, as is currently the case with workspaces.

**Comment by alefragnani** [comment]
Hi @jrial ,

> Conceptually, a project and a workspace are the same thing. At first, VSC did not have support for multi-root workspaces, which is why you wrote your own implementation, which you called "project".
At this moment, workspaces also have multi-root support, so in that regard there is feature parity with your projects implementation.

Kind of.

 A folder _can be_ a Project, and a Workspace _also can_.

At the beginning, you should **save** each project individually. After a few releases, I added the **auto-detect** feature, so it would detect every folder (git,svn,hg) and list them as Projects.

Hope this helps

**Comment by Gama11** [comment]
I think VSCode also considers folders as "workspaces"? They're just not _mult-root_ workspaces. It seems there's a lot of confusion / discussion around this topic though:

https://stackoverflow.com/questions/44629890/what-is-a-workspace-in-vs-code
