### ISSUE TITLE
Support for remote workspaces

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#318]
When working with remote workspaces, Project Manager's "List Projects to Open" command is no longer a good replacement for the built-in "Open Recent...": As far as I know there's no way to let Project Manager know about remote workspaces, while they do appear in "Open Recent...".

Here's an example with a workspace opened via the Remote SSH extension:

![](https://i.imgur.com/18oPf4z.png)

It is possible to run the "Save Project" command in that workspace, but this doesn't actually work when you try to open it (the saved project has the path on the remote machine as a `rootPath`).

I'm not sure how Project Manager could programatically open a remote workspace. Maybe it would have to invoke a command of the specific remote extension that is used (SSH, WSL, Container...). I wonder how VSCode does this internally in the "Open Recent..." UI.

**Comment by alefragnani** [comment]
Hi @Gama11 ,

First of all, thank you for you PR. I'm on vacation right now, and didn't have the time/resources to properly evaluate it.

I'm still not sure how the extension would work with Remotes At first, I thought about _working locally_ which means ignoring remote folders/workspaces, and displaying just the _local folders_. Then, I thought about _supporting remote folders_, but as you described, I don't know if there are APIs available for that.

If I remember correctly, updating the `extensionKind` info will allow the extension to be _visible_ and _usable_ while opening remotes workspaces (you will see the commands and the Side Bar), but the `Save Project` command (and probably others which depends on the file system) does not work, right?

I'm slowly returning to my OSS projects. Still planning what to do in the next releases 😄 . Stay tuned.

**Comment by Gama11** [comment]
I'm not sure supporting remote workspaces is the or even related to the extension running remotely.

>If I remember correctly, updating the extensionKind info will allow the extension to be visible and usable while opening remotes workspaces (you will see the commands and the Side Bar), but the Save Project command (and probably others which depends on the file system) does not work, right?

Indeed.

**Comment by alefragnani** [comment]
Same here 😄. 

I see two different scenarios, and not necessarily the extension needs to support both:

1. The extension _can be used_ when you connect to remotes
1. The extension _fully supports_ remote file systems, because it recognizes and supports working with it.

In both scenarios, you may have some _limitations_ (like when you use Live Share). In this case, the first scenario (_can be used_) is almost complete with your PR, because:

### It is working

* The Commands are available
* The Side Bar is available
* You can switch between projects

### It **is not** working

* You can't _save_ new projects (because the `projects.json` file is stored _locally_, not _remotely_.

To _fully supports_ remotes, I think it should have:

* _Auto-detect_ projects in the remote
* _Share_ the settings/projects between host and remote

But I'm not sure I would make _full support_ (probably not) 

I don't use remotes that much, and played a little with **Containers** while bringing the Bookmarks extension to remote (still in _alfa_ stage).

**Comment by Gama11** [comment]
> It is working - You can switch between projects

That's exactly the part that's not 100% working / what this issue is about.

In VSCode's "Open Recent" list, you have folders on the local file system in the same list as those `<remote folder> [SSH: <IP>]` entries from e.g. the Remote SSH extension. That's why the Project Manager's "Open Project" command is no longer a viable replacement for the built-in "Open Recent..." for me anymore since I started using remote development support: I can't use it to connect to a remote.

Personally I'm not really interested in auto-detection of projects on the remote, that seems unrelated to this.

**Comment by alefragnani** [comment]
I'm playing with it, and I guess I found a way to _securely_ allow the extension to run while connected to remotes. I won't _fully support_ remotes for now, but at least the extension will be available when connected on remotes.

What I mean about _secure_? I would like to avoid issues while using the `Save Project` command, so, the command will be _disabled_ when running in remote environments.

Stay tuned

**Comment by alefragnani** [comment]
Hi @Gama11 ,

The other Remote Development issue (#284) has raised a few issues, related to some users which (apparently) were using the extension installed _remotely_. Once the `Save Project` is now disabled _when remote_, they can't save remote projects anymore (which was an unexpected scenario to me).

I've created #323 to gather more information about these scenarios, better understand their needs, and release an update which could be used by everyone.

I hope the newly released version works as expected for you. If not, please let me know.
