### ISSUE TITLE
FR: Add a context menu "Reveal in Explorer"

### ISSUE THREAD

**Issue by ghost** [alefragnani/vscode-project-manager#322]
Hey @alefragnani ! 😊👋🏼

I would like to have a context menu called "Reveal in Explorer" which allows me to quickly open a project inside the explorer:
``` Typescript
vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file('path/to/project'));
```
Could you add it under the "Open" and "Open in New Window" context menus ?

![immagine](https://user-images.githubusercontent.com/45769702/73126926-00044180-3fb9-11ea-9094-e175d502489e.png)

Thanks

**Comment by alefragnani** [comment]
Hi @Denis-net ,

That's a great improvement. I miss that myself sometimes, specially in VSCode explorer panel itself 😄 

But I'm not sure adding it under both `Open` commands is the _best_ location. I think adding it to the end of the context menu would be a better option, because it is a command _not related to projects_. I'll think about it.

Thank you for your suggestion

**Comment by Denis-net** [comment]
They have finally added it 🎊🎉
![immagine](https://user-images.githubusercontent.com/45769702/73132301-88b2ca00-4019-11ea-9f06-8f8255397cfc.png)

> I think adding it to the end of the context menu would be a better option, because it is a command not related to projects

I agree with you, because projects are the fundamental principles on which this extension is based.
This feature is more a potato side dish 😂

Thanks for the kind reply.
May you have a nice day !😊👋🏼

P.S. I'm developing a new extension called [Extension Workbench](https://marketplace.visualstudio.com/items?itemName=Denis-net.extension-workbench), Which will support VS Code extension writers in writing VSC extensions more efficiently.
It's still in early stages but it's usable and i have learned a lot of things.
One of them is that the package.json has a field called `extensionPack`: with this you can reference other VSCode extensions that will be installed together with your extension.
So I have grouped other extensions that I believe could help the extension authors, one of which is yours.
I think it's fair to let you know.

**Comment by alefragnani** [comment]
This command exists for a long time, at least in the command palette as `Ctrl/Cmd + K + R`. It appears they duplicated it when added to the context menu. 

But it is different from what you have requested. It will not open _the project's folder_, but instead, _reveal the current file/folder in Explorer/Finder_. Run the command again, selecting different files in your project, to see how it performs. If that fit your needs, there is no reason to add a new command to the extension 😄 .

> P.S. I'm developing a new extension called Extension Workbench, Which will support VS Code extension writers in writing VSC extensions more efficiently.

Congratulations 👏 . I have a few extensions myself, and I really enjoy playing with it.

**Comment by Denis-net** [comment]
>  I miss that myself sometimes, specially in VSCode explorer panel itself 😄

I didn't understand what you meant 😅
The command highlight the selected file or folder in its parent directory (the parent directory get opened in finder).

With the extension i would like to have a command that can open instead of its parent directory the project directory itself, because projects are in different directory and when i want to copy/move/etc a project or do stuff outside the VSCode this can help me.
At the moment: i open it in another VSCode instance and then i reveal a file or folder in order to having its folder open: not so smooth 😅

Thanks for having tried my extension 😄

**Comment by alefragnani** [comment]
> With the extension i would like to have a command that can open instead of its parent directory the project directory itself... 

That's what I means 😆 . 

In the end, the new command is something like `Reveal Workspace in Finder/Explorer`

**Comment by Denis-net** [comment]
Hi @alefragnani, 
Social Force OT: If you (or someone you know) are interested in enhancing TreeViews API with inline-renames, node-dragging or things like that you could join me in [this issue](https://github.com/microsoft/vscode/issues/92848) that i've opened in the vscode repo, which is now backlog-candidate.

And if you have proposed features and you need votes, I'm available 👍🏼
I'm asking here because I've seen that you like to play with TreeViews too ✌🏼

Have a nice day ! 😊
