### ISSUE TITLE
Latest release does not work in WSL2 

### ISSUE THREAD

**Issue by MaurGi** [alefragnani/vscode-project-manager#325]
I had to reverse to the previous version because the current one fails in remote/WSL2 - not sure how to collect logs for it - 

Before udpate (using 10.9.1):
![image](https://user-images.githubusercontent.com/13138584/73804944-2a54bc80-477a-11ea-9e1d-b0957713610b.png)

And the taskbar shows the project correctly:
![image](https://user-images.githubusercontent.com/13138584/73805066-7ef83780-477a-11ea-8406-2e6d602c8c94.png)

After Update (Using 10.10.0):
![image](https://user-images.githubusercontent.com/13138584/73804983-422c4080-477a-11ea-93ef-37fc380ce803.png)

And there is no project name in the taskbar:
![image](https://user-images.githubusercontent.com/13138584/73805000-4e180280-477a-11ea-9251-53be83675ba4.png)

**Comment by alefragnani** [comment]
Hi @MaurGi ,

Yes, this has changed in the latest release. When I added support to remotes, the idea was to allow users to _switch to local projects, even when connected to remotes_. I wasn't expected users to be using the extension _inside the remotes_, and that's why it was defined as `UI`. Sorry about that.

I'm collecting feedbacks in #323 , so a new update could incorporate new/better support for these scenarios.

I don't use remotes that much (only Containers, in fact), and didn't played with WSL/WSL2 yet. 

Hope this helps
