### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by Perkin5** [alefragnani/vscode-project-manager#328]
Firstly, this is a great extension that I would not be without. However, occasionally, when I switch between projects using the sidebar and left click, VsCode crashes leaving a completely blank grey rectangle, which needs a restart. When restarted it defaults to the project I just clicked on. I have been unable to identify a particular set of circumstances for the issue, it just seems random, maybe every 6 switches or so. Is this a known issue, is it the extension or is it a VsCode issue? I use Windows 10 64-bit fully up to date.

**Comment by alefragnani** [comment]
Hi @Perkin5 ,

First of all, thank you for your kind words. I'm glad to know the extension helps you :+1

About your issue, I don't remember experienced something like this in Windows (I'm a Windows user at work), but a few users reported _freezing_ in Linux while opening some project, and they could detect it was a VS Code issue (not related to the extension). They where able to detect the VS Code issue simply opening the projects/folders via native VS Code commands.

You could try a few alternatives to help me find out _where_ is the problem:

* Does it happen with _some particular kind/set of projects_. You said its _random_, but we could try to identify a _pattern_. 
  * Are these projects on remote location/external disk? 
  * Are these projects workspaces, instead of folders?
  * Are these projects _saved_ (Favorites) or _auto detected (like Git)_
  * Do these projects have some _tooling_ or _enabled/disabled extensions_ which differs from others?
* Do this happens only if you use the Side Bar?
  * Open the project using the commands from the `Command Palette`
  * Open the project using VS Code native commands, like `Open Recent` or `Open Folder/Workspace`
  * Open the project using the command line (`code C:\Folder1\Folder2\Projects_Folder`)

The extension itself does nothing special about the projects. It simply calls the native command `openFolder` with the project's path as argument:

```
    vscode.commands.executeCommand("vscode.openFolder", uri, forceNewWindow)
        .then(
        value => ({}),  // done
        value => vscode.window.showInformationMessage("Could not open the project!"));
```

Unless something weird is happening to that path (uri), it should work

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
