### ISSUE TITLE
It's unclear to me, what is workspace?

### ISSUE THREAD

**Issue by 1st** [alefragnani/vscode-project-manager#349]
I see in the new version mention of `Add Project to Workspace ` option. Tried it but it's unclear, what does it do? If I will do it for one, then for the second project - should it somehow open two projects in the same window?

Please add such info to the doc to make it clear.

**Comment by alefragnani** [comment]
Hi @1st ,

Workspaces are a VS Code concept, not from this extension. Basically, it is the ability to open multiple folders in the same VS Code window.

You can see more details [it its official docs](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

Hope this helps.

**Comment by 1st** [comment]
Ok, I get it. But what is the option “Add Project to Workspace”? I don’t get how it works logically. Is it possible to add two projects to the same workspace?

@alefragnani

**Comment by alefragnani** [comment]
Exactly! 

The original request for this command was to be able to add _some of your Project Manager’s projects_ to the current Workspace.

For instance, let’s say you open a random workspace with two root-folders (like a backend and front apps). Then you feel the need to add another front end app as another root-folder, and _you know_ this front end app is saved/available in Project Manager. Instead of searching for that new front end project in finder/explorer, you use the `Add Project to Workspace` and select the front end project.

Now you have 3 root-folders in your workspace.

Hope this helps.
