### ISSUE TITLE
Saving Workspace from Dashboard ?

### ISSUE THREAD

**Issue by SheepDomination** [alefragnani/vscode-project-manager#362]
Is it possible to have project manager work with the dashboard extension so one can send the workspace as a favorite to project manager from dashboard ?

Also add a project manager favorite to dashboard as a project ?

**Comment by alefragnani** [comment]
Hi @SheepDomination ,

I’m not sure which dashboard extension you are referring to, but right now the extension doesn’t export neither consumes any extension. 

Depend on the kind of integration, support and interest from the community, I could think about it.

Could you provide more details?

**Comment by SheepDomination** [comment]
The extension is called Dashboard; this extension you can create projects and add projects to the current workspace .  Although switching between workspaces is a pain, but that is where project manager fills in those holes. 

I'm unable to directly add a workspace from dashboard to the project manager favorites, this being one addition to project manager.

**Comment by alefragnani** [comment]
Do you mean [this one](https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard)?

I remember seeing it sometime ago, when I thought about doing a custom UI to the Project Manager extension, because of a missing API to accomplish #50. In the end, I thought it would be to much 😄 .

Well, I never had the need to expose APIs from my extension, and I’m not sure VS Code has something like Atom had, but if that’s something doable, and the developer from Dashboard extension is open to that too, we could make an arrangement.

Hope this helps

**Comment by SheepDomination** [comment]
Yes that is the extension.  Would you know if it's doable, I can hopefully make it aware to the developer of that extension and hopefully both can work together ?

**Comment by alefragnani** [comment]
I’m closing this issue to continue the chat in #365
