### ISSUE TITLE
Change Font and Icon in Favorites ?

### ISSUE THREAD

**Issue by SheepDomination** [alefragnani/vscode-project-manager#363]
How can I change not only the font size but the icon in Project Manager: favorites ?

**Comment by alefragnani** [comment]
Hi @SheepDomination ,

I’m sorry to say, but you can’t customize these details. 

The font name, size, color and other decorations, follows VS Code identity/customization (are defined/customized by VS Code itself), so when you change one Tree view, all follows the same identity.

The icons, on the other hand, are hard-coded, and there are no settings available for that. I think you are asking this because you may be using some File Icon theme, which customizes Folders and Workspaces icon. If that’t the case, until VS Code _exposes_ the icons to be used in _nodes_, those two icons will not follow the theme.

Hope this helps

**Comment by SheepDomination** [comment]
If you can have different icons natively in explorer, why not with project manager favorites; that ties into an identity issue ?

**Comment by alefragnani** [comment]
You can't, because VS Code itself doesn't "allows" Tree Item nodes to _reference_ their icons, yet. I remember seeing ao open issue for that sometime ago, and it may be released soon, because of their iconography rewriting. After that, I should replace the extension's icons in favor of VS Code codicons, like I did last month with some of the icons.

For now, only commands (in Command Palette, Tree View headers, Tree View context menu, Tree View inline) and items in Command Palette, can.

But, the extension itself may end up with its own custom icon in the future (remote folders), if they don't release a proper one.

Hope this helps

**Comment by SheepDomination** [comment]
How about one adding their own icons, same problem ?

**Comment by alefragnani** [comment]
I think so.
