### ISSUE TITLE
Ability to map a keyboard shortcut to open a specific project (or close if it's currently open)

### ISSUE THREAD

**Issue by macintacos** [alefragnani/vscode-project-manager#367]
It'd be really nice if I could map a keyboard shortcut to open a specific project. 

Example: I have a `dotfiles` project that I randomly edit throughout the day which contains a lot of my environment's configuration files. It's common for me to open/close this project at will since it's mainly just editing configuration files that affect things globally. There are a few other projects that I have that fit this description as well, and it would be nice if I could map each of them to their own unique keyboard shortcuts.

I'm sure I could come up with something if I put my mind to it, probably some hack using [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command), but I'd rather this be built-in. If this is already possible, I couldn't figure it out, and would love some pointers :)

**Comment by alefragnani** [comment]
Hi @macintacos ,

Unfortunately, this is not possible right now, because extensions can't register keybindings in runtime. Instead, all keybindings are registered in extension's definition file (while publishing). 

I remember seeing in recent VS Code releases (I guess last year), that end users could add `args` to commands while defining custom `Keyboard Shortcuts` so maybe, you could create a new Keyboard Shortcut, to open your `dot files` project. I suggest you to take a look at VS Code repo for more info.

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if you have more questions.
