### ISSUE TITLE
The git.baseFolders setting expects Windows like paths in OS X

### ISSUE THREAD

**Issue by AbhiramH** [alefragnani/vscode-project-manager#383]
The `projectManager.git.baseFolders` setting on Mac OS X does not work with traditional OS X paths, like `~/my/projects`. It only works if Windows like paths are provided, like `$home\\my\\projects`.
This is very non-intuitive and there is no mention of this in the docs either.

**Comment by alefragnani** [comment]
Hi @AbhiramH ,

It works, but it does not support the `~` symbol (because it is a *nix feature). Instead, you must use another _variable_ called `$home`, which I created to be _platform independent_.

So, you can use something like this, and it will work:

```json
    "projectManager.git.baseFolders": [
        "$home/Documents/GitHub",
        "/Volumes/AnotherDisk/sources",
    ],
```

This _variable_ is mentioned in the README file (https://github.com/alefragnani/vscode-project-manager#edit-projects)

> Use a special variable called `$home` while defining any path. It will be replaced by the HOME folder.

Hope this helps
