### ISSUE TITLE
maxDepthRecursion setting shouldn't worry about extra trailing path separator

### ISSUE THREAD

**Issue by Shatur95** [alefragnani/vscode-project-manager#404]
Thank you for the awesome plugin!
Is there a way to completely disable recursion? `"projectManager.any.maxDepthRecursion": 1,` still scans first folders from found directories. For example:

```
"projectManager.any.maxDepthRecursion": 1,
"projectManager.any.baseFolders": [
    "/mnt/Files/Code/"
]
```

Shows all found folders in `/mnt/Files/Code/` and every first-level folder inside it. I would like to have the ability to display only top-level found folders.

**Comment by alefragnani** [comment]
Hi @Shatur95 ,

In fact, while testing your request (because I was pretty sure it worked), _I just discovered an undocumented feature_ 😬  

Remove the latest slash from your path, and it will work. I mean, use `/mnt/Files/Code` instead of `/mnt/Files/Code/`.

It shouldn't be considered, and I don't know how no one noted that before. I should fix it on the next release.

Thanks for pointing me this.

**Comment by Shatur95** [comment]
Interesting :) You are right, removing slash helped me, thanks.

**Comment by Shatur95** [comment]
I noticed another problem without trailing separator: it displays `Code` (Projects folder) in project list too.

**Comment by alefragnani** [comment]
Weird, it didn’t happen on my test. 

Are you sure the base Folder is not a Git repo, or is also saved as a **Favorite** project (used the `Save Project` command)

**Comment by Shatur95** [comment]
Yes, it just a folder that only contains nested folders.

**Comment by Shatur95** [comment]
```bash
/mnt/Files/Code $ ls
Sample/
```

![изображение](https://user-images.githubusercontent.com/22453358/90322234-8df64880-df5a-11ea-97fe-b79748a3a099.png)

**Comment by alefragnani** [comment]
Well, that I would say it is _by design_. 

The `Code` folder itself is a _regular_ folder (which is the kind of folder the `Any` handles), so it is also recognized as a project you want to see. That's why I asked about it being a Git folder (you described `projectManager.git.baseFolders` at the beginning).

Hope this helps

**Comment by Shatur95** [comment]
Got it. I would expect that the folders I add for `Any` are the ones whose contents will be scanned. I never need folder with other projects on my computer as a project itself.

**Comment by alefragnani** [comment]
Yep, but it _can add_ the `baseFolders` as well.

I see your point, and if you really think it would be a good feature to _remove_ the `baseFolders` from the detected projects, feel free to open a new issue. Doing so, other users could upvote, and it would land on future releases.

Hope this helps

**Comment by Shatur95** [comment]
Done, thanks.

**Comment by alefragnani** [comment]
In fact, this _extra trailing path separator_ issue has been reported before, but on a PR with a different initial request (#230). 

I'm not sure why it ended up lost in time 😞
