### ISSUE TITLE
Feature Request: Folder Structuring

### ISSUE THREAD

**Issue by UnRealReincarlution** [alefragnani/vscode-project-manager#416]
I understand that modifying existing JSON files to suit this change may prove to be a challenge but I will share my idea nonetheless. 

The idea is that as a user, you can **create folders** in which you can drag your projects this meaning that for example I could have the **games that I have developed in a folder**, **my websites in another** **etc...** I personally would greatly appreciate this feature as I have many projects stored using your project manager and the tab is beginning the get rather cluttered :smile:.

P.S Another feature could be to add folder icons that fit with the theme i.e if I had a unity game then the icon could be either unity or C# etc... This could be selected by the user of course.

**Comment by alefragnani** [comment]
Hi @UnRealReincarlution ,

Your first request is very similar to #50, which instead of _freely organise the projects_, you could define groups for each group and see the projects organised by them. About drag & drop, there is no API available for that, so it's not possible.

About the _folder icon_, I think the easiest way could be adding the icon as an additional info for each group, so the same icon could be used in the Side Bar. I'm not sure about using the Theme info. I guess it is the other way around. The extension must publishes icon metadata that the Icon Theme applies. But I'll take a look.

I'll close your issue as a #duplicate, and I'll paste your icon suggestion in #50. 

Hope this helps
