### ISSUE TITLE
Feature request: Open in New Window when I click with holding ctrl-key

### ISSUE THREAD

**Issue by lsyqll** [alefragnani/vscode-project-manager#418]
"List Projects to Open" is my favorite feature in the project manager.

Is it possible to open in new window when I click a project with holding ctrl-key?

VSCode feature "File: Open Recent..." has already have this feature.

Thanks.

**Comment by alefragnani** [comment]
Hi @lsyqll ,

Unfortunately not, simply because there is no API available to do that 😞 

It has already been requested before, the first time was in 2016 (#76), when I asked the VS Code team to provide an API (https://github.com/microsoft/vscode/issues/18064), but until now, no news. It’s neither on their backlog, so I guess it won’t happen anytime soon.

I'm subscribed to that issue, so if/when it is closed, I'll be notified.

Sorry about that
