### ISSUE TITLE
[FEATURE] - Detail tooltip when hovering over project in sidebar

### ISSUE THREAD

**Issue by tillig** [alefragnani/vscode-project-manager#422]
I think the #50 grouping mechanism and #366 side bar sorting support would go a long way to help better navigate projects in the side bar (which I use exclusively; not the command palette)... but it might be nice to hover my mouse over an item in the sidebar and see a tooltip with the full path to the project. If not on hover, maybe the ability to select a project with a single click in the side bar _without_ having it open so it can display some info, then double-click or click the "open" icon in the side bar to actually do the open operation.

The goal here is to get some info about the project before opening it. Opening the project, depending on project type, kicks off dependency restore, static code analysis, and other processes which aren't valuable to start if you clicked the wrong project.

**Comment by alefragnani** [comment]
Hi @tillig ,

The Side Bar already displays a `Tooltip` while hovering the mouse on every project. Today, it displays its _full path_ so you can easily see the project location.

Double click is not supported, simply because there is no API for that. And based on reports on VS Code repo, I guess it won't ever happen, basically because VS Code itself doesn't work this way.

There are two issues requesting some additional info for each Git project (#378 and #402). And #310 asks for a _description_ for **Favorite** projects.

Is there any additional info you think is missing? Otherwise, I guess the issues I listed covers most of your scenarios, right?

Hope this helps

**Comment by tillig** [comment]
I guess I just didn't wait long enough for the thing to pop up. I hovered, didn't see anything, and... man.

/slaps-self-in-forehead

I appreciate your response and your patience with me. The extension is awesome, just started using it today and loving it.

**Comment by alefragnani** [comment]
Thanks for your kind words. 

That's great to see it works for you. Enjoy 😉

**Comment by inwardmovement** [comment]
Is there a way to disable the tooltip?

**Comment by alefragnani** [comment]
Hi @inwardmovement ,

No, there is no way. Out of curiosity, why would you like that?

- The info displayed is not useful
- The display timing is not good
- The tooltip messes up the Side Bar use
- You don't like tooltips at all

Depending on your complaints, maybe is a VSCode issue and you should report to them. If is something to be improved here, feel free to open a new issue.

Hope this helps

**Comment by inwardmovement** [comment]
@alefragnani As far as I'm concerned the info displayed is not useful.
As I have tooltips displayed without any delay, it cluters the UX of the projects list. A simple disable switch would be great :)

**Comment by alefragnani** [comment]
Thanks. Let’s see how other users react 👍
