### ISSUE TITLE
[FEATURE] - Support remote location in automatic detection 

### ISSUE THREAD

**Issue by vladmandic** [alefragnani/vscode-project-manager#424]
Project manager works with remote projects just fine when manually added, but cannot automatically detect them when adding scan location (either WSL or SSH):

This does nothing:
```json
    "projectManager.git.baseFolders": [
        "vscode-remote://ssh-remote+wyse/home/vlado/dev",
        "vscode-remote://wsl+Ubuntu/home/vlado/dev"
    ],
```

But manually adding projects works fine:

```json
[
	{
		"name": "Project: PiProxy",
		"rootPath": "vscode-remote://ssh-remote+wyse/home/vlado/dev/piproxy",
		"paths": [],
		"group": "",
		"enabled": true
	}
]
```

**Comment by alefragnani** [comment]
Hi @vladmandic ,

This has been requested a few weeks ago in #409, but as you can see, it was closed basically because of VS Code limitations. When connected to remotes, you are connected to some _location_ instead of the computer itself, and the extension won't be able to _detect_ Git repos.

You could take a look at the Remote Extensions repo/docs, and maybe the settings that I suggested on #409 could work for your scenario somehow. Unfortunately for the other user, it didn't.

Hope this helps

**Comment by vladmandic** [comment]
Sorry for the duplicate, somehow I missed it.
In my case, dev system is static and it was easy to create script that adds all projects for me - seemed easier than tweaking VSCode.

Hope VSCode enables this workflow out-of-the-box in the future.

**Comment by alefragnani** [comment]
> Sorry for the duplicate, somehow I missed it.

No problem 👍 

> Hope VSCode enables this workflow out-of-the-box in the future.

I think this could happen in the near future. VS Code team is eager to make Remote works the best way possible. I'm subscribed to that issue, and I suggest you to upvote/subscribe it too. When it is released, we will be notified.

Stay tuned
