### ISSUE TITLE
[BUG] - command '...' not found

### ISSUE THREAD

**Issue by ghost** [alefragnani/vscode-project-manager#425]
**Environment/version**

- Extension version: 11.3.0
- VSCode version: 1.49.0
- OS version: Windows x64 10.0.19041

**Steps to reproduce**

Every commands don't work, either by clicking the icons or by typing the commands. I tried to uninstall the extension and to reinstall it, but it's still the same issue.
![ProjectManager_Bug](https://user-images.githubusercontent.com/70806235/93021614-85248100-f5b1-11ea-83ec-133c3d8997c4.png)

**Comment by alefragnani** [comment]
Hi @StormyWarrior8 ,

It appears you have _another extension_ conflicting with **Project Manager**, because the extension doesn't have all those buttons on its Side Bar.

You would only see `Save Project`, `Edit Projects` and `...`. This last one _replaces_ the VS Code native, only if you _intentionally_ decided to hide the Git Welcome Panel.

![image](https://user-images.githubusercontent.com/3781424/93029724-a3ab6c00-f5f3-11ea-8e04-86c6bbb5f093.png)

![image](https://user-images.githubusercontent.com/3781424/93029739-d48ba100-f5f3-11ea-8b3d-b08b21563bda.png)

Before running any command (or clicking any button) open the `Developer Tools` (via `Command Palette`) to see if something appears in `Console`.

I would suggest you to start VS Code with _another extensions-dir_ and install Project Manager _alone_. More details about running VS Code [via command line](https://code.visualstudio.com/docs/editor/command-line). Another idea is to open `Keyboard Shortcuts` and search for `projectManager`. This is the list of available commands:

![image](https://user-images.githubusercontent.com/3781424/93029881-02251a00-f5f5-11ea-93a8-7fcae485ba88.png)


Hope this helps

**Comment by StormyWarrior8** [comment]
You can close the issue! Very sorry!

**Comment by alefragnani** [comment]
No need to be sorry 👍 

Were you able to make it work? What was happening?
