### ISSUE TITLE
[BUG] - `projectManager.git.baseFolders` can't find any git projects in WSL

### ISSUE THREAD

**Issue by andyliangtw** [alefragnani/vscode-project-manager#427]
**Environment/version**

- Extension version: v11.3.0
- VSCode version: 1.49.0
- OS version: Windows 10 > WSL1 - Ubuntu 18.04

**Problem**

Project Manager (Git Projects) can't find any git projects when I'm using remote development of WSL.
I've tried to add these probable paths to `projectManager.git.baseFolders`, but none is available.

- `/path/to/git/projects`
- `vscode-remote://wsl+Ubuntu/path/to/git/projects`
- `\\path\\to\\git\\projects`

Additional, I've tried these three in VScode's settings for users and settings for Remote.
Of course, none is useful.

I'm sure that the path is right, and I can use this feature in other OS.

If this issue is dulplicated, I'm sorry in advance.

Very appreciated to this extension and all its features!! Very convenient and useful, which saved my time in switching projects.
Thanks in advance!!

**Comment by alefragnani** [comment]
Hi @andyliangtw ,

This has been requested a few weeks ago in #409, but as you can see, it was closed basically because of VS Code limitations. When connected to remotes, you are connected to some location instead of the computer itself, and the extension won't be able to detect Git repos.

You could take a look at the Remote Extensions repo/docs, and maybe the settings that I suggested on #409 could work for your scenario somehow. Unfortunately for the other user, it didn't.

I think this could happen in the near future. VS Code team is eager to make Remote works the best way possible. I'm subscribed to that issue, and I suggest you to upvote/subscribe it too. When it is released, we will be notified.

Hope this helps

**Comment by andyliangtw** [comment]
Thank you for the helpful & detailed explanation!! Very appreciated.
Hope this can be solved by VS code team ASAP.
