### ISSUE TITLE
Load project list from directory

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#43]
Great extension! :+1: 

Having a lot of different projects to switch between (well over 100), I would love a feature that allows me to provide a path and have the extension automatically scan that recursively and add all folders with a `.vscode` subdirectory to the projects list. Perhaps the path(s) to scan could be entered in the `projects.json` some way, so the projects are updated automatically?

**Comment by alefragnani** [comment]
Thanks :smile:  

Great ideas :) I mean _ideas_ because I see two different things:

1. Import projects: Scan for `.vscode` subfolders, inside a folder and automatically add it as new projects
2. Auto-detect projects: Automatically update the projects list, based on scanning when you call `Project Manager: List".

Both are welcome enhancements :+1:

I will take a look at these after finishing [New sortList - MRU](https://github.com/alefragnani/vscode-project-manager/issues/38)

**Comment by Gama11** [comment]
Cool! Keep up the great work, this extension has made me a lot more productive already. :)

**Comment by fuchao2012** [comment]
waiting for the upgrade of this extension. 

Auto-detect projects name is useful.

**Comment by alefragnani** [comment]
I updated the idea I little bit 😄 

 Instead of _import projects_ to you `projects.json`, you will be able to _load VS Code projects dynamically_. You just have to add a new setting, defining a list of folders _that contains VS Code projects_, and all projects will be presented in the same list.

Stay tunned.

**Comment by alefragnani** [comment]
Released in version 0.11.0

**Comment by Gama11** [comment]
Took me way too long to actually get around to checking this feature out. I have to say, I really like the way it's implemented (especially that there is an option to look for Git projects as well). Cheers! 👍
