### ISSUE TITLE
[FEATURE] - Set Color Theme per project

### ISSUE THREAD

**Issue by Josh-of-TT** [alefragnani/vscode-project-manager#430]
I would like to be be able to add a color theme to my project object, resulting in each project using the theme specified.

`{
		"name": "first project",
		"rootPath": "$home/first-project/",
		"paths": [],
		"group": "",
		"enabled": true,
		"colorTheme":"Cobalt2"
	},{
		"name": "second project",
		"rootPath": "$home/second-project/",
		"paths": [],
		"group": "",
		"enabled": true,
		"colorTheme":"Seti Monokai"
	}`

**Comment by alefragnani** [comment]
Hi @Josh-of-TT ,

I’m not sure you are aware off but, there are 3 levels of settings: User, Workspace/Folder and Per Folder on multi-root Workspaces. And all of them are _file based_ settings, with no _runtime_ feature.

With that in mind, how do you think this _Per Project_ setting would work? I mean, should it _override_ the lowest level setting (located at `.vscode/settings.json` file). If that’s the case, it wouldn’t rollback the settings when you close the project/VSCode, because there is no API for that.

I think the `Workspace` setting should be a good alternative, because so no matter you use the extension, or native VS Code commands (`Open Folder`/`Open Recent`) the same theme would be used you you open that project/folder/workspace.

What do you think?

**Comment by Josh-of-TT** [comment]
@alefragnani I think `Workspace` is the perfect place. Thanks for the clarity.
