### ISSUE TITLE
[BUG] - Duplicate Project Manager icon in sidebar

### ISSUE THREAD

**Issue by idleberg** [alefragnani/vscode-project-manager#440]
**Environment/version**

- Extension version: 12.0.0
- VSCode version: 1.51.1
- OS version: macOS 10.14.6 (18G6032) / Windows 10.0.190441

**Steps to reproduce**

1. Upgrade to Project Manager 12 from prior versions

![Screenshot 2020-11-23 at 09 04 59](https://user-images.githubusercontent.com/1504938/99939716-fda27d80-2d6a-11eb-84b9-d14f2c7b5e1f.png)

This looks like a remainder from an earlier version to me, not a feature. The duplicate can easily be removed through the context menu, but I wonder whether it's *supposed* to be there in the first place.

**Comment by alefragnani** [comment]
Hi @idleberg ,

It’s definitely _not supposed_ to be there. It should use the same already existing **Project Manager** Activity Bar, because it is defined this way in `package.json`.

It should be presented the same way the **Help and Feedback** panel you see in **Remote Containers** extension (located at the bottom, collapsed at start). You could move it to the _original_ Activity Bar, and this duplicate will be removed.

I wonder if this happened for similar reasons the Activity Bars sometimes, when you update the extension or VS Code itself, loses its icon. Sometimes you have to reinstall the extension, sometimes a simple `Reload Window` also works.

Thanks for reporting. I’ll leave the issue open as a reference if more users face the same problem. 

Hope this helps

**Comment by alefragnani** [comment]
Closing, as no more reports has emerged.
