### ISSUE TITLE
[BUG] - Stop spamming report.*.json files on Remote Server

### ISSUE THREAD

**Issue by mikevare** [alefragnani/vscode-project-manager#445]
**Environment/version**

- Extension version: 12.0.1
- VS Code version: 1.51.1
- OS version: macOS 11.0.1
- Server version: Linux Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64

**Steps to reproduce**

1. Install MS "Remote SSH"
2. Use Project Manager
3. Wait a few minutes, it will creaete a report.*.json file in your home directory

Related: https://github.com/microsoft/vscode-remote-release/issues/2349

**Comment by mikevare** [comment]
I tested it again, I activated Project Manager and I got those Files, I deactivated it and I didn't got any report files. Are you sure this is cased by VSCode? It has no problems with other extensions

**Comment by alefragnani** [comment]
Hi @mikevare ,

Well, you closed the issue, which was _linked_ to something which is open on VS Code Remote extension with no mention to my extension. So, yes, it appeared to be `caused by vscode`.

I've used a few remote scenarios (just Docker _kind_) and didn't noticed this issue. 

The Project Manager extension does not create any `report_` file in project's location, specially if you use _remotes_, because the extension itself don't have access to remote filesystem, and to access there, it should be installed there. The only files it creates are in VS Code internals location, where every extension _can_ touch. 

What are the contents of these files?

**Comment by mikevare** [comment]
It must be something else, it works fine for the last week, sorry.
