### ISSUE TITLE
[BUG] - duplicate project items

### ISSUE THREAD

**Issue by ctf0** [alefragnani/vscode-project-manager#449]
**Environment/version**

- Extension version: 12.0.1
- VSCode version: 1.53.0-insider
- OS version: osx 10.15.7 

**Steps to reproduce**

not sure how but i recently found a duplicate items in the git projects list which both point to the same path, 
 
![Screen Shot 2020-12-25 at 4 56 57 PM](https://user-images.githubusercontent.com/7388088/103137638-35d30e00-46d3-11eb-8f2a-7866c3f85c06.png)

- maybe the cache could have a way to make sure only unique items are added ? 
- or have a cmnd that clear the cached list 
- or add an icon to each list item to manually remove it. "i believe this would be more useful if added to both favorites & git projects list"

**Comment by alefragnani** [comment]
Hi @ctf0 ,

It's odd to see duplicates, because the _detection_ occurs individually for each `baseFolder` you define. Unless you have accidentally added a _subfolder_ of some of the `baseFolders` as a `baseFolder` as well.

Another possibility would be you have called changed the settings, or executed `Refresh ...` or `List Projects ...` command twice, without _waiting_ for the first run to finish. These commands doesn't have a concurrency detection, yet.

Hope this helps

**Comment by ctf0** [comment]
honestly am not sure what exactly happened, but as a safety net, we can have a remove btn for each item so we can remove it manually instead of clearing the global storage.

**Comment by alefragnani** [comment]
If the projects are really the same (same path) then a `Remove` button would remove both, because the list is created based on each path. 

I would ask you a few more details:

* Could you confirm both are the really the same path (hover the mouse and check the `Tooltip`)?
* Could you post the `projectManager.git.baseFolders` setting?
* Which OS are you using?

Thank you

**Comment by ctf0** [comment]
> Could you confirm both are the really the same path (hover the mouse and check the Tooltip)?

yes

> Could you post the projectManager.git.baseFolders setting?

`$home\Public\GitHub`

> Which OS are you using?

osx 10.15.7

**Comment by alefragnani** [comment]
Really weird.

I'm planning a _log_ feature for a while, for debugging purposes. I think it would help for your scenario. 

In the meantime, if you use kept the `cache` setting as `true`, you could check the cached repos and _remove_ the duplicate entry. It's located in the same _default location_ as the favorite projects. Just open it in Finder and you will the the _caches_.

Hope this helps

**Comment by ctf0** [comment]
i actually cleared both the ws storage & global storage and am still seeing the duplicate entry, however the favorites are gone "i was actually going to ask if there is a way to save the favs somewhere so clearing the storage doesn't affect it."

**Comment by ctf0** [comment]
okay, i think i found the issue, changing `projectManager.git.maxDepthRecursion` to `1` removed the duplicate item.

**Comment by alefragnani** [comment]
I didn't test your `vscode-clear-storage` extension, but if it clears the `global storage` of _any extension_ then it removes the cache AND the projects you saved.

Here is the location

![Screen Shot 2020-12-30 at 20 27 19](https://user-images.githubusercontent.com/3781424/103386405-6ce35e00-4add-11eb-889d-da731743ebae.png)

About the `maxDepthRecursion` change, I'm currently using `10` on my settings, and no duplicates 😕 . 

BTW, I know you said both are _the same path_ but, you are using MacOS, couldn't be a _different case_ issue?

**Comment by ctf0** [comment]
am also using the insider build which lately started to have more than a bug pretty much everywhere, so it could be that.

still i believe we can close this now as the issue has been solved "even if we cant find exactly why 🙄 ".

thanks for ur work & help, happy new year.

**Comment by trusktr** [comment]
I'm on 12.0.1, and I see this issue all the time. Example screenshot:

![Screenshot from 2021-05-06 13-20-49](https://user-images.githubusercontent.com/297678/117360857-1eb8df80-ae6e-11eb-8f03-6fb05a755efa.png)

It isn't a big deal though, it doesn't prevent me from doing anything.
