### ISSUE TITLE
[BUG] - Terminal content lost when switch back to project

### ISSUE THREAD

**Issue by turgs** [alefragnani/vscode-project-manager#460]
in my projects I usually have multiple Terminal panes running.

These expectedly disappear when switching projects, but switching back doesn't _restore_ my previous terminal content.

**Comment by alefragnani** [comment]
Hi @turgs ,

The Project Manager extension does not save or restore any _session information_. Everything you see restored, is made by VS Code itself, and right now, VS Code does not support restoring Terminal sessions, as you can see in this issue (https://github.com/microsoft/vscode/issues/20013), opened in VS Code repo.

I suggest you to upvote that issue, to give higher visibility to the VS Code team.

Hope this helps

**Comment by pudgereyem** [comment]
@alefragnani it seems like VS Code did fix the issue you mentioned, [see comment here](https://github.com/microsoft/vscode/issues/20013#issuecomment-783350150). An update from VS Code [can be seen here](https://code.visualstudio.com/updates/v1_54#_retain-terminal-processes-on-window-reload), which reads:

> Local terminal processes are now restored on window reload, such as when an extension install requires a reload. The terminal will be reconnected and the UI state of the terminals will be restored, including the active tab and split terminal relative dimensions.

However this didn't fix the issue where terminal content is lost when switching back to a project. Thinking that it makes sense to re-open this issue?

Thanks for the great work!

**Comment by alefragnani** [comment]
Hi @pudgereyem ,

Looking closer at the issue, I've noticed it talks about window **reloads** only, without mentioning **restore** (which is what happens when you switch back to previous opened projects/windows). So yes, switching between projects (restore previous projects) does not work. 

But, If you do the same thing using `Open Recent` command, you will notice VS Code does not restore the Terminal sessions.

I didn't find a proper issue in VS Code repo (did a quick search) but as previously mentioned, this behavior is controlled by VS Code, not the extension. The extension only opens the desired project (using the native `openFolder` command) so any _state_ VS Code has, is saved/restored by VS Code itself.

I'll try to find an open issue and link here. I would ask you to search too and if you find, please link as well.

Hope this helps

**Comment by pudgereyem** [comment]
@alefragnani that makes sense! I switched to open projects in a new window instead since I can't loose my terminals.

All the best,
Victor

**Comment by alefragnani** [comment]
I found this one (https://github.com/microsoft/vscode/issues/44302), but was closes as _out of scope_. I didn't dig too much, but if I understand correctly, it appears the team will not support that. But, some comments were added with new extensions to support that. Maybe some of that could work for you.

**Comment by LukeDickerson19** [comment]
+1 for this!
