### ISSUE TITLE
[FEATURE] - Ability to easily select a folder that is accessible to all workspaces

### ISSUE THREAD

**Issue by fade2gray** [alefragnani/vscode-project-manager#462]
Would it be possible, from the Project Manager sidebar, to add the functionality to select a folder or folders from a file explorer that can be made common to all listed favourites, without having to manually add a common folder to the root of all projects/workspaces?

I hope that makes sense.

**Comment by alefragnani** [comment]
Hi @fade2gray ,

I'm not sure I understood your idea. 

Do you mean select/define **folders** which should be _automatically added_ to some opened folder and or workspace? Doing so, anytime you open a **single folder**, the VS Code window would become a **multi-root** workspace with that folder(s) added. Or, anytime you open a **multi-root** workspace, it will be updated with new those folder(s)?

If that's not the case, could you explain a bit more what you need?

Hope this helps

**Comment by fade2gray** [comment]
![Capture-projectmanager](https://user-images.githubusercontent.com/1332009/106493522-25bc0480-64b1-11eb-99df-dbe32edbd73b.PNG)

**Comment by alefragnani** [comment]
People say an image worth more than a 1000 words, but sometimes a few words help 😁 .

I see an alternative approach to what I described in the previous comment.

Do you want an option/action/button to select some random folder, and add this selected folder to every **Favorite** Workspace? Like a bulk edit.

**Comment by fade2gray** [comment]
Yes, maybe a folder on the desktop that contains a to-do list that I would like to see accessible from all projects without having to add that folder/file individually to all workspaces. Does that make better sense?

**Comment by alefragnani** [comment]
Oh, right! I'm wondering if this makes sense _to the extension_, but I think is doable. 

The only downside I see is it would be made "manually", because there is no API available on VS Code for that. The current available API only works if you open the Workspace (`.code-workspace` file).

Thanks for the suggestion

**Comment by fade2gray** [comment]
Yes, feature requests I've made previously tend to end up hitting the 'API wall'. Oh well, a script to hack the `.code-workspace`  files it is then. 😁

**Comment by alefragnani** [comment]
Yes, some APIs are not as powerful as we need, but they tend to evolve from time to time. This one in particular, I didn't find any related issue open, but could be asked.

Instead of a script to manually update all selected workspaces (`.code-workspace` file), you could detect when a Workspace is opened, then add the _desired_ folder to the Workspace. Simply use the `vscode.workspace.updateWorkspaceFolders` API. If, for some reason in the future, you need to replace the _desired_ folder, the same API works as well.

I guess, your idea alone, is already an interesting extension to be published. Didn't you find anything similar on the marketplace? Aren't you interested in publishing yourself?

Hope this helps
