### ISSUE TITLE
[BUG] - Git projects: duplicate entries for repos with multiple remotes

### ISSUE THREAD

**Issue by askvortsov1** [alefragnani/vscode-project-manager#466]
**Environment/version**

Version: 1.54.0-insider
Commit: 5e74ad5430203eadf89fd8e99695f4ebdb0e62ad
Date: 2021-02-16T10:26:57.613Z
Electron: 11.2.3
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.10.15-200.fc33.x86_64

**Steps to reproduce**

1. Create a git repo, add multiple remotes to it
2. The git repo will appear multiple times under git packages

**Comment by alefragnani** [comment]
Hi @askvortsov1 ,

The Git locator/detector, does not check or validate for Git info, so having multiple remotes should not affect how the Git repo is detected. I have a few repos with multiple remotes, and didn't notice this behaviour.

Are you sure this duplicate is caused by the multiple remotes? I mean:

* Isn't there any entry at `projectManager.git.baseFolders` setting, which could cause the same folder to be recognised more than once?
* Does it add a duplicate _for each additional_ remote? I mean, 3 remotes means 3 entries on Project Manager?

You could run the `Project Manager: Refresh Projects`, to reload the projects. If for some reason a duplicate entry was added, it should be removed. 

Also, you could hover the mouse over each entry on the Side Bar, to be sure the projects are the same.

Hope this helps

**Comment by askvortsov1** [comment]
Ah, as you suspected, I had a duplicate entry in `projectManager.git.baseFolders`. Thanks for the help, and for making such an awesome extension!

**Comment by alefragnani** [comment]
That’s great to know it works! And thank you, I’m glad you like 👍
