### ISSUE TITLE
[BUG] - Favorite projects missing icons for Folders when using None or Seti Icon Theme

### ISSUE THREAD

**Issue by misolori** [alefragnani/vscode-project-manager#496]
Currently when there are items saved from codespaces we show a nice icon decoration, but the rest of the folders on the desktop don't have any decoration:

<img width="350" src="https://user-images.githubusercontent.com/35271042/116292838-04368600-a74b-11eb-8d7f-bd2e31f275db.png">

Suggestion would be to add an icon for regular folders to fit nicely in the list:

<img width="350" src="https://user-images.githubusercontent.com/35271042/116292997-3516bb00-a74b-11eb-840b-99483440571d.png">

If there's no other remotes, then a flat list with no icons works well. Thanks for this great extension!

**Comment by alefragnani** [comment]
Hi @misolori ,

You are using **Setti** or **None** Icon Themes, right?

If that’s the case, I remember I had an issue with`TreeItem` when these themes were selected, and the item refers to folders. I’m not sure I was misusing the API,  or the API really didn’t support that, but I remember I have fixed.

I think I have to revisit that

Thanks for reporting

**Comment by misolori** [comment]
I am using the default, Seti

**Comment by alefragnani** [comment]
Yep. These themes doesn't have icons for Folders. That’s why its icon is missing. I have to provide an alternative icon/svg to be used on this case.

I wonder if the issue appeared after I embraced Codicons instead of my own SVGs.

Thank you

**Comment by alefragnani** [comment]
Well, I knew I’ve fixed something back then. I fixed the **None** theme, but totally missed **Seti**.

It should be ok in the next release

**Comment by alefragnani** [comment]
Hi @misolori ,

Just out of curiosity, is the **Figma** repo still active/updated, compared to the **Codicons**? I mean, I couldn't find the **GitHub** icon there, just the _-inverted_ one.

I'm asking because as `None` and `Seti` File Icon Themes does not have a _folder_ icon, I have to provide a separate SVG file. And to follow VS Code extension guidelines, I was using the icons from that Figma design file 

Thank you

**Comment by alefragnani** [comment]
BTW, I'm talking about this GitHub icon.

![Screen Shot 2021-05-01 at 16 19 44](https://user-images.githubusercontent.com/3781424/116792787-40dee600-aa99-11eb-8094-f1368f457a37.png)

So, instead of the the one you see today inside VS Code (which is a codicon), it would end up with this one.

I tried to use the SVG file from the `vscode-codicons` repository, (https://github.com/microsoft/vscode-codicons/blob/main/src/icons/github-alt.svg), but it seems thinner than it's `codicon` counterpart. Probably related to the building/converting process?

Thank you

**Comment by misolori** [comment]
> Just out of curiosity, is the Figma repo still active/updated, compared to the Codicons? I mean, I couldn't find the GitHub icon there, just the -inverted one.

The Figma file/repo only gets updated a small handful times of the year. I'd reference the [codicons repo directly](https://github.com/microsoft/vscode-codicons/), which we also have a [preview page](https://microsoft.github.io/vscode-codicons/dist/codicon.html) for the direct name.

> I'm asking because as None and Seti File Icon Themes does not have a folder icon, I have to provide a separate SVG file. And to follow VS Code extension guidelines, I was using the icons from that Figma design file

I would not use File Icons for these items and just use codicons as we have folders + others (GH, WSL, etc.)

> I was able to use vscode-codicons repository. Simply used the github.svg file and had no issue with it. It's the same thickness of other icons 😬

Windows does render icon fonts slightly thicker, which is that difference you are seeing. I'd still opt to use codicons via `ThemeIcon` because our product icon themes feed into those and make it themeable.

**Comment by alefragnani** [comment]
> Windows does render icon fonts slightly thicker, which is that difference you are seeing. 

I'm using MacOS, but I see your point

> I would not use File Icons for these items and just use codicons as we have folders + others (GH, WSL, etc.)
> ...
> I'd still opt to use codicons via ThemeIcon because our product icon themes feed into those and make it themeable.

I would love to use `codicons` only, but unfortunately, it does not work properly. 

If I use `codicon` **only** in `Treeview`, and Theme Icon is defined as `None`, the `TreeItem` "reserves" the space where the Icon would be rendered, and render the `codicon` with the `Label`. 

![Screen Shot 2021-05-04 at 14 00 01](https://user-images.githubusercontent.com/3781424/117042366-3fecc500-ace2-11eb-97ba-85c18744e80f.png)

> You can ignore the `collapse-all` icon. It should have the originals

If I use a `codicon` mixed with my own SVGs in `Treeview`, and Theme Icon is defined as `None`, the `TreeItem` "reserves" the space where the Icon would be rendered, and render the `codicon` with the `Label`

![Screen Shot 2021-05-04 at 14 02 59](https://user-images.githubusercontent.com/3781424/117042427-58f57600-ace2-11eb-9bf0-22be8cef8804.png)

> This is weird 😕 

If I use the `$(folder) codicon` and the Theme Icon does not have `Folder` icon (like `Seti`), the icon is not drawn (because _folders don't have icon for the theme_)

Based on docs, it appears to be the "expected behavior" when your `TreeItem` refers to some Uri. After a few researches without success, I decided to keep my SGVs as a fallback.
