### ISSUE TITLE
Support virtual workspaces

### ISSUE THREAD

**Issue by lszomoru** [alefragnani/vscode-project-manager#501]
👋 Hi there, Martin here, from the VS Code team.

Recently we've announced the [Remote Repository feature](https://code.visualstudio.com/updates/v1_56#_remote-repositories-remotehub) that lets you browse and edit files and folders directly on GitHub.

`Open Remote Repository...` opens VSCode on a folder or workspace located on a virtual file system. We call this a **virtual workspace**. We observed that not all extension support this well, either because they can not, or they haven't thought about it.

It would be fantastic if you could test whether your extension can handle virtual workspaces:

Check out the [Virtual Workspaces Extension Author Guide](https://github.com/microsoft/vscode/wiki/Virtual-Workspaces) on how to do that.

When done, set the new `virtualWorkspaces` capability in your 'package.json'.

```
{
  "capabilities": {
    "virtualWorkspaces": true | false
  }
}
```

- Use `"virtualWorkspaces": true` if your extension is prepared for virtual workspaces
- Use `"virtualWorkspaces": false` if your extension should be disabled when a virtual workspace is opened

For questions and comments please use the [Virtual Workspaces Tracking Issue](https://github.com/microsoft/vscode/issues/123115).

Thanks for the support and the great work! ❤️

**Comment by alefragnani** [comment]
Hi @lszomoru ,

Thanks for reporting, and providing the related links for documentation!

I just miss the information (on that Author Guide) if I also need to update the `engine` entry on `package.json`. I guess no, but if yes, to which value (1.56 or 1.57 for to be in the Insiders). I didn't have to do anything to the extension properly activate while connected to some Virtual Workspace (while debugging) but I'm asking this because I'm worried if for any reason I update the extension to support Virtual Workspaces (adding that `capabilities` to `package.json`) but the user remains with older releases of VS Code (prior to 1.56), which does not _recognizes_ the `capabilities` entry or things like that.

BTW, this is already being tracked in #500, which was opened by your team mate 😬 

Thank you

**Comment by alefragnani** [comment]
Hi @lszomoru ,

Just moved the question above to that [Virtual Workspace Tracking Issue](https://github.com/microsoft/vscode/issues/123115), since it could be useful for other extension developers too.

Thank you
