### ISSUE TITLE
"You must define a name for the project" when saving

### ISSUE THREAD

**Issue by atombender** [alefragnani/vscode-project-manager#51]
1. Installed extension for the first time, and restarted.
2. Selected "Save Project".
3. Typed name and hit Enter.
4. Got the message **"You must define a name for the project"** (flagged as warning, though it's actually an error).
5. Nothing was saved.

![screen shot 2016-09-08 at 16 23 56](https://cloud.githubusercontent.com/assets/50314/18365491/eaeaafe6-75e0-11e6-89ba-290f3bddfd67.png)

Version 0.9.1 on VSCode 1.5.

**Comment by atombender** [comment]
On further testing, it seems this happens if you stick with the default, suggested name. If you enter a new name into the text field, it works.

**Comment by alefragnani** [comment]
It seems the [issue](https://github.com/Microsoft/vscode/issues/11503) reported in the Insider wasn't fixed for 1.5.0. I added a [workaround](https://github.com/alefragnani/vscode-project-manager/issues/42) specifically for the Insider, but since the issue will be fixed only for September release of VS Code, I will have to merge it for the Stable too.

Stay tuned for an update. Probably tomorrow 👍

**Comment by atombender** [comment]
Thanks!
