### ISSUE TITLE
[FEATURE] - Consider tweaking the activity bar icon to blend better with built in VSCode icons

### ISSUE THREAD

**Issue by tomparkp** [alefragnani/vscode-project-manager#510]
I love the extension but the icon feels a little out of place relative to other icons to me. The close lines/crowded detail actually makes the icon appear blurry on my display vs the built in icons which are sharp (screenshots don't capture it well). A more minimalistic folder icon might match better with the built in VSCode icons.

<img width="86" alt="CleanShot 2021-05-19 at 10 54 33@2x" src="https://user-images.githubusercontent.com/2266762/118860748-9c2e1800-b890-11eb-8e12-d8abdaf202ce.png">

<img width="86" alt="CleanShot 2021-05-19 at 10 55 06@2x" src="https://user-images.githubusercontent.com/2266762/118860831-b1a34200-b890-11eb-9b9a-65e92b094035.png">

**Comment by alefragnani** [comment]
Hi @tomparkp ,

Well, I don’t notice too much difference on the monitors/resolution that I use, but I see your point. Yes, the built in icons has become sharper in recent releases (I guess last year).

If you are willing to contribute with a sharper version of this icon, it would be great. I’ll try to find on the free services that I’ve used before, otherwise, let’s hope someone else with proper design skill to do 😬 

Thank you

**Comment by tomparkp** [comment]
@alefragnani Sure I'll look into making a PR when I have some time - thanks!

**Comment by KarlGusta** [comment]
Mine looks okay. Which operating system? Or maybe it is the graphics.

**Comment by alefragnani** [comment]
It's been almost an year, with no upvotes or PR for this issue. So, I'm closing it.

If someone opens a PR in the future, I'll be glad to merge.

Thanks for your understanding
