### ISSUE TITLE
[FEATURE] - Easy way for change IP for remote project

### ISSUE THREAD

**Issue by krutoo** [alefragnani/vscode-project-manager#511]
Hi, in my case i have several remote projects (i connect by remote ssh extension)

sometimes IP address of remote computer changes and i want to change it in Project manager config but i see something like this:
```json
{
  "name": "[remote]sima/product",
  "rootPath": "vscode-remote://ssh-remote+7b22686f73744e616d65223a2231302e39362e31322e313733222c2275736572223a22706574726f765f646d227d/home/petrov_dm/Projects/sima/product",
  "paths": [],
  "group": "",
  "enabled": true
}
```

How can i simply change IP on `rootPath`?

**Comment by alefragnani** [comment]
Hi @krutoo ,

Unfortunately, this is not possible, because that _large hexa info_ is all VS Code API provides as reference to the remote location. It doesn't expose IPs or anything _human readable_. 

And I suppose if you change the IP address of the remote computer, even if you connect _to the same computer_, VS Code will not recognized is as the same, and will work as a different workspace (no session restore).

I think we are out of luck here. Sorry.

**Comment by Aidenir** [comment]
Is there any way to get the remote info about a different remote, so you could setup a new remote and then just change the root path to use the hex-info from the new remote?

**Comment by alefragnani** [comment]
Hi @Aidenir ,

Not the I'm aware of, neither via docs nor API (which doesn't exists).

You could ask them directly in https://github.com/microsoft/vscode-remote-release, in hope some of the developers/users know anything about it. If you find it, please let me know.

Hope this helps
