### ISSUE TITLE
[BUG] - Cannot save or view projects

### ISSUE THREAD

**Issue by celutions** [alefragnani/vscode-project-manager#522]
**Environment/version**

- Extension version: 1.57.1
- VSCode version: v12.2.0
- OS version: Win10 Pro 1909

**Steps to reproduce**

Had to do a windows restore (back approx 2 weeks), no changes made to VScode
1. VScode would not launch after restore > reinstalled
2. Launced VScode without issue, opened Project Manager and no project appear (No project saved yet)

![image](https://user-images.githubusercontent.com/13694330/122941647-7dc6ab00-d36d-11eb-96d1-8b19a9443624.png)

If I try clicking button or command "Project Manager: Save Project" I get a prompt:

![image](https://user-images.githubusercontent.com/13694330/122935140-017d9900-d368-11eb-8451-1912899e5a4f.png)

Have tried to uninstall, reinstall the project manager extension many times, but issue persists.

I have the file 'projects.json' in folder: \Users\{user}\AppData\Roaming\Code\User\globalStorage\alefragnani.project-manager
in which I can see all my previously saved projects data.

Also tried command "Project Manager: List Projects to Open" and get prompt:

![image](https://user-images.githubusercontent.com/13694330/122936049-c3cd4000-d368-11eb-9bc6-69603d32b581.png)

I wonder if you can help please !

**Comment by alefragnani** [comment]
Hi @celutions ,

If you see this error messages, the extension is not being properly initialized. You could try to open `Toggle Developer Tools` and reload the window, to see the messages on `Console`.

Based on your scenario, it seems _something has crashed_ (you said you had to reinstall VS Code), so I suppose you would need to reinstall the extension too. You said you did, but to be _fully reinstalled_ you **must** close VS Code after uninstalling the extension. That's because VS Code won't remove the previous installed extension on _reloads_.

But, I would suggest you to **backup your `projects.json` file**, before doing anything. On regular situations (even reinstall) it wouldn't be necessary, but because something weird happened to you before, it's safer to do a backup.

BTW, only the `projects.json` file is necessary. The other `XXX_cache.json` files  (if available) are recreated when you refresh the projects.

Hope this helps

**Comment by celutions** [comment]
Thank you for your quick response.
Okay, so I did uninstall the extension, close and restart VS Code, then installed again (a few times)

This is an error I got from dev tools console:
![image](https://user-images.githubusercontent.com/13694330/122982412-be84eb00-d392-11eb-876b-2a0c4743c491.png)

I noticed it was looking for: C:\Users\celsol\.vscode\extensions\alefragnani.project-manager-12.2.0\dist\extension
using file explorer I could not find a direcory "dist" in that path at all.

What I did find was
C:\Users\celsol\.vscode\extensions\alefragnani.project-manager-12.1.0\dist\extension.js  (115kb)

So I am assuming I had v12.1.0 previously and the path and .js file still exists there, however the path called does not exist for folder: C:\Users\celsol\.vscode\extensions\alefragnani.project-manager-12.2.0\

![image](https://user-images.githubusercontent.com/13694330/122983647-225be380-d394-11eb-9b23-5ee0fbe1a232.png)

I was thinking of just copying the dir and js file to that path, but have not tried that as it would be a "hack" of sorts.

I have backed up the projects.json file but I am more concerned about getting the extension to function.

Thanks for you help

**Comment by alefragnani** [comment]
Really weird the missing `dist` folder. It’s not the first time I see errors while installing an extension, but the first time this way. It’s probably an error in VSCode while extracting/installing the extension. 

BTW, the whole download/install extension process is made by VSCode, not the extension itself.

I would suggest you to:

- Close all instances of VSCode 
- Delete this extension folder _(you don’t need to worry about `projects.json`, because it is located on that other folder)._
- Open VSCode _(the extension will not be installed anymore)_
- Install the extension 
- If the error persist, you could install _older versions_ of the extension. You do this using the gear button. Then you can try to update the extension to the lates release

If, after all these steps, you are still unable to install the extension, I guess it should be reported on VSCode repo

Hope this helps

**Comment by celutions** [comment]
So what I did was:
open Extensions > click the gear button for Project Manager >  "install another version" option > selected v12.1.0

And hey presto, all back and working as expected (like before)

May have to tackle this issue again if I feel the need to update the extension (and do what you advised by deleting folder etc), but for now, it's working for me and this may or may not help others who may come across this issue.

Thanks for all your help

**Comment by alefragnani** [comment]
Glad to see it is working now.

It's probably a temporary issue (on VSCode side) so you could try again after the next updates.

The next extension update should be available in a couple of weeks.
