### ISSUE TITLE
[BUG] - Can not Download and Install Extension on Azure Data Studio

### ISSUE THREAD

**Issue by pzprovi** [alefragnani/vscode-project-manager#558]
**Environment/version**
Azure Data Studio marketplace search can not locate extension and for that reason we need to download and install manually.
 

**Steps to reproduce**

1. Go to menu File / Install VSIX
2. Can not located to download and install

When installed manually not work at all.

**Comment by alefragnani** [comment]
Hi @pzprovi,

This extension is not compatible to Azure Data Studio. It is available (and works) only for Visual Studio Code.

In fact, I didn't know about ADS up until now, so I have no idea how an extension could work on it.

A quick look at ADS documentation, and I didn't find any information about how a VSCode extension could be updated to work on ADS (and the limitations). I'll take a second look, in order to find about more info, but unless some _easy step by step_ appears, I don't see the extension available there.

Hope this helps

**Comment by alefragnani** [comment]
It seems the Azure Data Studio approach for VS Code extension is _totally manual_, with no extra documentation about what has to be made in order to extensions to become "ADS ready".

So, for now, I won't spend efforts to publish it there. 

If, in the future, the Azure Data Studio become an **oficial channel** for VS Code extensions, like Codespaces/GitHub.dev/vscode.dev, I would be glad to make the extension to work there.

Hope this helps
