### ISSUE TITLE
New Install - No projects saved yet

### ISSUE THREAD

**Issue by craiglintott** [alefragnani/vscode-project-manager#57]
Hi

Just installed your extension with Code 1.5.3
When I try run Edit Projects, to edit Projects.json, it does not open the json file but rather just states "No projects saved yet"

What am i doing wrong? (Total nube i know)

**Comment by alefragnani** [comment]
Hi,

You should use the **Save Project** instead, after opening some folder/project that you would like to store. Doing so, it will update the `projects` file. This is the _user friendly _ way.

The **Edit Projects** command is a shortcut to update the projects file , where you have to type all details. It's more _low level_ but easier for batch updates.

You actually found a good point for improvement, because I could have added an option to _create an empty projects file_ instead of just displaying this message. I will add this option intee next release.

Hope this helps

**Comment by craiglintott** [comment]
EXCELLENT! Thank you for your quick response. I am up and running now. Loving it.
