### ISSUE TITLE
[BUG] - Git Tab Missing / No request to maintain the Git base folder

### ISSUE THREAD

**Issue by Z0mbiel0ne** [alefragnani/vscode-project-manager#578]
**Environment/version**

- Extension version: 12.4.0
- VSCode version: 1.63.2
- OS version: Windows 10 Home 2004

**Steps to reproduce**

I tried to reproduce it in a different environment. Unfortunately unsuccessful

**Bug**

I installed a clean VS Code. Reseted all settings. After install of Projectmanager no Git Tab is displayed inside Project manager with prompt for maintaining the Git Base Folder. When i manually add the setting 

```
"projectManager.git.baseFolders": [
        "C:\\path\\to\\my\\git\\folder"
],
```
in `settings.json` also no Git Tab is displayed. Inside "C:\path\to\my\git\folder" are valid Git Repos that worked with older version of Project Manager

Greetings

**Comment by alefragnani** [comment]
Hi @Z0mbiel0ne ,

Do you mean inside the **Project Manager** view, you only see `Favorites` view, but no `Git` or `Help and Feedback`? If that's the case, I suggest you to click in the ellipsis button, located at top-right of **Project Manager** view, and be sure the `Git` view is selected.

Maybe, you moved the view to somewhere else (like the bottom Panels). You could try to use the `Project Manager: Focus on Git view`. It should display the view, whenever it is. 

Other than that, if you define some valid base folder and hit save in your settings, the extension should look for Git repos (with a progress bar displayed in the Notification's area).

BTW, what do you mean by _older version of Project Manager_. The 12.4 (latest) was released in September 2021, with no updates since then.

Hope this helps

**Comment by Z0mbiel0ne** [comment]
Hey,

thanks for the reply.

Is can see everything but no Git :D

Sadly there is not Git View to select.

![Screenshot 2022-01-05 143819](https://user-images.githubusercontent.com/16578286/148226771-9354b590-28c9-4875-97c4-a28247338d1b.png)

There is also no Project Manager: Focus on Git view command as you can see here:

![Screenshot 2022-01-05 143910](https://user-images.githubusercontent.com/16578286/148226773-c98d624b-7722-48bd-bdfd-ba2c1aeb2e8d.png)

Do you have any further tips?

**Comment by alefragnani** [comment]
The only reason (I'm aware of) the **Git** view wound't be available is if you, at some point, clicked on `I don't need Git projects` button, in the same **Git** view, on fresh installs.

![Screen Shot 2022-01-05 at 21 16 36](https://user-images.githubusercontent.com/3781424/148308164-e09af5e7-06d1-48c7-9901-a4d1f81b8fe7.png)

If you do so, the **Git** view will be hidden, and you won't be able to see it again, unless you use `Show Git Welcome Page` command located in the top right ellipsis button in **Favorites** view.

But, even if you clicked that button, and the **Git Welcome Page** is hidden, if you define valid paths to `projectManager.git.baseFolders` setting, the located repos would be displayed in the **Git** view.

If nothing works, try to find the `Project Manager: Refresh Git Projects` command. If for some reason the _caching_ is not working properly, the projects should be displayed.

Unfortunately, the extension has no _logging_ system yet, but I have a WIP branch about it. 

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
