### ISSUE TITLE
[FEATURE] - filter text field for list of git projects

### ISSUE THREAD

**Issue by ThomasSteinbach** [alefragnani/vscode-project-manager#589]
Hi,

it would be really helpful having a filter text box for this list:

<img width="303" alt="Bildschirmfoto 2022-02-18 um 11 43 08" src="https://user-images.githubusercontent.com/1683246/154667843-8f38dae6-7dd5-4773-88c7-085fb88d9310.png">

I just have a coulpe of "favorite" projects. Mostly I scroll through the list of my nearly 300 git projects to find the one to open. A filter would speed up that immense.

**Comment by alefragnani** [comment]
Hi @ThomasSteinbach ,

This has already been requested in #213, and in fact, I'm planning for the next release.

But, instead of a text field to search for, like the **Find in Files** Side Bar, it will be a _magnifying glass_ button, that when clicked, will open the same `List Project to Open` Input Box, which will display the projects from that Panel. The reason for different approach is because VS Code does not support API for a text field in Panels.

Hope this helps

**Comment by ThomasSteinbach** [comment]
Hi @alefragnani ,

thank you for the answer. That totally helped and I think I would prefer the `List Project to Open` over any other solution, as I can access this menu by a keyboard shortcut.

However is it possible to do a more fuzzy search over the whole git url and/or project path? I have a lot of projects named `eks` which are managed under customer relevant folders. So for instance if one such project is located under

```
/home/myuser/git/lab.my.company.com/customerx/projecty/eks
```

it would be nice to find the project when searching for `customerx eks` or `projecty eks`. Is that already possible (haven't found an option) or should I create a new issue for that?

**Comment by alefragnani** [comment]
Hi @ThomasSteinbach ,

Unfortunately, I can’t customize/change the fuzzy search. VS Code has no API for that. 

But, if you want the search also apply over the project path, you should set the `    "projectManager.filterOnFullPath"` setting to `true`. Doing so, both, the project name and its path will be used while filtering the projects.

Hope this helps
