### ISSUE TITLE
[BUG] - Icon in side bar not aligned

### ISSUE THREAD

**Issue by Ceasers** [alefragnani/vscode-project-manager#619]
**Environment/version**

- Extension version:   V12.6.0
- VSCode version: 1.68.1
- OS version: Windows 10.0.19043

**Steps to reproduce**

Project of type remote and workspace is left aligned, while project only has local folder has white space before its icon.
Are there any setting options can be adjusted or could it be a bug really?
![image](https://user-images.githubusercontent.com/7239629/177515495-b6a4af7a-5eac-4772-95cc-26557558389c.png)

**Comment by alefragnani** [comment]
Hi @Ceasers ,

Could you share which `File Icon Theme` are you using?

There is no _alignment_ on icons. Every icon is supposed to be positioned on the same indentation (provided by VS Code), and I never noticed such misalignment.

However, VS Code itself has a strange behavior if extensions provide its own icons instead of using their collection, and if the `File Icon Theme` you use don't provide an icon to `folders`, like `Seti`. It seems VS Code does _reserve_ the location of the icon. That's why you notice differences when you choose `None` or `Seti` as `File Icon Themes`. But, the extension already handles such behavior and, if the user uses any of these Themes, I use the icons provided by the extension, instead of VS Code collection. At least I don't see any error here.

Hope this helps

**Comment by Ceasers** [comment]
Thanks Alefragnani, I used seti before, and I made some switch between seti and None, now the issue is gone and all icons are aligned. Thanks so much for the detailed explanation.
