### ISSUE TITLE
[BUG] - Project manager icon disappeared from the sidebar.

### ISSUE THREAD

**Issue by mu60** [alefragnani/vscode-project-manager#641]
[](url)

**Environment/version**

- Extension version: 12.6.1
- VSCode version: 1.70.2
- OS version: macOS Big sur 11.6

**Steps to reproduce**

After updating the extension, the Project manager icon disappeared from the sidebar.
Project manager is displayed at the top of explorer, but I want to restore it because it is difficult to use.

<img width="2048" alt="スクリーンショット 2022-08-25 9 38 48" src="https://user-images.githubusercontent.com/36182207/186549565-88db4798-8197-4a6d-ba35-f339ca2431ff.png">

**Comment by alefragnani** [comment]
Hi @mu60 ,

A few _Side Bar icon missing_ issues has been faced before, and it has been always caused by some VS Code issue. Not only _installation process_ but _VS Code updates_ that somehow brakes the extension. 

### Solution 1 - reinstall the extension

In most of the cases, a **full reinstall** has fixed the issue. A full reinstall means:

* uninstall the extension
* closes all VS Code windows
* open VS Code again
* reinstall the extension

Doing so, the extension will be _removed_ from Extensions Folder, and VS Code should clear its cache. If you simply remove/install again on the same window (without closing VS Code), it almost never works.

### Solution 2 - Reset View location

Another solution is to _reset_ the view locations, using the `View: Reset View Locations` command. It is a VS Code native command, which resets any ui/panel/view customization you have made, resetting these ui components to its default state. The problem is, if you do any customization (drag & drop) on your views/panels, will be missed.

Unfortunately there is nothing else I can do. The icon follows VS Code specifications and no updates has been made for a long time.

Hope this helps

**Comment by mu60** [comment]
Thank you for your answer.
I solved it by doing solution 2.

**Comment by DicTag** [comment]
I tried solution 1 first, but unfortunately it didn't fix the problem and erased my projects.json. If you wanna try, back up projects.json first.
The real issue was that I accidentally dragged the icon into another sidebar, like the Explorer. You can find it there and drag it back to fix the problem. Solution 2 works if you can't find where you dragged it.

**Comment by yujiaao100** [comment]
Solution 2 works,Thank you for your answer.
