### ISSUE TITLE
[BUG] - When close the favourites menu, it can't be restored

### ISSUE THREAD

**Issue by vieiraes** [alefragnani/vscode-project-manager#656]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version: 

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment]
Hi @vieiraes ,

Please, could you provide more details?

Thank you

**Comment by nathanstone** [comment]
Hi @alefragnani,

Thanks for getting back to me, this helped me figure it out. It looks like the baseFolders setting does not appreciate a `~` in the paths listed. For example, here was my previous config:
```
"projectManager.any.baseFolders": [
  "~/Sites"
]
```
However, as soon as I updated it to the following the `Any` and `Git` options reappeared:
```
"projectManager.any.baseFolders": [
  "/Users/whatever/Sites"
]
```
This is strange because everything was working until recently, and my settings had always been the former. Also, after I changed the setting to the full path, I could change it back to the former and the options would still be available. I was able to replicate the issue by completely deleting the setting, then re-adding it using the `~` path shortcut. The options failed to appear again until I change the setting back to the full path.

**Comment by alefragnani** [comment]
Hi @nathanstone ,

That's weird. I use the same `~` approach, and has no issue. And the extension itself hasn't received any update since September. 

Maybe something OS related? Could you take a look if some error appears in the Console, using `Developer: Toggle Developer Tools`? If yes, please, open a new issue with the details.

> Based on this report, I'm thinking of displaying the related panel, even if no project is located, so the user will be sure the extension searched for projects

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments (from the original post) has been added since my first question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Comment by kantesilvestrsEvidentStudio** [comment]
I'm having exactly the same issue and I haven't done any settings changes to Project Manager extension. Only time the `Git` tab is available is when I disable and re-enable the extension, and it disappears again after opening project in a new window.
