### ISSUE TITLE
Use match-sorter for filtering and sorting the list?

### ISSUE THREAD

**Issue by kentcdodds** [alefragnani/vscode-project-manager#66]
Would you consider using [`match-sorter`](https://github.com/kentcdodds/match-sorter) for filtering and sorting the list? It's more user-friendly than [the current default method](https://github.com/alefragnani/vscode-project-manager/blob/d1c6c42d7fc7a4a0d7fb419e957638d0df4aca2d/sorter.ts#L5-L18). I'd be happy to create the pull request if you're interested.

**Comment by alefragnani** [comment]
Hi @kentcdodds ,

I would be glad to have a better _sorter_ than the default one (I just noted that isn't _case-insensitive_ 😢  ). But unfortunately, a _filter_ it not possible, because it's built in VS Code `PickList` API. 

I remember seeing some opened issues about a better match criteria in the VS Code `PickList`, so maybe you could suggest your package directly for them, and so, every package would benefit from it 👍 

Thanks.

**Comment by kentcdodds** [comment]
Filed there.

For now, I think that you could at least get better sorting with `match-sorter`, which would be a great start.

**Comment by alefragnani** [comment]
Sure 👍

**Comment by kentcdodds** [comment]
I don't use VSCode anymore, so this issue is irrelevant to me. I'll go ahead and close this. Thanks.
