### ISSUE TITLE
Prioritize names over paths when searching

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#67]
![](http://i.imgur.com/FL3HUFB.png)

The picture illustrates the issue nicely. I have to scroll way down the list to find `haxe`, which exactly matches my search term, because there are a whole bunch of other projects with that search term in their _paths_. Project names should have a higher priority than paths and an exact match like `haxe` should be at the top of the list.

I think this issue wasn't present in earlier versions. I guess paths probably weren't being taken into account then?

**Comment by alefragnani** [comment]
Hi @Gama11 ,

I tottaly agree with you, but I don't have control how the items are filtered/matched. It's built in VScode. I don't remember changing that, at least intentionally, but maybe this is being caused by the new way the list is presented, because of the new `.vscode` projects detection (which explicity tells to `matchOnDetail`, which means, the `path`).

I'm not in front my dev machine to test, but once available I will revert to an older version and if confirmed, I will update a patch.

Thanks for reporting :thumbsup:

**Comment by Gama11** [comment]
Thanks for the quick fix!

**Comment by Gama11** [comment]
>but I don't have control how the items are filtered/matched.

I guess this can't be improved on your end then? (I'd expect the exact match to be first)

![](http://i.imgur.com/wyehFXu.png)

**Comment by alefragnani** [comment]
Not yet... See #66 for more details
