### ISSUE TITLE
[BUG] - "What's new ..." always displays and sometimes it's outdated

### ISSUE THREAD

**Issue by tyler36** [alefragnani/vscode-project-manager#677]
I've been a long-time fan of this extension however recently it is driving me crazy.

Everytime I open a project it displays a "What's new ... 12.7" 
Everytime I close a project it displays a "What's new ... 12.0"; yes, a different, older version.
Everytime I re-open a project it a "What's new ... 12.7".
Everytime I open a project on Gitpod, it displays a "What's new" popup.

Ideally, I'd love to disable this "feature" completly.  However I know from searching for duplicate issues that you have no intention of allowing this. 

But seeing this pop up every single time I open AND close a project is excessive. The fact that they are different version hints there might be something else going on.

**Environment/version**

- Extension version: `12.7.0`
- VSCode version:  `1.76.0`
- OS version: WSL via Win10.

**Steps to reproduce**

1. Open up an exisiting project, it displays a "What's New in Project Manager 12.7"
![new-12-7](https://user-images.githubusercontent.com/7234392/223598648-2ce010d3-191e-4d69-846a-1362f5e521f2.png)

1. Close "What's new" tab.
1. Close project via "File | Close Remote connection." It displays a "What's New in Project Manager 12.0"
![new 12-0](https://user-images.githubusercontent.com/7234392/223598669-6ba3d21e-51f7-4842-a6d3-2c437db2d183.png)

1. Open previous project, it displays "What's New in Project Manager 12.7" again.

**Comment by reggiepy** [comment]
I have the same problem

**Comment by alefragnani** [comment]
Hi @tyler36 ,

I could reproduce the _broken_ What's New page. It was a missing update and it will be available in the next release at the end of the month.

The _outdated_ behavior, on the other hand, I couldn't reproduce. No matter if the project is located locally or WSL, if the extension is installed in the host (regular) or inside the WSL (using `remote.extensionKind` setting), it always display the current (newer) release. 

I think it displays 12.0 because you are using Gitpod or some VS Code _alternative_ like VS Codium, because that's the version number which is currently _unofficially_ available in open-vsx. The extension is not supported there yet, but will be, and can be tracked in #458 . I had planned to release a couple of months ago but couldn't focus back then, but things are getting better and I'll be able to have better cadence on releases.

Hope this helps
