### ISSUE TITLE
[BUG] - 12.7.0 not showing text and not working

### ISSUE THREAD

**Issue by eephyne** [alefragnani/vscode-project-manager#696]
I'v searched for similar bug but honestly I don't really know how to name this.

I installed vscode on a new laptop and all my extensions have been reinstalled.
Project manager 12.7.0 is not working (can't save project for exemple) and all the text seem to be missing or sometings (cf the screenshot)

![alt](https://i.imgur.com/VxBh3m5.png)

When downgrading to 12.6.1 its working fine and upgrading again redo this bug.

**Comment by alefragnani** [comment]
Hi @eephyne ,

The installation process is entirely handled by VS Code, with no touch by the extension itself, but sometimes it fails, and the installation seems corrupted.

When this happens (it already happened to me not only on my extensions but on others as well), the only way I could fix it entirely was a _full reinstall_ of that extension. By full reinstall I mean:

* Uninstall the extension
* Exit VS Code (Close all windows)
* Reopen VS Code
* Install the extension again

Closing all VS Code windows is necessary because only when you do this and reopen it, it will effectively remove the uninstalled extension from the "extension's folder". Otherwise, it reuses and you remain in the same stage.

But, since Profiles feature was launched in VS Code, I've noticed that it is not always working this way anymore, and it seems VS Code keeps copies of _other releases_ of the extension that are used by some profile. In this case, maybe it would be necessary to manually delete the extension's folder. But only do this if the above steps don't work. You can look at extension's folder using the `Developer: Open Extensions Folder` command in VS Code.

Hope this helps
