### ISSUE TITLE
Project switching does not work

### ISSUE THREAD

**Issue by janmarek** [alefragnani/vscode-project-manager#7]
Hi, I have Project Manage 0.4.1 installed on VS Code 0.10.8 for Mac. When I choose List Project in command pallete and confirm selected project by enter or by click, nothing happens.

**Comment by NTTAKR** [comment]
Exactly the same for me on Windows 10. I also have Project Manager 0.4.1 installed. 
Code version is also 0.10.8.

I already tried to provide the codePath in config. But nothing changes.

**Comment by alefragnani** [comment]
Hi, I noted a similar issue when starting **Code** from the _Application Icon_ instead of the _command line_, and to fix that, I noted that I had to define the `codePath` setting. It should be something relative to `PATH` Environment Variable (in Windows)

```
"projectManager.codePath": "C:\\Program Files\\Microsoft VS Code\\Bin\\Code.cmd"
```
> Note that the you have define `code.cmd` path instead of `code.exe` (in Windows). For  Mac, I think you have to use the _Show Package Contents_ context menu option to open up `Code.app` structure, looking for the correct startup, probably in the same `Bin` folder.

I tested with Windows 10 and Windows 7, but unfortunately my Mac is not available :cry: 

* Did it stop working for **Code 0.10.8**, or never worked?
* Does it work if you start **Code** from the _command line_?

Let me know if you have any progress.

**Comment by NTTAKR** [comment]
Hi Allessandro,

I have set the following options in my settings.json:

//-------- Project Manager Configuration --------

                // List the projects sorted by...
                "projectManager.sortList": "Name",

                // Indicate the full Code app path
                "projectManager.codePath": "C:\\Program Files (x86)\\Microsoft VS Code\\code.exe",

                // Should the project be opened using a New Window?
                "projectManager.openInNewWindow": false

Starting from App-Icon or Commandline makes no difference.

There is no error message or anything useful. It just does NOTHING.

By the way: If you close all edit windows in code you cannot use Alt-shift-p anymore. It is specified to only work in edit window.

Best regards,
  Andreas Kroll

NTT-SolutionWare GmbH
Andreas Kroll
Am Hang 1G
40822 Mettmann
Germany

Tel:      +49 (2104) 175 7590
Fax:      +49 (2104) 175 7591
Mobil:   +49 (151) 5288 2476

Sitz der Gesellschaft:             Mettmann                               Bank / BLZ / Konto:                 VR-Bank Mainz / 550 604 17 / 68470
Handelsregisternummer:       HRB 21698                             IBAN:                                     DE47 5506 0417 0000 0684 70
Amtsgericht:                           Wuppertal                              BIC:                                        GENODE51MZ2
Geschäftsführer:                    Andreas Kroll                         Kontoinhaber:                          NTT-SolutionWare GmbH

Von: Alessandro Fragnani [mailto:notifications@github.com]
Gesendet: Mittwoch, 10. Februar 2016 12:20
An: alefragnani/vscode-project-manager <vscode-project-manager@noreply.github.com>
Cc: Andreas Kroll <akr@ntt-sw.de>
Betreff: Re: [vscode-project-manager] Project switching does not work (#7)


Hi, I noted a similar issue when starting Code from the Application Icon instead of the command line, and to fix that, I noted that I had to define the codePath setting. It should be something relative to PATH Environment Variable (in Windows)

"projectManager.codePath": "C:\\Program Files\\Microsoft VS Code\\Bin\\Code.cmd"

Note that the you have define code.cmd path instead of code.exe (in Windows). For Mac, I think you have to use the Show Package Contents context menu option to open up Code.app structure, looking for the correct startup, probably in the same Bin folder.

I tested with Windows 10 and Windows 7, but unfortunately my Mac is not available [:cry:]
·         Did it stop working for Code 0.10.8, or never worked?
·         Does it work if you start Code from the command line?

Let me know if you have any progress.

**Comment by alefragnani** [comment]
Hi Andreas,

It appears to be the same problem that I faced. Note that you are defining `code.exe` path instead of `code.cmd`. Try changing it to: 

```
  "projectManager.codePath": "C:\\Program Files (x86)\\Microsoft VS Code\\bin\\code.cmd",
```

I also note that even without defining this setting, when **Code** was started via _command line_, it worked fine. But in my case, I have `C:\Program Files (x86)\Microsoft VS Code\bin` defined in `PATH` environment variable.

Hope this helps

And about the `keybinding` not working if you close all editors, I could reproduce. I opened [issue #8](https://github.com/alefragnani/vscode-project-manager/issues/8) to fix it. Thanks :+1:

**Comment by NTTAKR** [comment]
Hi Allesandro,

you are absolutely correct, even if I do not understand what makes the difference.

As soon as I changed the path tot he exe to the path to bin\code.cmd it all worked.

It works now for me from commandline as well as from the icon.

Thanks for your quick help.

Best regards,
  Andreas Kroll

**Comment by alefragnani** [comment]
Great news Andreas,

The `code.cmd` appears to be a _startup/launcher_. If I remember right, Atom has a similar technique, so I think this is an Electron stuff.

I hope this could solve @janmarek problem as well.

**Comment by janmarek** [comment]
No, I don't have C:\Program Files on my computer :)

I tried to create function code in my .bash_profile from https://code.visualstudio.com/Docs/editor/setup and set projectManager.codePath setting to "code" but it does not work.

**Comment by alefragnani** [comment]
> No, I don't have C:\Program Files on my computer :)
:smile: 

Other than the extension, does it work opening **Code** from the **Terminal**? I mean, if you type `Code .` it opens **Code** for the _current folder_ and if you type `Code ~/Documents/MyFolder` it opens **Code** for the _~/Documents/MyFolder_ folder?

**Comment by janmarek** [comment]
yes

**Comment by satokaz** [comment]
I also do not work in OS X (darwin) and  create a quick fix.
I can not well be handling the associated of the `projectManager.codePath` and `'open' + ' -b \'com.microsoft.VSCode\' ' `.
Therefore, this fix ignores `projectManager.codePath` for darwin .

```diff
diff --git a/extension.ts b/extension.ts
index 4f83f23..4107c89 100644
--- a/extension.ts
+++ b/extension.ts
@@ -144,11 +144,42 @@ export function activate() {
             let openInNewWindow: boolean = vscode.workspace.getConfiguration('projectManager').get('openInNewWindow', true);
             let reuseCmdOption: string = openInNewWindow ? "" : " -r";

-            exec(codePath + " " + projectPath + reuseCmdOption);
+            if (process.platform == 'darwin') {
+              exec('open' + ' -b \'com.microsoft.VSCode\' ' + projectPath + reuseCmdOption);
+              // exec('open' + ' -a \'/Applications/Visual\ Studio\ Code.app\' ' + projectPath + reuseCmdOption);
+            } else {
+              exec(codePath + " " + projectPath + reuseCmdOption);
+            }
```

**Comment by alefragnani** [comment]
Great  @satokaz . I was looking the contents of **Code** for Mac package, trying to understand how it is structured, so, thanks a lot :+1:. It appears it needs to use the same solution from [https://code.visualstudio.com/Docs/editor/setup](https://code.visualstudio.com/Docs/editor/setup). 

And, _something easier_ may come in [Febrary release](https://github.com/Microsoft/vscode/issues/2859) :smile: 

A friend of mine has a Mac and I will try to test the extension and this fix.

Can you confirm this fix works for you @janmarek ?

**Comment by satokaz** [comment]
> And, something easier may come in Febrary release

@alefragnani, Thank you for the useful information!

**Comment by satokaz** [comment]
@janmarek, It has created a package of applying the fix.
I think that behavior can be confirmed.
After unzip, please open your code to be .vsix.
```
$ code project-manager-0.4.1.vsix
```

https://github.com/satokaz/vscode-project-manager/releases/download/test/project-manager-0.4.1.vsix.zip

**Comment by alefragnani** [comment]
Hi @satokaz . I could test your code and it works even without the [Mac setup](https://code.visualstudio.com/Docs/editor/setup). But I missed the `-r` arg functionality (I couldn't make it work). Is it working for you?

I'm thinking in release an update with a _temporary `setting`_ that would use your fix, expecting the [February release](https://github.com/Microsoft/vscode/issues/2859) for a final version. What do you think?

Thanks for your help :+1:

**Comment by satokaz** [comment]
Hi @alefragnani.

> But I missed the -r arg functionality (I couldn't make it work). Is it working for you?

reuseCmdOption is to re-use the window that is open?
The following animation has open two projects in the new.
Is displayed, the window that was opened by selecting the project again.
I am aware of this behavior it useful :-)

![vscode_project_licecap](https://cloud.githubusercontent.com/assets/13635244/13031979/15ed1102-d325-11e5-9687-d687a86cccc1.gif)

> I'm thinking in release an update with a temporary setting that would use your fix, expecting the February release for a final version. What do you think?

There is no problem with a temporary fix.
However, In the fix of the February release it seems to have not been provided -r option to darwin.
[Add -h/-v command line args and linux/mac launch scripts #2650](https://github.com/Microsoft/vscode/pull/2650/files)

**Comment by nothnk** [comment]
I have the same problem with  Project Manage 0.5.0/ VS Code 0.10.8 for Mac. Not project change. :(

**Comment by alefragnani** [comment]
Exactly @satokaz . I personally prefer `-r` option by default :+1: 

@nothnk , could you check @satokaz fix? I pretend to merge it and release a new version tomorrow with it, so Mac users could also enjoy the package :smile: 

Thanks in advance.

**Comment by nothnk** [comment]
Hhi @alefragnani don't work :( first remove the version 0.5 and then I installed the version of @satokaz and still not working.

also tried with to set the path in the user settings

 // Indicate the full Code app path
	"projectManager.codePath": "/Applications/Visual Studio Code.app",

Thanks Ale looks good

**Comment by satokaz** [comment]
@nothnk, I'm sorry! I forgot to write something important.
following is the correct setting.

"projectManager.codePath": "com.microsoft.VSCode"

**Comment by nothnk** [comment]
Yeah!

@satokaz with that works in conjunction with the version 0.4.1 thanks!

**Comment by satokaz** [comment]
@nothnk , Thank you for checking!

**Comment by fallXone** [comment]
I'm having this same issue. Is there any fix coming for this? Switching projects is not working at all.

**Comment by alefragnani** [comment]
Hi @fallXone , are you using a Mac?
I want to release an update with @satokaz fix at the weekend.

**Comment by fallXone** [comment]
I am not using a mac, i'm on Windows 8.1

**Comment by alefragnani** [comment]
Did you tried the solution suggested above to Andreas, defining `  "projectManager.codePath"`?

**Comment by fallXone** [comment]
That does work, just seems odd that I have to do that?

**Comment by alefragnani** [comment]
Great! :+1: 

I agree, but it appears to be a problem with the `PATH` Environment Variable not being loaded (or being missing), when you open **Code** from _Application Icon_ instead of _command line_.

I have created an issue in **vscode** repo [link](https://github.com/Microsoft/vscode/issues/574) right at the beginning of extensions being available in **Code**, requesting an API for that, but until the API is released, I have to use the `shell` to do the work.

Sorry for the inconvenience.

**Comment by alefragnani** [comment]
Hi @satokaz , @janmarek , @nothnk , I just released an update with @satokaz fix. 

I also added a _temporary setting_ to enable this fix. So, after updating, you still need to add the following line to your `User Settings`.

```json
    "projectManager.useAlternativeMacOSXPath": "true"
```

With the February Release, the Code team intends to update the Mac OS X setup and hopefully this fix will not be needed. If so, I will update the package as well. 

Thanks a lot to @satokaz for the fix, and you two @janmarek and @nothnk for testing and for the patience :+1:

**Comment by satokaz** [comment]
@alefragnani , I has been updated to v0.5.1.It worked!
Thank you for providing useful extension!

**Comment by alefragnani** [comment]
Great @satokaz ! 
Thank you :clap:

**Comment by nothnk** [comment]
yeah! This works!

My user settings:
 //-------- Project Manager Configuration --------
    "projectManager.codePath": "com.microsoft.VSCode"
    ,  "projectManager.useAlternativeMacOSXPath": true

**Comment by alefragnani** [comment]
Great @nothnk  :+1:

**Comment by lelandcope** [comment]
On a mac using what @nothnk posted doesn't work if you set `projectManager.openInNewWindow` to `false`. Is there a way to have it open in the same window on a mac?

**Comment by alefragnani** [comment]
Unfortunately, I don't know @lelandcope . I hope that this could be fixed with February release, when **Code** team will update Mac and Linux install (no more `bash` scripts).
I don't have a Mac available for testing, so if you could test the Insider version and post the results here, I will appreciate :smile:

**Comment by satokaz** [comment]
@alefragnani , It has been improved in the vscode-insiders Febrary Release!

@lelandcope, 

Try to [vscode-insiders Febrary Release](https://code.visualstudio.com/insiders).

1. Run ` Command: Install 'code' command in PATH`
<img width="585" alt="2016-03-02 7 36 57" src="https://cloud.githubusercontent.com/assets/13635244/13444431/9daec348-e049-11e5-8083-e05284fd1212.png">
2. Check the placement of the `/usr/local/bin/code`
3. Add the following settings
in setting.json:
```
	//-------- Project Manager Configuration --------

	// List the projects sorted by...
	"projectManager.sortList": "Name",

	// Indicate the full Code app path
	"projectManager.codePath": "/usr/local/bin/code-insiders",

	// Should the project be opened using a New Window?
	"projectManager.openInNewWindow": false,

	// Should use the alternative approach in Mac OS X?
	"projectManager.useAlternativeMacOSXPath": false,    
```

![insider_licecap](https://cloud.githubusercontent.com/assets/13635244/13444608/a37677b6-e04a-11e5-9c1d-1e099e5d88d1.gif)

**Comment by lelandcope** [comment]
@satokaz @alefragnani Thanks for the quick replies. @satokaz the example you showed worked! Looks like its just a waiting game for the stable build to be able to do this. Thank you again.

**Comment by alefragnani** [comment]
That's great @satokaz  :+1: 

I will update the `readme` with this info as soon as the February release goes stable.

**Comment by satokaz** [comment]
Visual Studio Code  Stable February Release has been released.
I've checked.

1. Run ` Shell Command: Install 'code' command in PATH`
<img width="600" alt="2016-03-08 6 33 36" src="https://cloud.githubusercontent.com/assets/13635244/13584165/884bd550-e4f8-11e5-92dd-5dcfa7ec099d.png">

2. Check the placement of the `/usr/local/bin/code` (vscode insiders version: /usr/local/bin/code-insiders
3. Add the following settings
in setting.json:
```
	//-------- Project Manager Configuration --------

	// List the projects sorted by...
	"projectManager.sortList": "Name",

	// Indicate the full Code app path
	"projectManager.codePath": "/usr/local/bin/code-insiders",

	// Should the project be opened using a New Window?
	"projectManager.openInNewWindow": true,

	// Should use the alternative approach in Mac OS X?
	"projectManager.useAlternativeMacOSXPath": false,    
```
Please set to false always `projectManager.useAlternativeMacOSXPath`.
`projectManager.openInNewWindow` also works.

**Comment by janmarek** [comment]
@satokaz when code command is installed into path, you don't need to use absolute path

This is my configuration for current insiders build:

```
    "projectManager.codePath": "code-insiders"
```

Note that command has a different name for insiders build (this could also be mentioned in readme)
