### ISSUE TITLE
Add Proj name to window title

### ISSUE THREAD

**Issue by mrx23dot** [alefragnani/vscode-project-manager#705]
Type: <b>Feature Request</b>

In case I have multiple windows of VScode open all I see is:
```
file.c [admin]
file2.c [admin] 
```

in task manager, no idea which project they belong to.

Extension version: 12.7.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by alefragnani** [comment]
Hi @mrx23dot ,

In order to this to be supported, it would be necessary to VS Code support more _variables_ in `window.title` setting, but unfortunately, this is was considered _out-of-scope_ a few year ago (ref #98). So, I'm sorry to say but can't be made.

Personally, I use `"${rootPath}${separator}${appName}"` on my `window.title` setting

Hope this helps

**Comment by aaron13223** [comment]
I made a quick extension based on [this](https://github.com/microsoft/vscode/issues/202991#issuecomment-2310582766)

It works!
