### ISSUE TITLE
Highlight most important settings in README.md

### ISSUE THREAD

**Issue by EdTheC** [alefragnani/vscode-project-manager#73]
As a newbie VSCode user, I am having trouble with settings. It's not clear from the documentation where settings (eg  "projectManager.projectsLocation": "C\\Users\\myUser\\AppData\\Roaming\\Code\\User") would be added or changed.

Also, the $home concept needs a bit more explanation as it seems very powerful.

Could you please add a little to the docs to help out?

TIA

**Comment by alefragnani** [comment]
Hi @EdTheC ,

I don't think that the extensions should say how to configure VSCode, since the VSCode website already has a rich documentation area (https://code.visualstudio.com/docs/customization/userandworkspace). But yes, the extension's `README.md` could highlight the settings that matters most

I will make a few tweaks in the `README.md`, giving attention to this in the next release.

Hope this helps

**Comment by jb510** [comment]
PM is the first package most users will install, they're going to be more naive to the ways of VSC that most.

I too can't figure out where to put the settings for
projectManager.vscode.ignoredFolders and projectManager.vscode.baseFolders

Do these go in settings.json or on projects.json?  Is there a way to make them project root relative?  

I'm used to sublime text's project where I can specific exactly which folders I want to see in the folder tree, just trying to recreate that.

**Comment by alefragnani** [comment]
I'm sorry for taking so long to answer you. I saw your comment but weren't able to reply at the time and at the end, I forgot :cry: .

The `settings` described in `README.md` must be defined in `settings.json`, which you access via `User Settings`. The `settings.json` is where you configure VSCode and its extensions. If you intend to create _root_ relative settings, you must use `Workspace Settings`, but this extension does not support workspace relative settings.

The `projects.json` file is where the this extension stores the projects that you saved. It's an _internal file_ and you don't need to touch it, because the `Project Manager: Save Project` command is responsible for storing new projects. But, if you intend to _manually_ add/remove/update projects, then yes, you have to _touch it_ with `Project Manager: Edit Projects` command. 

Multi folder projects, on the other hand, is not available in VSCode yet. There is already an issue there, and it appears that they will _start experimenting_ in December/January_ Insiders release.

Hope this helps

**Comment by jb510** [comment]
Thanks!  Note however that the reason I was asking about directly editing the projects.json file was because I'd really like to import 20 projects and it's way easier just edit the .json file than to open and save them all the manual way.

Looking forward to multi folder support.  SublimeText 3's Project Manager does a fabulous job of including/excluding files and folders from multiple locations.  I've come rely heavily on this "cleaner" workspace environment than what VSC provides.

**Comment by alefragnani** [comment]
I thought you wanted to _import_ :smile: . That's one of the reasons that I created the _VSCode projects auto-detection support_. Next month I will release Git and SVN support as well.

I also used SublimeText for some time (still uses for large files) but personally don't like how the projects are stored. Having a _Projects Folder_ to store _project definition_ files _all together_ was a mess (at least for my workflows). In the end, I prefer how VSCode works :smile: 

I hope the VSCode team takes the best ideas of Sublime Text and Atom when designing this, so all users would like.

**Comment by jb510** [comment]
Well, "import" yes, but using same basic text editing instead of opening/saving dozens of projects.  It's way easier to just copy/paste/edit/paste/edit/paste/edit...  than to locate/open/save/locate/open/save...  

I'm a bit confused by your description of projects in sublime. I think sublime works both ways now, project definitions in a central location, or in the project folder itself.  When I first started with sublime the project definition being a file in the project folder seemed messy to me, but I came around though and can't imagine it any other way. Much like a .gitignore file being part of the repo it just makes sense to me to have my .sublime-project/workspace files in the root folder of the project. I then use the multiple paths to target my actual working folders (screenshot). My .git repo is a level down from that, which also means I can have "other" folder in the project but not in the repo without gitignoring them (like project notes) or inside the repo (like project notes to share).

This setup make me love projects in sublime, it's neat and quick to use.

I think you're referring to the optional setup where project files in one central location which always sounded crazy to me too...  

![2016-12-29 at 4 27 pm](https://cloud.githubusercontent.com/assets/801241/21555220/09660dc0-cde4-11e6-94ec-1374e3c60d7f.jpg)

**Comment by alefragnani** [comment]
Yes, I was refering to the  _central location_, because only with that I was able to _switch between_ all projects (appearing in `Projects` menu). Based on that workflow, I didn't know Sublime had `.sublime-project` support. Maybe was added after I switched to Atom (or only in version 3 - I started using version 2). 

That's exacly how VSCode works, but instead of a file, it has a folder (`.vscode`) because besides the `workspace settings` its inside that folder that you have `tasks` defined.
