### ISSUE TITLE
[BUG] - extension not working anymore - placeholders not interpreted

### ISSUE THREAD

**Issue by kbsali** [alefragnani/vscode-project-manager#739]
Hi,
I am really unsure how to debug this, but for 10 days now the extension is not working at all. The commands are not executable and the translations are missing (only seeing the translation keys). Could it be a conflict with another extension ?
![image](https://github.com/alefragnani/vscode-project-manager/assets/53676/dad8883f-4254-4a19-971b-d7a234795287)

**Environment/version**

- Extension version: v12.8.0
- VSCode version: 1.88.1
- OS version: Linux Manjaro

thanks for your help (and the awesome extension :))

**Comment by alefragnani** [comment]
Hi @kbsali ,

I think you may be facing an installation/update issue, as in the end of March, a new version was released. This new version added Czech translation and embraced localization of other resources inside the extension.

To _kind of debug_ this, you could call  the `Extensions: Toggle Developer Tools` command, and look for the `Console` window, for messages about localization files. Or you could call the `Extensions: Open Extensions Folder` command and open the `alefragnani.project-manager-12.8.0` folder, and look for `package.nls.json` file (as it seems you are using English locale), and see if the files are equals to the ones on this repo.

Otherwise, I would suggest you to reinstall the extension, using a _cold install_:

1. Uninstall the extension
2. Close all VS Code windows (completely)
3. Reopen VS Code
4. Install the extension again.

> This cold install process is necessary because it will ensure the _old_ extension is removed from VS Code internals, prior to installing it again, otherwise it will simply reactivate the extension. If you are using Profiles, I suggest you to uninstall the extension from all profiles, before reinstalling it.

This shouldn't delete your settings nor your saved projects, but backups are aways our friends 😬 

Hope this helps
