### ISSUE TITLE
Promote to project folder

### ISSUE THREAD

**Issue by jordanmaslyn** [alefragnani/vscode-project-manager#75]
Atom offered an extension ([https://github.com/forivall/atom-promote-folder-to-project](https://github.com/forivall/atom-promote-folder-to-project)) for promoting sub-folders within a project. This would allow subfolders to be accessible from the top level.

For example, I work a lot with CMSes. I prefer to open the root folder as the project, but much of my work happens within the theme folder (several levels deep). It is super helpful to be able to access such folders without digging through the entire hierarchy.

As a an additional feature request, it would be nice to have settings to determine which project folder the integrated terminal should open in by default (maybe allowing it to be dynamic based on currently open file?).

Thanks! If I can help with development of any sort, let me know. Haven't done any Electron extension development yet, but very proficient with front end dev stuff.

**Comment by alefragnani** [comment]
Hi @jordanmaslyn ,

I had this idea myself sometime ago (didn't know about the Atom package), but first, VSCode should support multiple folders in projects (https://github.com/Microsoft/vscode/issues/396), which stil has no ETA :cry: . 

The same dependency exists for you Terminal idea (maybe you could add a feature request in VSCode repo for this). Personally, I prefer the Terminal to be opened in the same directory as the active file, instead of the root folder. Maybe an idea for your first VSCode extension? :smile: . 

Hope this helps

**Comment by alefragnani** [comment]
Ops, the extension idea for _Terminal in the current directory_ already exists https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here

**Comment by alefragnani** [comment]
Hi @jordanmaslyn ,

Based on the newly released multi-root support in VS Code, I think that a better approach would be to create a new extension to support this **Promote to Project Folder** feature. Because of the model that VS Code decided to use _(how it works/stores the info)_ it does not fit inside this extension.

The good news is that it is fairly easy to develop extensions for VS Code, compared to Atom. I can help you if still have interest. I just suggest you to wait a bit for the API/Model becomes stable, because it is available only in the _insiders_ channel by now.
