### ISSUE TITLE
[BUG] - Folder icon does not open tree but HELP and FEEDBACK sometimes

### ISSUE THREAD

**Issue by melcarthus** [alefragnani/vscode-project-manager#773]
**Extension version:**
12.8

**VSCode version:** 
- Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z (2 wks ago)
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0

**OS version:** 
- MacOs 15.0.1 (24A348)

**Steps to reproduce**
I have not figured out steps to reproduce. But everytime I close all project and want to open a new one i get the help and feedback menu. This changes after I disable the extension and reload it again.

Sometimes the folder icon does not open the tree menu of project folders but instead the *help and feedback* menu opens instead.

Sometimes there are 2 *project manager* options one will be the help and feedback menu and one will be the folder tree. However they have the same name. Sometimes one disapears. Like in this instance, and I cannot get the folder tree to show.

<img width="787" alt="image" src="https://github.com/user-attachments/assets/59b49df0-fb3e-473d-bee4-fac5017a5640">

**Comment by alefragnani** [comment]
Hi @melcarthus ,

The extension has no control on the panels / side bar position or sizing, and once installed, VS Code is the one that handles the sizing / positioning of it. I have seen issues like this in the past, but mostly after updating VS Code, instead of simply disabling / enabling the extension.

I would suggest you to use the `View: Reset View Locations` command. It is a VS Code native command, which resets any ui/panel/view customization you have made, resetting these ui components to its default state. The problem is, if you do any customization (drag & drop) on your views/panels, it will be missed.

Hope this helps

**Comment by melcarthus** [comment]
Thanks for the suggestion. I accept that vs-code is doing this. I will have to reinstall it from scratch because the reset view locations does nothing.

**Comment by alefragnani** [comment]
If you are going to reinstall the extension, I just have a small tip. Not only _uninstall_ the extension, but also _close all VS Code instances_ prior to reinstall the extension. Simply because VS Code only removes uninstalled/outdated extension from your file system while starting. So, you have to close and open it again, in order to your system to be free of any _outdated_ extension resources.

Hope this helps
