### ISSUE TITLE
Invalid projects.json causes issues

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#82]
Using the latest version (0.13.0) + VSCode 1.8.1.

If the `projects.json` file is completely empty, the following error appears:

![](http://i.imgur.com/fSktzFA.png)

This is not particularly surprising.

However, clicking "Open File" here doesn't do anything. It even looks like the extension crashes entirely (?), since no project manager command works anymore:

![](http://i.imgur.com/UKAaqwF.png)

This means you have to manually locate the `projects.json` file to correct the issue (not a big issue in my case since I knew where it was, but this could be considered bad UX).

____________________

Note: if `projects.json` contains `{}` instead of being completely empty, it fails slightly differently:

![](http://i.imgur.com/T6ofEVz.png)

So that might be a different issue.

**Comment by equinusocio** [comment]
I have the same issue, where is the `projects.json` file?!

**Comment by Gama11** [comment]
(on windows)

`%AppData%/Code/User/projects.json`

**Comment by equinusocio** [comment]
Thank, on macOS is in `/Users/[USER]/Library/Application Support/Code/User/projects.json`

**Comment by alefragnani** [comment]
@Gama11 thanks for the detailed description :+1:. 

I think I have to revisit this code. It's probably related to the refactoring that was made to support `VSCode`, `Git` and `SVN` auto-detection.

But, I don't see why `projects.json` file should be empty, _unless_ you removed the projects from there and started to use `VSCode`, `Git` or `SVN` support, am I right? Or it was _cleared_ with the extension update?

In the meantime, try to add a temporary project in `projects.json`, until I'm able to release a fix.

Thanks for your help

**Comment by Gama11** [comment]
>But, I don't see why projects.json file should be empty, unless you removed the projects from there and started to use VSCode, Git or SVN support, am I right?

Yes, I manually emptied the file to check out the project auto-detection feature.

>In the meantime, try to add a temporary project in projects.json, until I'm able to release a fix.

Like I mentioned, that's what I did. I just thought I should report this anyway so the UX can be improved. :)

**Comment by alefragnani** [comment]
Better UX is aways a good point, but in this case, is really a bug :smile:

**Comment by samuelsuarez** [comment]
I submitted PR #81, which probably fixes this issue.

@alefragnani Can you please have a look and confirm if that's the case?

**Comment by alefragnani** [comment]
Hi @samuelsuarez , 

First of all, thanks for you PR. I didn't evaluate yet because I'm on vacation, and decided _give a break_ on some coding :smile: . I must return to play next week.

About the fix, I guess aren't related. The problem here appears to be _not handling malformed json files_, instead of _empty project list_. I didn't check/debug the issue yet to be sure, but if your PR fixes, I will be _veeery happy :grin:

**Comment by alefragnani** [comment]
Well, I can't simply read/write e-mails, developers loves to code 😄 

I debugged this issue and discovered some things:

1. An _empty file_ is not supported, but instead of leaving it empty, it should be **deleted**. That would be the case if you don't want any **Saved Project**, but only **VSCode**, **Git** or **SVN**. But, the `Open File` button should work, so I will fix that 😄 

2. An _invalid json file_ is supported, but is not working, so I will fix that.

It will be fixed soon, but first I have to merge 2 PRs and merge another _internal code_ that I'm doing. After that I have to check #84 

Thanks for your help

**Comment by alefragnani** [comment]
@samuelsuarez ,

Looks like you were right, your PR fixes the _empty list_ problem 👍 🎉. 

Thank you!
