### ISSUE TITLE
Project-Caching between vscode window doesn’t work correctly

### ISSUE THREAD

**Issue by mkszepp** [alefragnani/vscode-project-manager#85]
VsCode: 1.8.1
Project Manager version: 0.13.0
OS: Windows 10 - 64bit

1. Open project “xy” in vscode
2. Open a second vscode window with project “zx”
3. Save project “zx” in Project Manager
4. Close project “zx”
5. Try to reopen project “zx” with Project Manager, from window with project “xy”
The project “zx” will not displayed in the list.
6. After closing and reopening from project "xy", the project “zx” will displayed in Project Manager List

**Comment by alefragnani** [comment]
Hi @mkszepp ,

That's the expected behavior, since each VSCode session doesn't know about the others, and the caching is made _per instance_. 

It never bothered me, because I reload the VSCode instances from time to time, for many reasons, so didn't feel the pain.

I will take a look if that's something easy to change (changing in-memory for in-disk cache) so one instance woule _know_ the changes made by other.

Hope this helps.

**Comment by mkszepp** [comment]
Hi @alefragnani ,

thanks, for your prompt answer. I hope that your idea works.

I have got a simple idea, but I don’t know, if it works.

The first interaction from Project Manager loads the “project.json” file. So maybe you can store the timestamp from last file modify.
After selecting the command “Project Manager List” you can check, if the last modify date from file “project.json” was changed. If the timestamp was modified so it needs to reload the json. If there was no change, read from cache.
