### ISSUE TITLE
VS Code finds project.json only aftar ~5s from startup.

### ISSUE THREAD

**Issue by Aukstkalnis** [alefragnani/vscode-project-manager#96]
When new instance of VS code is created, it can't find project.json file immediately. But after 5s (or more) it can list projects.

**Comment by DavidBabel** [comment]
I think it's the common way for vscode to load extensions. Not sure something can be done for that

**Comment by alefragnani** [comment]
Hi @Aukstkalnis , 

Like @DavidBabel commented, this is how VSCode works. It takes some time to activate the extensions, and unfortunately there is no way to define _priority_ over other extensions. 

Since the extension activates _at startup_ (because of the `Status Bar` feature), it should start even sooner, but it may not be enough, depending on the computer speed and the number of installed extensions.

Sorry about that, but for now, there is nothing I can do 😢 

Hope this helps.

**Comment by alefragnani** [comment]
Closed via https://github.com/alefragnani/vscode-project-manager/pull/97

**Comment by Aukstkalnis** [comment]
Thank you. Now it works perfectly!
